bitwarden/jslib

- .npmignore
- package.json
- rollup.config.ts
- tsconfig.json
Based upon https://github.com/alexjoverm/typescript-library-starter
VS Code and Visual Studio uses the commonjs library for their IntelliSense, while webpack prefers the es5 version.
As an added bonus, documentation gets generated using typedoc.
> Add multiple build targets, for umd and es5.

- src/importers/passmanJsonImporter.ts
- src/services/import.service.ts
The importer reads JSON files generated by the Nextcloud app Passman.
The first tag is used as the folder name. This works well if passwords
have no or only one tag. If no username is set then the email address is
used as the username.
Files are not being imported.
> Add importer for Passman

- src/importers/passmanJsonImporter.ts
When importing my real data I noticed some names being cut off. The limit was copied from `gnomeJsonImporter.ts` assuming it's some internal limit.
After testing with a 200 character name that still was imported fine I think this limit on the name should be removed.
> Remove artificial limit on name length

- src/services/totp.service.ts
Steam uses a different format for printing their TOTP codes.
This pr allows to use this format by prefixing the OTP key with steam://
> Add support for Steam TOTP

- src/models/response/breachAccountResponse.ts
HIBP API V2 does not contain `logoType` property but a `logoPath` property containing the full path of logo.
> Replace logoType by logoPath in BreachAccountResponse

- src/electron/baseMenu.ts
- src/electron/electronConstants.ts
- src/electron/tray.main.ts
- src/electron/window.main.ts
Allow the app to be minimized to the tray icon if the window gets closed. This is disabled by default.
Tested (and therefore enabled for linux) on Archlinux.
See desktop pull request: https://github.com/bitwarden/desktop/pull/168
> Close to tray

- src/electron/electronConstants.ts
If this setting is enabled, the main window will be hidden after startup. Disabled by default.
This is useful if Bitwarden gets started automatically after boot.
See desktop pull request: https://github.com/bitwarden/desktop/pull/169
> Allow app to start minimized (as tray icon)

- src/angular/directives/flex-copy.directive.ts
Related to https://github.com/bitwarden/browser/pull/897.
Triple-clicking a password to select it completely and invoking a platform-specific copy action (e.g. pressing Ctrl-C) currently copies the password with unrelated newlines and whitespaces.
This change assumes that a password always consists of only one line and removes everything after a newline (`\n` or `\r\n`).
> Fix appFlexCopy improperly trimming newlines and spaces

- spec/common/importers/onepassword1PifImporter.spec.ts
- src/importers/baseImporter.ts
- src/importers/onepassword1PifImporter.ts
When I migrated my 1Password archive into Bitwarden I noticed that concealed fields in 1Password are imported as regular "text" fields in Bitwarden. While the content itself is imported correctly it can do better by setting the FieldType to 'hidden'.
This PR adds this feature and related specs.
> 1password 1pif importer: create hidden fields

- spec/common/importers/onepassword1PifImporter.spec.ts
- src/importers/onepassword1PifImporter.ts
Solves part of #18 
My export file is create by 1Password 6.
> 1password import does not import 1p identities as bitwarden identities
>
> I imported a 1pif file which contained several identities. They were imported as secure notes, even though bitwarden has an identity type. You can tell they are identities by looking this field : "typeName":"identities.Identity"
When no address is specified in 1Password, the address field is still exported, with blank strings in every subfield.
> 1password 1pif importer: create identity records

- spec/common/importers/onepassword1PifImporter.spec.ts
- spec/common/misc/throttle.spec.ts
- src/importers/onepassword1PifImporter.ts
Tested using 1pif export of 1Password 6
Export format does not include the `passwordHistory` key if the password was never changed, so checking for presence should be good enough IMO. 
solves part of #18
> 1password 1pif: import password history

- package-lock.json
- package.json
- src/angular/components/add-edit.component.ts
This is a companion pull request for [#237](https://github.com/bitwarden/desktop/pull/237) in the bitwarden/desktop repo. This change is needed for the custom fields sorting feature to work correctly.
> Add support for CdkDragDrop in add-edit.component.js

- src/electron/window.main.ts
Main goal of this change is to remove ugly (at least in my opinion) title bar from application on macOS, which looks terrible when app is using dark and nord themes. This is a simple css change in desktop (also a PR), with additional change in jslib to allow electron to hide titlebar on 'darwin' platforms.
Application is draggable by most of the empty spaces.
I tested it as well as I could, to make sure important elements do not cause window to be dragged. If there are any left, let me know. I hope i didn't break anything (I shouldn't really, this is just CSS).
Here are screenshots after changes:
> Prettier UI on macOS

- src/electron/tray.main.ts
- src/electron/window.main.ts
Fixed issue on MacOS where closing BW via the red button then reopening using tray icon wouldn't work.
See the issue on `bitwarden/desktop` here: [Issue 143](https://github.com/bitwarden/desktop/issues/143)
The issue was that when closing the window via the red circle, the `win` property in `windowMain` becomes null, and the window instance needs to be recreated.
> MacOS: Closing with red button won't open window again through tray icon

- src/electron/electronConstants.ts
- src/electron/window.main.ts
Adds a checkbox option to the window menu which makes Bitwarden always stay on top of other windows. This is really useful when copying more than one thing to an other program because the window doesn't get minimized. This option is disabled by default.
See desktop pull request: [https://github.com/bitwarden/desktop/pull/257](https://github.com/bitwarden/desktop/pull/257)
> add window option: always on top of other windows

- src/services/passwordGeneration.service.ts
While the generated passphrases are generally secure enough without the need for uppercase characters and numbers, I ran into the issue that a lot of websites still require these to be present when creating/updating your password.
I've added an option to the passphrase generator which does the following:
- Capitalize the first letter of each word in a generated passphrase
- Insert a digit at a random place in the the passphrase
Passphrases generated when this option is selected often do meet all the requirements on passwords imposed by websites without any manual changes, and the broader character set does not hurt I suppose.
Should I also submit PR's to the other Bitwarden repos to add this option in the browser extension, apps, etc?
> Add common password requirements option to passphrase generator

- spec/common/misc/utils.spec.ts
- src/misc/utils.ts
Resolves https://github.com/bitwarden/browser/issues/1023: high CPU usage issue with large data URLs.
The issue is caused by the regex used to determine whether the URL ends with a common TLD:
```
// Utils.getDomain
if (!httpUrl && uriString.indexOf('://') < 0 && Utils.tldEndingRegex.test(uriString)) {
...
}
````
> Bugfix https://github.com/bitwarden/browser/issues/1023

- src/angular/components/add-edit.component.ts
- **add-edit component**: Adjusted logic to allow saving of collection(s) on cloned items
> Enabled ownership/collection changes for cloned items

- src/angular/components/add-edit.component.ts
- **add-edit.component**: Fixed several lint warnings including missing whitespace, trailing whitespace, and incorrect inline string designation
> Fixed lint warnings in add-edit component

- src/abstractions/passwordGeneration.service.ts
- src/angular/components/password-generator.component.ts
- src/models/domain/passwordGeneratorPolicyOptions.ts
- src/services/passwordGeneration.service.ts
> Make sure the Password Generator enforces the specific rules set by an Organization for password generation. In the case of multiple Organizational rules, apply the stricter option.
- **abstractions/passwordGeneration.service.ts**: Adjusted abstraction to mirror function calls in `passwordGeneration.service.ts`
- **password-generator.component.ts**: Utilized new `getOptions` function that injects intermediate step for password options retrieval. It applies the rules set by the governing organization to the user's password generation options. UI adjusted by using information stored in the `PasswordGeneratorPolicyOptions` object. Because field's floors were being altered, the `normalizeOptions` function was used to further adjust potential changes.
- **passwordGeneratorPolicyOptions.ts**: …
> Enforce Password Generator Policy

- src/abstractions/policy.service.ts
- src/models/domain/masterPasswordPolicyOptions.ts
- src/services/policy.service.ts
> Update the policy service to allow client applications to retrieve a strict compiled object of master password policy options and also allow the policy service to evaluate a supplied password meets/exceeds the criteria.
- **abstractions/policy.service.ts**: Added the two new functions `getMasterPasswordPolicyOptions`and `evaluateMasterPassword`
- **domain/masterPasswordPolicyOptions**: Created object for storing the strictest master password policy options between organizations
- **services/policy.service.ts**: Added function to retrieve and compile the strictest master password policy options.  Added function that evaluates the supplied master password against the password strength in conjunction with the enforced policy options.
> Enforce master password policy

- src/abstractions/passwordGeneration.service.ts
- src/services/passwordGeneration.service.ts
Allows us to pass in some options to have policies enforced upon. need this for upcoming CLI PR where options are derived instead of pulled from storage.
> enforce policies when options already known

- src/angular/components/password-generator.component.ts
- src/models/domain/passwordGeneratorPolicyOptions.ts
- src/services/passwordGeneration.service.ts
> Add missing components for passphrase policy. Use existing data structures/patterns to implement a shared password generator (password/passphrase)
- **password-generator.component.ts**: Updated logic for defining a default type (user preference/password/passphrase). Updated `normalizeOptions` function to include raising the floor for the minimum number of words during passphrase generation
- **passwordGeneratorPolicyOptions.ts**: Added params for tracking passphrase policy options and default type selection and also added a helper method to retrieve whether or not the policy is in effect.
- **passwordGeneration.service.ts**: Updated `getPasswordGeneratorPolicyOptions()` function to instantiate/retrieve/set policy data options. Multi-org collision: password default type always wins (to …
> Password Generator Passphrase Policy

- spec/common/importers/lastpassCsvImporter.spec.ts
- spec/common/misc/sequentialize.spec.ts
- tsconfig.json
To gain more security, we should use `--noImplicitAny` option of tsc.
https://www.typescriptlang.org/docs/handbook/compiler-options.html
Some spec files needs to be fixed.
desktop already enables `noImplicitAny`.
https://github.com/bitwarden/desktop/blob/master/tsconfig.json
cli enables too.
https://github.com/bitwarden/cli/blob/master/tsconfig.json
> Add noImplicitAny to tsc compiler options

- src/abstractions/token.service.ts
- src/services/token.service.ts
- src/services/vaultTimeout.service.ts
> Allow applications to properly present login vs lock based the presence of auth tokens.  Don't save auth tokens to disk when a timeout is selected and the action is log out.
- **abstractions/token.service.ts**: Added `toggleTokens` to interface
- **token.service.ts**: Updated `setTokens` to handle async. Updated `setToken` and `setRefreshToken` functions to not save to disk if a timeout it set and the action is log out. Added `toggleTokens` function for adjusting token storage based on change in timeout/action. Added helper function `skipTokenStorage`.
- **vaultTimeout.service.ts**: Added `tokenStorage` dependency. Added call to `toggleTokens` on saving of timeout/action.
> [Auto-Logout] Update Token Service 

- src/abstractions/api.service.ts
- src/abstractions/cipher.service.ts
- src/abstractions/search.service.ts
- src/angular/components/add-edit.component.ts
- src/angular/components/ciphers.component.ts
- src/angular/components/groupings.component.ts
- src/angular/components/view.component.ts
- src/angular/pipes/search-ciphers.pipe.ts
- src/enums/eventType.ts
- src/models/data/cipherData.ts
- src/models/domain/cipher.ts
- src/models/request/cipherBulkRestoreRequest.ts
- src/models/response/cipherResponse.ts
- src/models/view/cipherView.ts
- src/services/api.service.ts
- src/services/cipher.service.ts
- src/services/search.service.ts
Added the following changes with latest commit:
* **search.service.ts** - filter can be 1 or array of functions (or null or any combination, array with nulls, etc.)
* removed deleted flag parameter for search function, ensure a deleted filter is included in call
* **components** - ensure restore functionality works, also ensure all deletes detect whether they should be soft or permanent deletes
> ## Objective
> Integrate the new API updates for soft delete (PUT /delete) and bulk operations as well as restore (PUT /restore) into the jslib common library for use by JavaScript based clients. This would integrate the fundamental tenants of:
> 
> * Items deleted now go to Trash (soft delete)
> * Items in Trash when deleted are deleted permanently
> * Items in Trash can be restored
> * …
> Soft delete - update cipher search and added restore functionality

- src/angular/components/add-edit.component.ts
- src/angular/components/view.component.ts
- src/services/cipher.service.ts
Previous changes to jslib modified the add-edit component to handle soft-delete and restore actions, however the web vault only uses that component, the other clients do use the view component. It was decided that we would add Delete actions to the View page, as well as for viewing a deleted item (from the trash) a Restore option would also be available from this screen.
* **add-edit.component.ts** - Miss on the i18n service call to get the proper dialog text in the confirmation for permanent vs soft-delete
* **view.component.ts** - Added new events and actions for handling delete and restore operations and event emitters
* **cipher.service.ts** - Previously missed and now discovered when working on the browser extension, when fetching from all ciphers to match a URL, Domain, pattern, …
> [Soft Delete] - view component to handle soft delete and restore

- src/cli/commands/login.command.ts
- src/misc/nodeUtils.ts
* the environment variable BW_PASSWORD
* prefix the command line argument with "file:" and the password will read from the first line of that file
* prefix the command line argument with "env:" and the password will be read from that environment variable
I would like to avoid giving passwords on command lines. From the command line it would then be written into command histories and visible to other users and processes on the same machine.
> Enable alternative ways for settings passwords

- src/services/vaultTimeout.service.ts
> Fix bug reported where during upgrade, defaults for a `null` timeout action resulted in user's being logged out.
- **vaultTimeout.service.ts**: Updated conditional to properly default to a locked state instead of logging out (incase the action is `null`)
> Bug fix: made lock default conditional check

- src/misc/utils.ts
When parsing a URL string that meets the proper format to construct a URL, but the hostname/host is malformed, you end up with an empty string for the hostname/host rather than `null`. We handle the `null` condition when comparing URLs for autofill, but not an empty string. This leads to two malformed hostnames/hosts being able to match `('' === '') == true`. This PR ensures that hostname/host parsing always treats an empty string the same as `null`.
resolves https://github.com/bitwarden/browser/issues/1267
> check for empty string on malformed URL

- src/models/domain/cipher.ts
Resolves bitwarden/mobile#973 for remaining client libs.
Tested on:
Had to use a slightly different approach since default values in TypeScript are not set when casting objects. Hence why it's instead checked if the value is null (undefined) in `Cipher` and not `CipherData`.
> Ensure viewPassword has a default value

- src/models/data/organizationData.ts
- src/models/domain/organization.ts
- src/models/response/profileOrganizationResponse.ts
> Create `UseBusinessPortal` boolean for use in client-side applications via jslib.
- **organizationData.ts**: Added `useBusinessPortal` boolean and updated constructor
- **organization.ts**: Added `useBusinessPortal` boolean and updated constructor
- **profileOrganizationResponse.ts**: Added `useBusinessPortal` boolean and updated constructor to look for the newly added view from the server side API response.
> [Business Portal] Added portal usage boolean to necessary objects

- src/misc/utils.ts
- src/services/cipher.service.ts
When loading the current tab, the cipher service loads creds matching the URL. It's possible to load malformed URLs into your matching, which then causes the entire tab to stop functioning. 
**src/misc/utils.ts** The call to getDomain was throwing an error when URL was invalid. Wrapped with try / catch and returned null in the event of issue, following the pattern in the rest of the method.
We should do checking for malformed situations - see https://github.com/bitwarden/browser/issues/1295 for some examples - from being entered.
> Prevent malformed URLs from blocking the loading of the current tab

- src/misc/utils.ts
- src/models/view/loginUriView.ts
It was requested in https://github.com/bitwarden/desktop/issues/449 that we don't parse out port in the Website list. Small modification / request, added port if it exists to the host that returns from getHostname to support this request.
**src/misc/utils.ts** Modified response - added if port isn't null, append to end of hostname.
> Modified response to include port if exists

- src/importers/firefoxCsvImporter.ts
resolves https://github.com/bitwarden/server/issues/831
Adds `url` header support for new firefox export format. Keep backwards compat with `hostname` header too.
> support url header for firefox import

- src/angular/components/lock.component.ts
Prompting for biometrics based on a query parameter is more suited for the individual client implementation of the lock component. I also could not get the original implementation here in jslib to build.
> move bio prompt to onInit in desktop

- src/abstractions/auth.service.ts
- src/services/auth.service.ts
Adds "complete" sso login method which support 2FA + sso code login in one step. This flow is used in the CLI and complements the existing "complete" login method for email/password.
> auth service support for "complete" sso login

- package-lock.json
- package.json
- src/angular/components/sso.component.ts
- src/cli/commands/login.command.ts
- src/services/passwordGeneration.service.ts
- Support SSO option when invoking the login command
- Support for other clients to call into SSO component ans pass parameters
> SSO login for generic clients and CLI

- src/electron/biometric.windows.main.ts
Fixes https://github.com/bitwarden/desktop/issues/507
This _should_ resolve an issue where the NodeRT module successfully loads on a Windows 7 machine due to necessary development libraries, etc. being present for a VC++ developer, however then fails at run time with an application crash because the appropriate Windows APIs are not present/available when invoked by the library.
> added try-catch around ext module calls

- src/angular/components/login.component.ts
> Move code that launches a browser tab for SSO flow into the shared library
- **login.component.ts**: Added `launchSsoBrowser` method. Cleaned up imports and adjusted constructor.
> [SSO] Login - added launchSsoBrowser method

- src/abstractions/index.ts
- src/angular/components/login.component.ts
`login.component`
changed variable `stateService` to be of type `StateService()`
combined the abstractions imports into one group
`abstractions/index.ts`
added an export for `CryptoFunctionService`
> Misc jslib cleanups

- package-lock.json
- package.json
- src/abstractions/collection.service.ts
- src/abstractions/folder.service.ts
- src/abstractions/search.service.ts
- src/angular/components/groupings.component.ts
- src/importers/kasperskyTxtImporter.ts
- src/misc/serviceUtils.ts
- src/misc/throttle.ts
- src/models/domain/importResult.ts
- src/models/domain/treeNode.ts
- src/models/request/importCiphersRequest.ts
- src/models/request/importOrganizationCiphersRequest.ts
- src/services/cipher.service.ts
- src/services/collection.service.ts
- src/services/folder.service.ts
- src/services/search.service.ts
TypeScript 3.6+ is required to access newer versions of the navigator. apis.
- TypeScript updated to 3.6.5 which is the minimum minor version required.
- TSLint updated to latest, however TSlint is now deprecated so we probably want to switch to ESlint and Prettier sometime in the future.
- @types/node updated to 10.17.28
> Upgrade TypeScript

- src/abstractions/cipher.service.ts
- src/misc/sortedCiphersCache.ts
- src/models/domain/sortedCiphersCache.ts
- src/services/cipher.service.ts
To be used from browser extension when autofilling.
Related PR: https://github.com/bitwarden/browser/pull/956
> Add new method for cycling through every login

- src/angular/components/change-password.component.ts
- src/models/request/setPasswordRequest.ts
Extend set password models to accept new api properties
update change password base component to work for setting password and other crypto keys for new users via sso
> extend functionality for set password flow

- src/services/auth.service.ts
On a new user SSO flow, there are no encryption keys to set on auth response. These are set later on in the process when setting the password for the first time.
> dont set keys if not there on sso

- src/angular/components/two-factor.component.ts
> Fix bug with success route in relation to potential 2fa + set-password combination. Moved parsing of query params into jslib because each angular application will parse/look for the same parameter in the same manner.
- **two-factor.component.ts**: Fixed route to the `set-password` component (across all platforms), by checking the returned `AuthResult` and adjusting the success route (if necessary)
> [SSO] Bug - Fixed set password route

- src/angular/components/set-password.component.ts
- src/cli/commands/login.command.ts
> The `set-password` flow needs to perform a full sync in order to pull down potential org policies. This flow will not be allowed on the `CLI` or `directory-connector` applications for the time being.
- **set-password.component.ts**: Added private `syncService`. Added tracking boolean for UI management.
- **login.command.ts**: Added error response for `resetMasterPassword` flow.
> [SSO] Set Password flow sync

- src/cli/commands/login.command.ts
CLI login command was using `environmentService.webVaultUrl`, which does not include logic to check base URL first. This PR fixes it by using the helper function `environmentService.getWebVaultUrl`
> change to environmentService.getWebVaultUrl

- src/abstractions/api.service.ts
- src/angular/components/sso.component.ts
- src/services/api.service.ts
Added a pre-validation check for SSO calls to pass the org identifier (domain_hint) through the Identity PreValidate endpoint to ensure the SSO pipeline _should_ work end-to-end.
* **api.service** - function calls the Identity /Account/PreValidate pre-validate endpoint which runs a full-spectrum deep validation of SSO setup before actually redirecting the user to attempt the SSO flow itself. This will show any error messages to the user in a friendly manner, and otherwise kick off the flow as usual/expected.
* **sso.component** - Added `preValidate()` method to wrap and handle the call to validate the domain_hint and pipe the error to the user if necessary.
> Wrap sso login with pre-validation check

- spec/common/misc/utils.spec.ts
- spec/web/services/webCryptoFunction.service.spec.ts
- src/angular/components/register.component.ts
- src/angular/components/set-password.component.ts
- src/angular/pipes/search-ciphers.pipe.ts
- src/services/search.service.ts
- src/services/webCryptoFunction.service.ts
Related to https://github.com/bitwarden/web/issues/653
Old IE Edge is no longer supported. This PR removes the hacks put in place to support the older Edge version so that the newer Edge version, when properly detected as "Edge" doesn't invoke the same hacks (and essentially break).
> remove old Edge browser hacks

- src/electron/biometric.windows.main.ts
Related to and _should_ resolve https://github.com/bitwarden/desktop/issues/507.
Apparently just a `try { ... } catch { ... }` alone isn't enough to prevent an app crash for some Windows 7 machines when attempting to load the WinRT node module used for Biometrics support (Windows Hello). Instead we need to simply circumvent that attempted load and just detect the major Windows version ahead of time and not attempt the module load on anything other than Windows 10+ (Windows Hello is not supported in prior versions of Windows, and Windows build 1511 is the earliest build supported by NodeRT module anyway).
Our current version of nodeJS we're using for build + dev doesn't yet support the `os.version()` (returning the build number) method, so we're stuck with `os.release()` (returns the major …
> Conditional load of biometrics API on Win10+

- src/services/user.service.ts
Any checks to `canAccessPremium` will throw an exception when not authed since there is no token to reference. This stops it from even trying to access the token.
> check authed before checking if token has premium

- src/angular/components/login.component.ts
SSO from the desktop in jslib was using the web vault URL directly, which is often `null` in self-hosted deployments, instead of using the derived URL method baked into the environment service for the web vault which handles the cascading nature necessary for getting the correct URL from the user's settings.
> Fixed web vault URL reference for SSO launch

- src/cli/commands/login.command.ts
- src/cli/services/cliPlatformUtils.service.ts
ref #165
This PR implements launchUri for CLI platform utils by using the `open` library. The `open` library is broken with packaged as a binary with `pkg`, so we handle that case manually.
> implement launchUri function

- src/abstractions/cipher.service.ts
- src/models/domain/sortedCiphersCache.ts
- src/services/cipher.service.ts
Relates to bitwarden/browser#1391
When using the search bar to launch a url & autofill the autofill process is not using the login that was clicked, it is using the last used login previous to the clicked login. 
We can locally track last launched logins and get that data back for autofill
> Add login launch data

- src/angular/components/view.component.ts
- src/models/domain/sortedCiphersCache.ts
- Added launch time storing to the View component
- Fixed a bug with autofill from lastLaunched that was causing totally unlauched logins to have priority
Relates to https://github.com/bitwarden/browser/pull/1405
> bug fix + added launch time to view component

- src/models/view/loginUriView.ts
This will allow users to launch the Remote Desktop client directly from
Bitwarden if their OS supports the URI scheme.
Per
https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-uri,
rdp:// is legacy and ms-rd: is the preferred one. I'm adding both so
that either can be used as ms-rd: is not available on all versions of
Windows and rdp:// is easier to add as a custom URI scheme in Windows 10
if it is desired.
> Add Microsoft RDP URI schemes

- src/services/lowdbStorage.service.ts
Resolves https://github.com/bitwarden/cli/issues/160
Pre-creates the data.json file on init and chmods it to 600.
For whatever reason, the mode is not set properly on the initial `writeFileSync`, so a follow up `chmodSync` is required.
> pre-create and chmod 600 data file

- src/abstractions/cipher.service.ts
- src/models/domain/sortedCiphersCache.ts
- src/services/cipher.service.ts
Instead of updating it every time you call getNext(), it will be updated in a separate call, to avoid updating the index when the cipher did not auto-fill correctly (e.g wrong frame)
Fixes https://github.com/bitwarden/browser/issues/1392
> New method to update the last used index

- src/enums/policyType.ts
See [Asana ticket](https://app.asana.com/0/1195018406457675/1196488889925152) for information about this feature as a whole.
This PR to jslib just adds a new PolicyType enum to be used in the web vault.
[Web PR](https://github.com/bitwarden/web/pull/669)
[Server PR](https://github.com/bitwarden/server/pull/962)
> added OnlyOrg to PolicyType enum

- src/angular/components/set-password.component.ts
- src/angular/components/sso.component.ts
- src/angular/components/two-factor.component.ts
- src/models/request/setPasswordRequest.ts
> Currently, when a new bitwarden/org user is created, they are given a status of `accepted`.  This can create issues for organizations trying to `confirm` the same user (which can't happen until they've set their master password). To alleviate the issue, change new user's `orgUser` status to `invited` until after they've set a master password.
- **set-password.component.ts**: Added new string `identifier` for parsing the query params and keep track of the entered org identifier. This is passed through to the API.
- **sso.component.ts**: Added org identifier to the state and saved (regardless of the `state` object's state). Passed along the org identifier to two of the potential routes (2fa, set password). Created function to parse org identifier from the saved `state` object.
- …
> [SSO] New user provision flow

- src/services/lowdbStorage.service.ts
Adds ability to get to next steps on https://github.com/bitwarden/directory-connector/issues/41
Add logging to the bwdc when initializing it's lowdb storage service so any failures, issues, warning, etc. which may result in wiping of the data file (`data.json`) will get appropriately logged for further troubleshooting.
The resulting output, for example, if there's a syntax error (or other error) with the existing `data.json` file may look like this:
```bash
$ node bwdc.js login
Error creating lowdb storage adapter, "Malformed JSON in file: /Users/<user>/Library/Application Support/Bitwarden Directory Connector/data.json
Unexpected token h in JSON at position 303"; emptying data file.
```
> Add logging to lowdb storage service

- src/enums/policyType.ts
It has been requested that we change the verbiage of the new OnlyOrg policy to be SingleOrg instead, this per fulfills that.
[Asana Ticket](https://app.asana.com/0/1195018406457675/1198564632123101)
> changed OnlyOrg enum to be SingleOrg

- spec/node/services/nodeCryptoFunction.service.spec.ts
- spec/web/services/webCryptoFunction.service.spec.ts
- src/abstractions/cryptoFunction.service.ts
- src/services/crypto.service.ts
- src/services/nodeCryptoFunction.service.ts
- src/services/webCryptoFunction.service.ts
In some upcoming work with Send, I will need to use HKDF to expand a smaller encryption key that is part of the URL to a larger encryption key needed for our AES encryption functions.
Today we have an implementation of HKDF-Expand in our crypto service, but it is rather specific.
This PR creates *generic* crypto functions for HKDF and HKDF-Expand (web-crypto and node implementation) so that they can be used for other general crypto operations that we may need. The PR also ports the existing HKDF-Expand function in crypto service to use these new generic functions.
As with all crypto functions, unit tests were written to verify the correct implementation.
> hkdf crypto functions

- src/models/view/fieldView.ts
This property was referenced in views and was being set in the Angular context, however was missing from the actual model type definition causing issues when needing to be referenced outside of the view and in other TypeScript files.
> Added missing member, showValue to Field

- src/electron/window.main.ts
This needs to be `false` so that chromium through electron doesn't suppress repaint/redraw needs when minimizing or altering window states. There are other aims and things this setting impacts, however should not be largely impactful for the remainder of Bitwarden's code base.
Note: If backgroundThrottling is disabled, the visibility state will remain `visible` even if the window is minimized, occluded, or hidden when testing through the Page Visibility API. `visibilityState` is not used/referenced anywhere in the electron world of Bitwarden today.
> Turned off background throttling for browserWindow

- package.json
Hi,
As per requested by @cscharf - This PR is raised to bump a NodeJS dependency (`https-proxy-agent`) which solves an upstream bug in the [CLI repo](https://github.com/bitwarden/cli/issues/181). 
The bug in question prevents you from log in successfully when running CLI commands behind an HTTP proxy.
> Bump https-proxy-agent dep. to 5.0.0

- package.json
- src/services/nodeApi.service.ts
I had prematurely accepted a package version update of https-proxy-agent which then broke the build via a TypeScript compile error on that dependency.
> Fixed import for HttpsProxyAgent

- src/abstractions/send.service.ts
- src/models/response/syncResponse.ts
- src/services/send.service.ts
- src/services/sync.service.ts
This PR adds support to sync and store sends locally with other vault data.
- Adds send service to centralize send business logic
- Extends sync response model to include list of sends from server
- Store sends locally on sync operation
> send service and syncing send data

- src/abstractions/platformUtils.service.ts
- src/angular/components/lock.component.ts
- src/cli/services/cliPlatformUtils.service.ts
- src/electron/electronConstants.ts
- src/electron/services/electronPlatformUtils.service.ts
- src/services/constants.service.ts
- src/services/crypto.service.ts
- src/services/vaultTimeout.service.ts
* Changed so that passwords are only stored in desktop (secure storage).
* Resolved a bug where `biometricLocked` was not set to true after manual lock (desktop), which provided access to some things from the lock screen (after first unlock).
* Added constants required for browser biometric unlock.
Required by https://github.com/bitwarden/desktop/pull/566 and https://github.com/bitwarden/browser/pull/1426
> Browser <-> desktop communication

- src/angular/components/two-factor.component.ts
> Based on the response from the server, the `successRoute` needs to be updated before any specific `Navigate` actions are called.
-  [Server - 996](https://github.com/bitwarden/server/issues/996)
- **two-factor.component**: Adjusted timing of `successRoute` to happen before any router navigation.
- Update to `web` that includes these changes
> [Bug] Update Success Route before Navigate action

- src/models/request/cipherRequest.ts
- src/services/cipher.service.ts
This is a companion PR to API changes found in bitwarden/server#994
* **cipherRequest.ts**: Add revision date to request model for validation.
* **cipher.service.ts**: Include revision date in encryption of ciphers so it can be included in the request model.
> Include revision date in cipher requests

- src/services/sync.service.ts
The motivation for this is https://github.com/bitwarden/cli/issues/129
where failed sync's are swallowed by try-catch. By moving the try-catch
to the outside it is possible to reuse the already existing
allowThrowOnError argument which callers can use to signal whether
fullSync should throw or ignore errors silently. This patch is
companioned with a patch to the SyncCommand CLI command to pass
allowThrowOnError.
Edit: see https://github.com/bitwarden/cli/pull/190, although the patches are independet of each other.
> sync: move try-catch out of needsSyncing and handle errors in fullSync

- src/services/sync.service.ts
Missed this in the last PR from https://github.com/bitwarden/jslib/commit/adcc618b42a7643b2500c7ed31fbe62a9a2ef3ee, which resulted in a lint/build failure: https://github.com/bitwarden/jslib/runs/1443397249?check_suite_focus=true
> Fix lint error

- src/angular/components/sso.component.ts
This resolves: https://community.bitwarden.com/t/sso-issues-with-desktop-app-and-cli/15604 (for Desktop)
The issue was caused by the `state` being modified when parsing the query string parameters from the web vault back into the Desktop. The identifier is needed in this case and is passed at the end of the state, however the state comparison with what's in local-storage for the desktop app will not match because it's only the "base" `state` value (w/o the `_identifier=...` appended).
Since this is a shared component and needs to work across clients/types, I instead went for a comparison method, `checkState()` that would take both state values and encapsulate the parsing, splitting, cleaning them for true comparison, vs. hard-coding further up the chain.
I also found an issue where the …
> Update SSO component to parse state for comparison

- src/abstractions/api.service.ts
- src/models/request/organizationUpgradeRequest.ts
- src/models/response/taxRateResponse.ts
- src/services/api.service.ts
https://app.asana.com/0/1195018406457675/1178713563045098/f
As Steve I need Bitwarden to collect sales tax from a manually defined list of postal codes in order to save us from world governments.
1. Added some simple billing fields to the orgUpgrade model to collect sales tax against.
2. Added API passthroughs for the GetAllActive TaxRate method to be used in the web vault
3. Created a model to use in (2)
https://github.com/bitwarden/server/pull/1017
https://github.com/bitwarden/web/pull/723
> Implemented tax collection for subscriptions

- src/abstractions/log.service.ts
- src/cli/baseProgram.ts
- src/cli/services/consoleLog.service.ts
- src/electron/services/electronLog.service.ts
- src/importers/baseImporter.ts
- src/services/auth.service.ts
- src/services/consoleLog.service.ts
- src/services/crypto.service.ts
- src/services/notifications.service.ts
- src/services/search.service.ts
Establish a centralized means of handling console logging. Partially resolves bitwarden/cli/issues/188, which calls out the need to shunt all stdout to stderr when the --response flag is used. This is the first step toward that.
* **log.service.ts**: node's console.time is used to measure time taken handling Ciphers and so must be implemented on logService.
* **cli/baseProgram.ts**: `--response` flag is meant to **guarantee** json output to stdout.
* **consoleLogService.ts**: Implement console.time similar to node's library. Output is in ms rather than s+ms.
* **electronLogService.ts**: Same as **consoleLogService.ts**
* **baseImporter.ts**: provide a basic consoleLogService in non-dev mode for importer. We may want to look at determining dev mode here. Use the logService for error …
> Use logService for console messages

- src/angular/components/sso.component.ts
SSO login for browser still leaves an extra hanging tab if 2fa is required to complete a login. This change passes an extra parameter specifying the 2fa request is for sso and clients can use that information as they may.
A companion PR, bitwarden/browser#1480, is submitted for Browser that uses this query parameter to close the 2fa window on successful login.
Closes bitwarden/browser/issues/1479
* **sso.component.ts**: Add query parameter sso='true' to default 2fa redirect.
> Specify to 2fa we're coming from sso

- src/electron/tray.main.ts
- src/electron/window.main.ts
Resolves the bugs found during testing for #212.
* Fix dock icon not working when minimized to menu bar.
* Fix window listeners not working after closing the main window
Since the main window on Mac can be closed without quitting the application, this caused the Tray window listeners to disappear and not work until the application was restarted. Resolved by setting up a callback in `createWindow`.
> Desktop fit & finish bugfixes

- src/electron/tray.main.ts
Prevents creating duplicate tray icons due to https://github.com/electron/electron/issues/17622
> Avoid destroying the tray icon in linux

- src/angular/components/view.component.ts
It is not possible to edit and share at the same time. Browser extension
currently utilizes this layout and it is confusing. This change is in
conjunction with altering that UI.
Relates to bitwarden/server/issues/976. Enables moving share button from the cipher edit page to the view page.
* **view.component.ts**: This is the parent class of browser's view component. These changes are to match existing functionality in the [add-edit.component.ts](https://github.com/bitwarden/jslib/blob/master/src/angular/components/add-edit.component.ts#L349)
> Move share button to view page

- src/enums/eventType.ts
Related to bitwarden/web/issues/686. Include missing Server EventType to known EventTypes.
* **eventType.ts**: sync Server and jslib Event Type enums
> Add missing event type from server

- src/electron/tray.main.ts
Related to bitwarden/desktop#493. Electron has an upstream issue/possible feature where tray click options are disabled and context menu is always displayed. This means our left and right click callbacks are being ignored and the stored context menu is being opened.
This is a workaround for the context menu, at least. `updateContextMenu` will be called upon updateTrayMenu and, if on Linux, the context object is updated.
* **tray.main.ts**: Helper methods to force update of context menu object if in Linux
> Force update of tray menu if on linux

- src/angular/components/export.component.ts
- src/importers/baseImporter.ts
This PR adds:
1. A fix to importing encryption json exports. We recently added the `organization` property to the base importer as a getter, but forgot to add the `get` keyword. This made it evaluate to a function, which always has a truthy value when trying to use it like a boolean.
2. Moves the warning messages to a dialog that prompts upon submitting the export.
Follow-up PRs will update the UI of each app and update to this jslib ref.
> fix org getter on import and export warning dialog

- src/angular/components/add-edit.component.ts
> Cloning a cipher when personal ownership is not allowed would result in an unexpected experience with the ownership list (nothing would be selected, but the personal option would be removed).  Fix by adjusting logic for downstream changes in clone mode when personal ownership is not allowed.
- **add-edit.component**: Added explicit check for `null` Organization ID on the cipher being edited and if allowing personal ownership was disabled - if so, the cipher's Organization ID will be updated to the (first) organization enforcing this policy forcing the necessary downstream UI updates for ownership/collection(s)
> [Bug] Clone personal ownership

- package.json
- spec/common/services/export.service.spec.ts
- spec/support/karma.conf.js
- spec/utils.ts
- src/services/export.service.ts
Do not export items that have been trashed. Related to [this community request](https://community.bitwarden.com/t/deleted-password-shows-up-in-vault-export/13246/14).
It seems like in the future we will want to optionally export trashed items with a flag showing they are trashed. However, this aligns closer to expected behavior for now.
* **package.json**: Added the [substitute](https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking) package to enable mocking of interfaces and match the mock framework used in bitwarden/server.
* **export.service.spec.ts**: Tested export of user-owned ciphers. Organization owned are not tested due to difficulty mocking out apiService.
* **karma.conf.js**: included utils.ts file for utility methods.
* **utils.ts**: Contains utility methods used in …
> Do not export trashed items

- src/abstractions/api.service.ts
- src/abstractions/cipher.service.ts
- src/services/api.service.ts
- src/services/cipher.service.ts
https://app.asana.com/0/1169444489336079/1199337616674667/f
related to bitwarden/web/issues/748
Cipher edit revision date validation is failing for ciphers which were restored from the trash. This is because restores update revisionDate on the server side, but do not send an updated cipher back to the client.
These changes force a call to the server after restore to get the new revisionDate of the cipher.
* **api.service.ts**: Change signature to expect response from restore calls. (bitwarden/server#1072)
* **cipher.service.ts**: Update local cipher db to match ciphers returned from restore calls
> Update revision date upon cipher restore

- src/models/domain/send.ts
- src/models/domain/sendFile.ts
- src/models/domain/sendText.ts
domain/Send.ts has a bug in its `toData` method and upon investigating it, the method is totally unused. This PR just removes these unused methods.
> Remove unused toData methods

- src/abstractions/sync.service.ts
- src/enums/notificationType.ts
- src/models/response/notificationResponse.ts
- src/services/notifications.service.ts
- src/services/sync.service.ts
https://app.asana.com/0/1199659118818122/1199511462356833
https://github.com/bitwarden/server/pull/1106
https://github.com/bitwarden/web/pull/799
As a Bitwarden Send user I would like my local Send storage to stay in sync across concurrent sessions.
1. Added new `notificationType` enums to match their siblings in the Server PR.
2. Added new `syncService` methods for handling Sends.
3. Added a new NotificationResponse object for Send notifications.
4. Added logic to the `notificationService` for handling the new notification types by calling their sync methods.
> Send Sync Notifications

- src/abstractions/search.service.ts
- src/services/search.service.ts
A simple search function for sends. Filters on Name, Notes, Text (for text sends), FileName (for file sends), and id for both send and file send attachment.
This is basically the same search functionality as implemented in `searchCiphersBasic`.
This code will be used in
* Cli implementation of Send
* To fix web send searches, which is currently non-functional
* **search.service.ts**: Adds searchSends to service implementation and abstract.
> Enable search for sends

- package-lock.json
- package.json
- src/services/consoleLog.service.ts
Addresses https://app.asana.com/0/1199657392022597/1199665585962888
Importing `browser-process-hrtime` breaks in different clients using various import styles. This is causing the search index to break in desktop and browser.
Changed to a different package for `hrtime` needs.
All clients will need to be updated to the the new module & jslib after this is merged.
> Lunr search bug

- package-lock.json
- package.json
- src/abstractions/api.service.ts
- src/abstractions/send.service.ts
- src/cli/commands/login.command.ts
- src/cli/commands/update.command.ts
- src/misc/nodeUtils.ts
- src/misc/utils.ts
- src/services/api.service.ts
- src/services/search.service.ts
- src/services/send.service.ts
These are changes related to Send in CLI (PR incoming). 
* **api.service.ts**: CLI needs to be able to access api's other than those configured for it, so ApiService's PostSendAccess accepts an outside url.
* **send.service.ts**: CLI does not have a file object, so instead sends in an ArrayBuffer directly as the contents of any files uploaded.
* **login.command.ts/update.command.ts**: A result of upgrading CLI to commander 7.0.0, options are no longer on a command object, but an OptionsValues object. This is just a refactor and shouldn't have any impact.
* **Utils.ts**: These helpers allow for compile-time errors in case of property renames. It emulates what you get from c#'s `nameof(property)`. The assign helper limits possible assignments to overriding values already on the given object …
> Add send to cli

- src/angular/components/send/add-edit.component.ts
- src/angular/components/send/send.component.ts
> Provide a starting point for shared components to be used in the Send integration to other angular platforms
- send/add-edit.component.ts: Full port of existing web based component.  
- send/send.component.ts: Ported existing web base component to jslib. Added `onSuccessfulRemovePassword` and `onSuccessfulDelete` callbacks in case other platforms perform these actions within different components
- Once patched with the web client, make sure existing send features work as they did initially
> [Send] Port web based components

- src/angular/components/send/add-edit.component.ts
- src/angular/components/send/send.component.ts
- src/enums/policyType.ts
Add disable send logic to Send components and define `DisableSend` policy type.
This policy will be used by organizations to disable organization users from creating or editing Bitwarden Sends. Delete is still allowed.
* **add-edit.component.ts/send.component.ts**: If any policy on any organization the user belongs to is enabled and that user cannot manage policies on that organization, send is disabled.
* **policyType.ts**: Add enum number for DisableSend policy
Logic for the disable will be tested in the first client to implement this policy, which will be web.
> Implement disable send policy

- src/electron/window.main.ts
Enables subpixel font antialiasing by explicitly setting Electron background color.
https://www.electronjs.org/docs/faq#the-font-looks-blurry-what-is-this-and-what-can-i-do
> Enable subpixel antialiasing

- src/cli/commands/logout.command.ts
Removing unused CLI command run parameter
* **logout.command**: This command was missed during the Send CLI jslib updates. This parameter is unused and should be removed.
> Remove unused logout argument

- src/angular/components/send/send.component.ts
Lately we've had failures updating the Send list on delete. This PR fixes those issues.
* **send.component**: The actual fix is removing the parenthesis. `load` => `refresh` is to match cipher.service behavior, but is not part of the fix
> Do not evaluate callback function when testing existence

- src/electron/services/electronPlatformUtils.service.ts
Linked to bitwarden/desktop/issues/705. The original complain is on export, but this change is for all saved files for Desktop. 
The default should be for any file downloaded from Bitwarden to grant permissions to only the current User (permissions = 600).
* **utils.ts**: This is the save method for all of Desktop. We open up the saved file in user read/write only mode (600)
Need to test for all downloaded items
* Attachments
* Exports
Need to test for all OS
* Windows
* Linux
* Mac
The expected behavior is that the logged in user can read and write to the downloaded file, but any other (non-super) user cannot.
> Chmod exported file permissions

- src/angular/components/send/send.component.ts
> Update `send.component` to following existing patterns for subscription to the `BroadcasterService` -> child class should handle.
- **send.component.ts**: Removed `BroadcasterService` references/implentation/imports from `ngOnInit & ngOnDestroy`. Moved `this.selectAll()` function call in `load()` to a conditional to add flexibility to `load()` function and child classes (requires no downstream change)
- [Web PR](https://github.com/bitwarden/web/pull/826)
> [Send] Update Send component

- src/electron/services/electronPlatformUtils.service.ts
Now that we are on electron 11, it is possible to detect the system theme on both Windows and macOS using `nativeTheme.shouldUseDarkColors` (previously it only worked on macOS).
This PR implements this into `electronPlatformUtils` service so that the desktop app can consumer it (future PR).
> detect dark theme based on system theme

- src/services/lowdbStorage.service.ts
Move db locking to post db file creation from #273 . This is necessary because Proper-lockfile, the locking package I'm using in bitwarden/directory-connector/#95 throws if the file it's locking does not exist. 
So, I'm locking around adapter creation rather than file creation.
> Do not lock until after the file is created

- src/services/vaultTimeout.service.ts
Needed to enable browser extension to properly extend VaulTimeoutService with some custom logic to handle safari timeouts better.
* Changed `platformUtilsService` to protected.
* Refactored `init` and split out `startCheck`.
Required by https://github.com/bitwarden/browser/pull/1615
> Add support for extending VaultTimeoutService

- src/angular/components/send/add-edit.component.ts
> Calling the `delete` function from the browser extension during the add/edit flow cannot be handled properly in the current state. Make the `delete` function more flexible by mirroring the return state of the `submit` function.
- **send/add-edit.component**: `delete` now returns `Promise<boolean>` so that the child class can properly handle navigation changes after a successful deletion (if necessary).
- `Browser` -> Yes, the child's `delete` signature/operations will need to be updated.
- `Desktop` -> No
- `Web` -> No
> [Send] Updated delete function for add/edit component

- src/services/import.service.ts
Required by https://github.com/bitwarden/web/pull/841.
* `import.service` - parse the validationErrors returned by the server, match them up to the corresponding import items, and format some nice error messages for the user.
> Improve import error messages

- src/services/import.service.ts
Minor amendment to #280. @clayadams5226 suggested adding +1 to the cipher index when displaying the error message to the user. In other words, start counting at 1 instead of 0. This should be easier for non-technical users to understand. It also matches the numbering of lines in CSV files when opening them in Excel or Google Sheets.
> Start cipher numbering at 1 in import error messages

- src/services/lowdbStorage.service.ts
A client just hit an issue with Directory-Connector where their lowdb file was wiped out due to being malformed. This makes sense for the most part since we don't expect clients to be editing that file directly _usually_. However, it does happen. A nicer thing to do is at least backup their data before blowing it out of the water.
* **lowdbStorage.service.ts**: Create a backup on adapter creation error. known error is malformed json
> Write backup before deleting lowdb database

- src/angular/components/send/add-edit.component.ts
1. Null checked the array that is returned when trying to split a datetime. This was throwing a console error when creating sends.
2. Initialized expirationDate to null instead of undefined for reliability 
3. Corrected the conditional that applies the datetime fallback to account for expirationdate not being required conditionally.
> Date time fallback fixes

- src/angular/components/send/add-edit.component.ts
**Addresses:** 
> for a Send with an expiration, you can go in there and clear that out, but you can’t save because expirationDateFallback will never be null again. Should probably also check expirationTimeFallback since they’re both required.
> last issue is the clear <a> tag doesn’t work and it’d be nice if we could hide the clear out buttons in the input or link the two fields
1. Check if either expiration date or time is null in `expirationDateTimeFallback()` and return null if true are instead of "T"
2. Throw an error if only one of the two is null informing the user to add both.
3. Added expirationDate and Time fallbacks to `clearExpiration()`
> fixed up the send date fallbacks again

- src/angular/components/export.component.ts
This separates the export warning messages into its own method, so it can be overridden by the desktop client for platform-specific formatting.
> Enable platform-specific export warning message

- src/angular/components/send/add-edit.component.ts
Added support for dropdown time selection in Safari & made sure formatting in and out of our various date/time input methods stays consistent (`MM/dd/yyyy hh:mm a` for display; `yyyy-MM-ddTHH:mm` for storage)
> Safari Date/Time support for Send dates

- src/angular/components/send/add-edit.component.ts
Found an issue with default formatting of the previous time value in Safari that was causing times like "17:00 PM" to display for the previous value. This PR addresses this by:
1. Moving the date option generation function to a protected method and checking it once: on load
2. Changing formatting of the time string from `HH:mm a` to `hh:mm a`.
> Safari Time Formatting

- src/angular/components/send/add-edit.component.ts
https://github.com/bitwarden/web/pull/879
https://github.com/bitwarden/browser/pull/1672
QA requested a few fix ups to the send date fallbacks.
1. The calendar popup for `<input type="date">` doesn't work in the Firefox browser plugin. This is for the same reason `<input type="file">` popups don't work, and has been handled in a similar way by adding some subtext telling users to pop out the extension to use the picker. The text based date input works as expected regardless of being in a popup or not.
2. Better error messages for input validation. Placeholders were created for messages in jslib but they didn't get added to clients.
3. We should auto populate `expirationTime` if `expirationDate` is set and no time is already present. Not doing so was causing confusion when trying to just …
> set default expiration time on date input for Sends

- src/cli/models/response.ts
- src/services/api.service.ts
Fix https://app.asana.com/0/1199659118818122/1200033242011053/f
Our proxy is blocking large file uploads with an text/html bodied error response. Handle those situations gracefully and never output [object Object] to CLI. Prefer serializing the error object for _some_ amount of information.
* **response.ts**: This file is used by CLIs to process a response for outputing to stdout. Do not allow output of `[object Object]`, it's not helpful. Prefer serialization in that case.
* **api.service**: Cloudflare is returning request too large information as status 413 with a text/html body. Handle that case in api.service error handling. This will return raw html, but it's better than nothing.
> Handle text response errors

- spec/common/importers/testData/safeInCloud/testData.xml.ts
- src/importers/safeInCloudXmlImporter.ts
Hello everyone, 
I recently switched from SafeInCloud and found the import tool to be not very good. I made some adjustments for myself and though I'd give them back to the community and this great otherwise great program.
I understand that I had to make some choices here which may not be liked by everyone and might not be the right thing to use in Bitwarden, but at least importing favourite status seems universally useful to me :)
I'd be glad to get feedback from you
Paul
**Changes**
- Keep favourite status when importing
- in SafeInCloud, the trash doesn't ever get cleaned automatically.
-  Currently, all deleted cards are imported, which can be a lot of very old ones
- I exempt deleted cards from being imported (I wanted to set cipher.deleteDate, but this didn't work)
- SafeInCloud …
> Enhance SafeInCloud import

- src/angular/components/premium.component.ts
Premium component is not detecting if a user has premium due to organizations. This updates the premium page of non-web clients to display that the user is already a premium member.
> **Note:** This behaves differently to Web, which tell you you have access already due to an org, but still displays the purchase form.
* **premium.component.ts**: Use userService's `canAccessPremium` because that method correctly checks all organizations as well as the user's token.
[ ] Desktop PR
[ ] Browser PR
> Use UserService to determine if user has premium access

- src/abstractions/api.service.ts
- src/abstractions/fileUpload.service.ts
- src/angular/components/attachments.component.ts
- src/models/request/attachmentRequest.ts
- src/models/response/attachmentUploadDataResponse.ts
- src/services/api.service.ts
- src/services/azureFileUpload.service.ts
- src/services/bitwardenFileUpload.service.ts
- src/services/cipher.service.ts
- src/services/fileUpload.service.ts
- src/services/send.service.ts
Enable direct-to-azure upload of cipher attachment items. Similar PR to #296.
* **api.service**: Deprecate old attachment upload methods and include required methods for direct upload
* **fileUpload.service.ts**: Add attachment upload method
* **attachment.component.ts**: Grab url from new api endpoints. Fallback to old if not available. Upgrade limit to 500MB
* **AttachmentRequest**: Match new Server models
* **AttachmentUploadDataResponse**: Response model containing upload information for attachments. Two cipher types are for organization vs personal attachment uploads
* **azureFileUploadService**: Improve error handling
* **bitwardenFileUploadService**: Generalize upload of a file to bitwarden. Now accepts and api callback to actual upload the form data.
* **cipherService**: Upload …
> Attachment azure upload blobs

- src/angular/components/send/add-edit.component.ts
I removed max size check in #296, but we decided to maintain a 500MB max upload for now (pending legitimate examples for greater need).
This puts the server side check back and ups it to the current 500 MB
* **add-edit.component.ts**: client side check on save.
> Check file size client side

- src/services/api.service.ts
The path for uploading an attachment file to a Bitwarden server was wrong. It shouldn't include `renew` in the path.
>Note: I have a PR on server (bitwarden/server#1229) to remove the `renew` string from the renew url path in order to match Send's controller paths
* **api.service.ts**: correct the path.
> Fix post attachment file path

- src/abstractions/api.service.ts
- src/enums/eventType.ts
- src/models/data/organizationData.ts
- src/models/domain/organization.ts
- src/models/request/organizationUserResetPasswordEnrollmentRequest.ts
- src/models/response/profileOrganizationResponse.ts
- src/services/api.service.ts
> Create the `ResetPasswordEnrollment` API that will set an Organization User's `ResetPasswordKey`.  
- **api.service/abstraction**: Created `putOrganizationUserResetPasswordEnrollment` API
- **eventType**: Added `OrganizationUser_ResetPassword_Enroll` and `OrganizationUser_ResetPassword_Withdraw` enums
- **organizationData**: Added `ResetPasswordKey` and `UserId`
- **organization**: Added `ResetPasswordKey` and `UserId`. Added helper method `isResetPasswordEnrolled`
-  **organizationUserResetPasswordEnrollmentRequest**: Created new request that has the `ResetPasswordKey`
- **profileOrganizationResponse**: Added `ResetPasswordKey` and `UserId`
> [Reset Password] Enrollment API, event type, and models update

- src/abstractions/search.service.ts
- src/angular/components/ciphers.component.ts
- src/services/search.service.ts
jslib changes for: https://app.asana.com/0/1169444489336079/1183168049159854/f
This expands organization searches to allow for advanced search functionality the same as in personal vault.
* **search.service.ts**: indexCiphers method optionally takes a list of ciphers to index. Organization view will pass all organization ciphers to this method on load in order to index only the organization's ciphers
* **ciphers.component.ts**: optionally pass ciphers to search. Organization view will pass the organizations ciphers to this search method
* **search.service.ts**: optionally take ciphers to search. Defaults to all ciphers from cipherService like normal.
> Pass ciphers to index and indexed ciphers to search service

- src/models/response/attachmentUploadDataResponse.ts
- src/models/response/sendFileUploadDataResponse.ts
Fixes https://app.asana.com/0/1153292148278655/1200144714522727/f.
The issue is I do not deep-parse this model and so the `sendResponse` property is an object with all caps as provided by the c# server.
* **attachmentUploadDataResponse**: Parse CipherResponse models returned
* **SendUploadDataResponse**: Parse SendResponse models returned
> Deep parse models

- src/models/export/cipher.ts
This enables immediately setting collections from the CLI on create. Specifying a collection that does not exist will still create the item, but associate with no collection.
The other location this code is used is on import of Bitwarden json data. However, collectionId is explicitly nulled out here to be resolved later at the server level.
1. Create cipher with organization and collenctionid specified from CLI:
```
node bw.js get template item | jq '.organizationId="<<orgID>" | .name="NEW LOGIN ITEM" | .login.username="TestUser" | .login.password="Password123" | .login.uris=[{uri:"https://vault.bitwarden.com"}] | .collectionIds=["<<collectionId that exists>>"]' | node bw.js encode | node bw.js create item
```
* expect success with cipher created and asociated with the specified …
> Add collections to ciphers in export model.

- src/electron/services/electronPlatformUtils.service.ts
Electron currently does not support the UI elements required for WebAuthn to work correctly on macOS and Linux. This was an oversight on my part and I've restricted it to only run on Windows at this moment.
I've added an Asana task to remove this restriction once https://github.com/electron/electron/pull/28349 has been merged.
> Restrict WebAuthn to Windows only for Electron

- src/models/export/cipher.ts
It appears that there are some issues with instantiating an Array by expanding a Set object through `[...set]`. This hopefully fixes this issue in other clients (`web` observed so far) requiting `downlevelIteration` option set in `tsconfig.json` in order to compile.
`downlevelIteration` comes with a warning that it will impact performance and increase verbosity for all javascript produces for any iteration. This doesn't seem worth it for this one line. Hopefully this instantiation works and we can get past this...
*  **Cipher.ts**: instantiate the collectionId array in a different way
> Use iterator compatible Array instantiation

- src/abstractions/platformUtils.service.ts
- src/cli/commands/update.command.ts
- src/cli/services/cliPlatformUtils.service.ts
- src/electron/services/electronMainMessaging.service.ts
- src/electron/services/electronPlatformUtils.service.ts
- src/electron/services/electronRendererStorage.service.ts
- src/electron/services/electronStorage.service.ts
- src/electron/utils.ts
- src/misc/analytics.ts
Since Electron has [deprecated the remote module](https://www.electronjs.org/docs/api/remote) we need to migrate away from it. The recommended alternative is to use `ipc` to explicitly communicate between the main and renderer. This was mostly straightforward to convert and I placed the handlers in `electronMainMessaging.service.ts` we might opt to create a separate service for this but since it handles messaging it seemed a suitable home for now.
* **src/abstractions/platformUtils.service.ts**: Promisified some async values.
* **src/electron/services/electronMainMessaging.service.ts**: Added handlers for renderer ipc calls.
* **src/electron/services/electronPlatformUtils.service.ts**: Converted remote to ipcRenderer.invoke.
* **src/electron/services/electronRendererStorage.service.ts**: …
> Remove electron remote

- src/electron/baseMenu.ts
cmd + w doesn't close the window on macOS - bitwarden/desktop#714
Based on @cscharf [explanation](https://github.com/bitwarden/desktop/issues/714#issuecomment-810554674) - it seems that issue was introduced in response to erroneous Apple Store approver request. 
The code change reverses previously made changes.
> fix:  cmd + w doesn't close the window on macOS (bitwarden/desktop#714)

- spec/common/services/cipher.service.spec.ts
- src/abstractions/crypto.service.ts
- src/abstractions/fileUpload.service.ts
- src/abstractions/send.service.ts
- src/angular/components/send/add-edit.component.ts
- src/models/domain/cipherArrayBuffer.ts
- src/services/azureFileUpload.service.ts
- src/services/bitwardenFileUpload.service.ts
- src/services/cipher.service.ts
- src/services/crypto.service.ts
- src/services/fileUpload.service.ts
- src/services/send.service.ts
This bug was discovered by our QA team prior to public availability. No public unencrypted data was uploaded.
This PR fixes the bug (cipher.service line 634) as well as:
* add cipher service test to ensure file upload data is encrypted
* Create a CipherArrayBuffer tiny type which signifies an encrypted array buffer. CryptoService is the only generator of these buffers and all upload methods require them, converting to a buffer only on upload.
* **cipher.service.spec.ts**: Quick test of uploading cipher array buffer file data
* **crypto.service.ts**: Return CipherArrayBuffer from encryptToBytes to signify an encrypted array
* **fileUpload.service/send.service/add-edit.component/azureFileUpload.service/bitwardenFileUpload.service/cipher.service**: Use CipherArrayBuffer
* …
> Fix cipher upload

- src/abstractions/user.service.ts
- src/angular/components/send/add-edit.component.ts
- src/services/sync.service.ts
- src/services/user.service.ts
Fixes a defect in https://github.com/bitwarden/web/pull/915: when a user verifies their email, they must log out and log back in again for the client to recognise the changes. This was confirmed to affect the desktop client, but in theory should affect others as well.
This is because I was using `tokenService` to check whether the user had verified their email, but the token is not updated when syncing the vault. However, we can get the same information via `syncService.syncProfile`, which is updated when syncing.
* use `userService.getEmailVerified` as the standard interface for checking whether a user's email is verified
* update this stored `emailVerified` value when syncing the vault
It's a bit of a chore to go back and change this, but I think the behaviour will be more in line with …
> Use syncService + userService instead of tokenService to manage emailVerified

- src/abstractions/api.service.ts
- src/services/api.service.ts
- src/services/fileUpload.service.ts
In #335, I foolishly tacked `/renew` onto the Send endpoint, when it is needed on `ciphers attachment` endpoint. This corrects that mistake and clarifies the SendFile method name.#278 
update jslib references for:
I'll do these jslib updates at the same time as #348
> Fix mistake and clarify api method name

- src/abstractions/api.service.ts
- src/services/api.service.ts
Add an optional apiUrl to Send download requests. This is needed for CLI to download Send files from non-configured Bitwarden Servers. 
Web does not have this issue because it can assume api from its own url.
update jslib
I'll do these jslib updates at the same time as #347
> CLI specifies bitwarden api for send download

- src/angular/components/view.component.ts
I didn't realize in #312 that [Desktop](bitwarden/desktop) and [Browser](bitwarden/browser) both use a separate angular component to download attachments. As a result, those projects were always attempting to download attachment files from the `attachments` storage container rather than the one specified by `AttachmentData`, resulting in Azure 404s.
This PR implements the same attachment download scheme as in `attachments.component.ts`
* **vault.component.ts**: re-implement attachment download scheme
update jslib references are only relevant in Desktop and Browser clients
> Use new attachment download data

- src/abstractions/search.service.ts
- src/services/cipher.service.ts
- src/services/search.service.ts
Fixes https://app.asana.com/0/1169444489336079/1183168049159854/f. A defect in organization vault advanced searching.
Searching a user vault after searching an organization vault leaves a subset index on SearchService which consists only on org vault items. To fix this, I've added a property to SearchService that indicates the entity for which an index was built.
A null indexedEntityId specifies it is the users entire vault. Otherwise, organizations specify their id to signify the index is a subset.
User's vault will re-index if the indexed entity does not match the users id or null. At the moment, user's vault does not set userId because indexing occurs in the setter for decryptedCipherCache, which cannot be asynchronous.
* **search.service.ts**: Update indexing to accept indexedEntity …
> Specify Organization indexed on search service

- src/angular/pipes/color-password.pipe.ts
Original PR on `Desktop`: 
- [#844](https://github.com/bitwarden/desktop/pull/844#event-4628417442)
Issues this PR is related to: 
- [#768](https://github.com/bitwarden/desktop/issues/768)
- [#1682](https://github.com/bitwarden/browser/issues/1682)
The issue is associated with an angular pipe ColorPasswordPipe used for sanitizing HTML and colorizing the password. Unicode characters do not play well with this Pipe because of issues with Unicode, ie: "💩".length === 2, and how it parsed through a basic string. I've updated the Pipe to use [Array.from](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) because it is a simple approach that will keep Unicode characters properly grouped. I've also set the type for emoji in case there are any desires to …
> Update color-password.pipe.js to handle Unicode/Emoji correctly accross platforms.

- src/abstractions/search.service.ts
- src/services/cipher.service.ts
- src/services/search.service.ts
Fix for issue I missed while developing #356. We were getting stuck in an infinite load loop where we were basing logic on a dirty state of search service. This await enables us to wait until an index is complete, then update it rather than being kicked out of indexing early because it is in progress.
This allows `CipherService` to await indexing and restart with the full ciphers list.
* **search.service**: move indexing hard work to a private method so we can store its promise and allow for outside awaits on it. Add await and clear method that will block until indexing is completed then clear out the index. Also reset indexedEntity value when clearing index.
* **cipher.service**: await and clear index prior to re-indexing if the indexed entity is not the full vault.
> Allow external awaits of indexing

- src/services/azureFileUpload.service.ts
During an azure block upload, if the last block PUT request takes too long, the upload URL will time out prior to the block list request being sent up. This results in an authorization error.
The fix is the renew the upload url just prior to block list PUT as well.
> Fix auth error if last block put takes too long

- src/electron/services/electronMainMessaging.service.ts
- src/electron/services/electronPlatformUtils.service.ts
In #332 I removed the remote module and moved the save file logic to happen in the main process instead. This had the unfortunate side effect of slowing down file saving quite significantly for large files. Changing the logic to use the same download method we use in the browser extensions resolves this since we no longer need to send content between processes.
- **src/electron/services/electronMainMessaging.service.ts**: Remove `saveFile` ipc handler.
- **src/electron/services/electronPlatformUtils.service.ts**: Change download to happen in the renderer.
Verify downloading attachments works similar as before on all platforms.
> Change download to happen in the renderer

- src/abstractions/crypto.service.ts
- src/services/crypto.service.ts
When running multiple desktop applications (portable and installed) using different accounts it was possible for the application to get confused and use the wrong key to unlock and decrypt items. To avoid this we validate the key prior to returning it and should it be invalid we delete it from the storage.
- **src/abstractions/crypto.service.ts**: Added new method `validateKey` used to check if the key is valid for the stored encKey.
- **src/services/crypto.service.ts**: Implemented `validateKey` and refactored `shouldStoreKey` to be more readable.
> Validate key before using it

- spec/common/importers/nordpassCsvImporter.spec.ts
- spec/common/importers/testData/nordpassCsv/nordpass.card.csv.ts
- spec/common/importers/testData/nordpassCsv/nordpass.identity.csv.ts
- spec/common/importers/testData/nordpassCsv/nordpass.login.csv.ts
- spec/common/importers/testData/nordpassCsv/nordpass.secureNote.csv.ts
- src/importers/baseImporter.ts
- src/importers/nordpassCsvImporter.ts
- src/services/import.service.ts
As requested by a new user. last week during the "Bitwarden for Beginners"-Crowdcast, Bitwarden is missing an importer for Nordpass. 
This PR changes that 😉
I also fixed a minor thing in the setCardExpiration-method in the baseImporter. I added a removal of all possible whitespace before continuing the extraction.
> Add support to import from Nordpass(.csv)

- src/angular/components/send/add-edit.component.ts
We currently do not include the encryption process in the formPromise. Which means there is a slight delay between submitting the form, and form promise starting. Which would potentially allow users to start multiple requests. To avoid this I added the encryption step to formPromise.
> Include encrypt in formPromise

- src/angular/components/add-edit.component.ts
- src/importers/baseImporter.ts
- src/importers/bitwardenCsvImporter.ts
- src/models/export/cipher.ts
- src/models/view/cipherView.ts
- src/services/export.service.ts
I'm getting a few errors because the new `cipher.reprompt` property does not have a default value set in some places. e.g.
* if you create a new cipher and save it without changing the value of the reprompt checkbox, it tries to save a null value
* all imports fail because imported ciphers are not initialized with a default reprompt value
On the import/export question, should we export this value so that users can import & export without any change in behaviour? Currently I've just initialized it to `CipherRepromptType.None` on all imports, but users may not be expecting that if they're importing a vault backup. Happy to do this if required as I'm poking around in the import/export code at the moment.
@Hinton I know you're still working on this feature, let me know if this is helpful or …
> Default values for cipher.reprompt

- src/electron/biometric.darwin.main.ts
- src/electron/biometric.windows.main.ts
- src/electron/electronConstants.ts
- src/electron/services/electronMainMessaging.service.ts
When starting the desktop application on launch or when running using `npm run electron`, the biometrics prompts can be quite annoying. This PR adds the boilerplate required to add a setting to the desktop application for disabling the auto prompt behaviour.
- **src/electron/biometric.{darwin|windows}.main.ts**: Set `noAutoPrompt` text on windows or mac.
- **src/electron/electronConstants.ts**: Add some constants required to setup no auto prompt.
- **src/electron/services/electronMainMessaging.service.ts**: Add ipc callback for checking if the window is visible.
>  Add setting to disable biometric auto prompt on desktop

- src/angular/components/send/add-edit.component.ts
Fixes swallowing of form errors introduced in #368.
Submit form promises are attached to in `api-action.directive.ts` to reset form loading indicators and show error toasts. We can't silently catch errors in them.
* **send/add-edit.component.ts**: Remove try/catch from promise and wrap await.
> Reject form promises for proper error handling

- src/cli/baseProgram.ts
- src/services/cipher.service.ts
#356 incorrectly assumes that the `searchService` generator in `cipherService` will always be available. CLI does not currently use SearchService so this is null. A null check is added where `searchService` is accessed.
* **cipher.service**: Check null search service 
* **baseProgram.ts**: chalk has been updated and now exports two objects, set the default export as `chalk` for use in responses.
>  Fix null search service checking

- src/abstractions/api.service.ts
- src/models/request/userBulkReinviteRequest.ts
- src/services/api.service.ts
Currently org administrators needs to manually re-invite each user which requires multiple steps in the UI per user. To streamline this I've added a new bulk api which allows for re-inviting multiple users at a time.
- **src/services/api.service.ts**: Added new method for reinviting many organization users.
- **src/models/request/userBulkReinviteRequest.ts**: New request model for bulk invites.
https://app.asana.com/0/1198901840263430/1200202229721743
> Bulk re-invite of org users

- spec/common/services/export.service.spec.ts
- src/importers/bitwardenJsonImporter.ts
- src/services/export.service.ts
- src/services/import.service.ts
Fix the following defect:
> When a user makes an encrypted export of their vault, rotates their encryption key, and then attempts to import the encrypted JSON, the web vault doesn't always throw an error. Sometimes, corrupted/blank vault items are imported instead.
The problem is that `importService` only checks the first, middle and last items of an import to make sure they parsed/decrypted correctly. All of these 3 items must be "bad" for the import process to be aborted. However, the error checking only works for Login items, any other items will pass through it. Therefore, if a Card, Identity or Secure Note is in the first, middle or last position, the import will always succeed even if decryption failed.
At first I was going to include a hash of the `encKey` in the encrypted JSON, so …
> Increase error checking on imported Login items

- src/abstractions/export.service.ts
- src/models/export/event.ts
- src/models/view/eventView.ts
- src/services/export.service.ts
Closes https://app.asana.com/0/1199950673439194/1155011472108808/f
Adds the ability to export Organization events to a csv.
* **export.service.ts**: Add csv creation for array of EventViews -- this turned out to be crazy simple since the component already does all the fetching/filtering for us.
* **export/event.ts**: The export model for Events. `humanReadableMessage` is preferred because the `EventView` message has html to link to searches and specific policies.
* **eventView.ts**: The full data available from event messages.
> Export Organization events

- README.md
With @Hinton bumping node to 14 recently, I've adjusted the README to show the need for Node 14.17 (LTS)
> Add node including version to requirements in README.md

- src/electron/services/electronStorage.service.ts
Fix https://github.com/bitwarden/desktop/issues/894.
The problem is that we were saving a Set object to localStorage [here](https://github.com/bitwarden/jslib/blob/master/src/angular/components/groupings.component.ts#L162). However, `electron-storage` requires that stored values are serializable. `Set` objects are not:
``` node
> JSON.stringify(new Set([1, 2, 3]))
'{}'
```
When the empty object (`{}`) was loaded from storage, it passed the `null` check but caused the `Set` constructor to throw an error (because it is not an iterable).
`electronStorage.service` - check if the value is `instanceof Set` and if so, convert it to an array before saving.
Desktop `jslib` will need to be bumped after this is merged, and maybe a hotfix put out.
> Convert Sets to Arrays before saving locally

- src/services/cipher.service.ts
Minor tweak to #199. If a newer client is running against an older server, #199 will break autofill on page load entirely. That's because `cipher.login.autofillOnPageLoad` will not exist on the server model, and it will be `undefined` instead of `null` when parsed by the client. I was using strict comparison to detect if the property was null (`cipher.login.autofillOnPageLoad === null`).
Although we don't really intend people to be running old servers, I thought this could save CS some tickets if self-hosted folks get their versions out of step. The new feature won't fully work, but it won't break the existing functionality either.
Use less strict equality checking, so that `null` and `undefined` are treated the same way.
Browser will need to be bumped.
> "Autofill on Page Load" options - minor tweak for backwards compatability

- src/angular/services/lock-guard.service.ts
Fix https://github.com/bitwarden/web/issues/978:
> After closing bitwarden tab, and reopening, you are not logged in as your account, but rather logged in as $1
This was introduced by the `lockGuardService`, which is meant to only allow navigation to the lock screen if the vault is locked. Thanks to @Hinton for picking this up.
The problem is that we were allowing navigation if `vaultTimeoutService.isLocked() == true`. However, that returns true if the user is logged out as well as if the vault is locked, so it was allowing a logged out user to access the lock page.
I've changed the order of the logic so that it should work as intended. This closely follows `unauthGuardService`.
`web` and `jslib` will need to be bumped. `browser` doesn't use this.
> Fix lockGuard logic

- src/abstractions/crypto.service.ts
- src/abstractions/policy.service.ts
- src/services/crypto.service.ts
- src/services/policy.service.ts
> Allow `Crypto` service to `rsaDecrypt` with a passed-in private key instead of inferring user's private key. Update/add a couple of helper methods to reduce redundant code during policy by token retrieval/parsing.
- **abstractions/crypto.service**: Updated method signature to pass in nullable private key value
- **abstractions/policy.service**: Update `getResetPasswordPolicyOptions` method signature to accept an `orgId` and return a tuple. Create `mapPoliciesFromToken` to take an api response and map the data to expected objects.
- **crypto.service**: Passed in private key will be used to decrypt unless its null -> will fallback to existing behavior and decrypt using the user's private key.
- **policy.service**: `getResetPasswordPolicyOptions` will now parse all policies for the user …
> [Reset Password] Update Crypto and Policy services

- src/abstractions/api.service.ts
- src/models/request/organizationUserBulkConfirmRequest.ts
- src/models/response/organizationUserBulkConfirmResponse.ts
- src/models/response/organizationUserBulkPublicKeyResponse.ts
- src/models/response/organizationUserBulkResponse.ts
- src/services/api.service.ts
Confirming multiple users is currently time consuming and involves multiple steps. This PR adds two new endpoints, one for retrieving the public key of multiple organization users, and another for confirming multiple users.
Related: https://github.com/bitwarden/server/pull/1345
> Bulk confirm

- src/cli/baseProgram.ts
Fix https://github.com/bitwarden/cli/issues/283:
> When using --response the exitcode should always be 0 when valid JSON is outputted, because the command was successful, even if the results being returned indicate a non-success.
We currently set the exit code according to the `response.success` value. For example, if the user tries to retrieve a folder with `bw get folder "my folder"` and the folder is not found, it will exit with an error code of 1 because `response.success === false`.
This PR adds a new option, `--cleanexit`, which will force the program to exit with a success error code (0) in this case.
* jslib: set exit code to `0` if `--cleanexit` is set. My understanding is that if there is an actual error thrown, it would have already bailed out by this point, so we won't be …
> Add support for --cleanexit option

- src/services/cipher.service.ts
Same objective as outlined in https://github.com/bitwarden/browser/pull/1857. However, that PR only changed the default selection for the drop-down, it did not actually change the logic if that setting has not yet been configured. Hopefully this is the last fix needed for this feature.
Bonus fix for indentation!
> [Autofill on Page Load options] Make logins autofill on page load by default

- src/importers/bitwardenJsonImporter.ts
- src/services/export.service.ts
I added a test `encString` to the top of encrypted exports in #369. This is an encrypted random GUID, which is decrypted first to test whether the `encKey` is valid (i.e. the same one used to export the data), before importing the data.
However, I didn't properly deal with organization imports & exports in #369, so this error checking is not working properly for organizations.
* export.service.ts: add the `encKeyValidation` value in organization exports
* bitwardenJsonImporter: pass in `orgKey` (if any) when decrypting the test string
> Add encKey validation for org import/export

- src/angular/components/add-edit.component.ts
- src/angular/components/view.component.ts
Bugfixes for the password reprompt discovered during QA.
- **src/angular/components/add-edit.component.ts**: Wrong event
- **src/angular/components/view.component.ts**: Reset `showCardNumber`, `showCardCode` and `passwordReprompted` fields when cleaning up. Add password prompt before downloading attachments.
> Password reprompt fixes

- src/models/request/tokenRequest.ts
- src/services/api.service.ts
Adds a new request header, `auth-email`, to auth requests that includes the same value as the `username` post parameter. This will enable us to rate limit auth requested based on username to prevent things like 2FA brute forcing.
> add auth-email header

- common/src/services/api.service.ts
Add a `Send-Id` header for Send access requests. This will allow for better rate limiting.
* apiService - add `Send-Id` header on Send access requests. This new parameter on `apiService.send` should also let other api calls implement similar functionality if required.
> Add Send-Id header for access requests

- angular/src/components/lock.component.ts
- common/src/abstractions/biometric.main.ts
- common/src/abstractions/crypto.service.ts
- common/src/abstractions/storage.service.ts
- common/src/abstractions/vaultTimeout.service.ts
- common/src/services/crypto.service.ts
- common/src/services/system.service.ts
- common/src/services/vaultTimeout.service.ts
- electron/src/biometric.darwin.main.ts
- electron/src/biometric.windows.main.ts
- electron/src/keytarStorageListener.ts
- electron/src/services/electronRendererSecureStorage.service.ts
- electron/src/services/electronRendererStorage.service.ts
- electron/src/services/electronStorage.service.ts
- node/src/services/lowdbStorage.service.ts
Split `secureStorage` key into multiple with separate keys (with the same value) to enable differential authentication of the keys.
Right now we have two use cases (1) Never unlock scenarios and (2) biometric unlock. 
This option stores a copy of the vault key, which is grabbed on start to unlock the vault. No password or biometric prompt should be shown.
This options stores a copy of the vault key, which should _always_ require biometric authentication in order to access.
These two options are split into keys stored under `Bitwarden_auto` and `Bitwarden_biometric`. 
In order to differentially authenticate securely stored secrets, storage needs the ability to receive context in stored item requests. `StorageService` methods now have `StorageServiceOptions` passed in which provide this …
> Authenticate with secure storage service

- angular/src/components/export.component.ts
- angular/src/components/lock.component.ts
- angular/src/components/set-password.component.ts
- common/src/abstractions/crypto.service.ts
- common/src/enums/hashPurpose.ts
- common/src/services/auth.service.ts
- common/src/services/crypto.service.ts
- common/src/services/passwordReprompt.service.ts
Use different iteration count for password hashing when it's for front-end authentication vs. server authentication. See rationale and approach here: https://app.asana.com/0/1169444489336079/1200436665343464/f
> Use 2 iterations for local password hashing

- common/src/abstractions/crypto.service.ts
- common/src/services/crypto.service.ts
@Hinton noticed some issues with biometric unlock from browser introduced in #402 and bitwarden/desktop#946.
Namely, the normal `getKey` method was being used, which will use a key stored in memory, if available, and set the key to memory if not. We don't want that behavior for biometric unlock -- it should _always_ prompt.
This requires a new method, `getKeyFromStorage`, which always retrieves the requested key from secure storage.
* **crypto.service**: Add new `getKeyFromStorage` method to abstraction and implementation. `getKey` uses this method to retrieve from storage.
> Add get key from storage for ensuring biometric browser integration

- angular/src/components/export.component.ts
- angular/src/components/lock.component.ts
- common/src/abstractions/crypto.service.ts
- common/src/services/crypto.service.ts
- common/src/services/passwordReprompt.service.ts
Follow up work from #404. Changing the local password hashing method would have stopped users from unlocking after the update (at least until they logged out and back in again). This checks to see whether they're using an outdated hash and updates it gracefully.
> Add backwards compatability for new local hashing method

- angular/src/components/share.component.ts
The term "Share" is confusing to users because it implies maintaining ownership and control of a cipher while allowing others to access it as well. It also implies the ability to revoke access or to stop sharing -- neither of these things is true.
When a cipher is "shared" it is irrevocably taken over by an organization. This occurs for good cryptographic and security reasons. The better solution to this is to revise the communication around "sharing." To that end, this work changes the term "share" to "move to organization." 
Most of these changes will occur in specific clients. PRs will reference this one.
* **share.component.ts**: Renamed translation item and added cipher and org names
> Add org name to moved to org success toast

- angular/src/components/lock.component.ts
- common/src/abstractions/vaultTimeout.service.ts
- common/src/services/vaultTimeout.service.ts
Vault should be locked if key is not in memory. Key is loaded on startup if auto key exists.
> Note: This PR will be cherry-picked to `rc` as well as propagated to all jslib clients (and cherry-picked there) prior to the upcoming release. Please evaluate accordingly.
* **vaultTimeoutService**: 
* `biometricLocked was overriding never lock in situations where never lock, biometric unlock, and do not prompt biometric on start were set. 
* The new `hasKeyInMemory` method can be used to reliably detect when the vault is locked -- the key shouldn't be in memory in a locked vault. There is also logic to handle startup conditions with "Never lock" set.
* The above changes make `manuallyOrTimerLocked` obsolete.
* **other**: remove references to `manuallyOrTimerLocked`
> Simplify `isLocked` and fix interaction between Never lock and no prompt biometr

- common/src/abstractions/apiKey.service.ts
- common/src/services/api.service.ts
- common/src/services/apiKey.service.ts
Linked to bitwarden/directory-connector#135
#382 and bitwarden/directory-connector#121 switched authentication to organization API key flow. However, this authentication does not include refresh tokens.
This is groundwork for persisting api key credentials and overriding token refresh with simply re-authenticating with api key creds.
> Note: This PR will need to be cherry-picked into `rc` and subsequently into the clients. Please evaluate accordingly
* **apiKey.service.ts**: Persist and retrieve api key credentials
* **api.service.ts**: Update `doRefreshToken` private method to return nothing, and allow for inherited override. Return signature change is due to auth flow not receiving an `IdentityResponse` from the `apiService`. At any rate, we were only interested in grabbing the new …
> Persist API key creds for token refresh.

- common/src/services/crypto.service.ts
Correct typo. This bug causes keys to never be deleted in CLI.
> Note: this will be cherry-picked into `rc` and pushed to at least CLI prior to next release. Please evaluate accordingly
> Correct typo

- angular/src/components/password-generator.component.ts
**Feature name:**
```
Replace the drop down for password/passphrase option with a radio button choice
```
**Feature Description**
There are only two options in the drop down, would it be better to replace it with a radio button for choice?
-  Aids in discoverability: I completely missed the option for a whole year before I thought to click on the option and see what it contains.
- Less number of interactions: It would take 1 less click to get the same result
Community Forum post: https://community.bitwarden.com/t/radio-choice-password-passphrase/30636
> feat: radio button options

- common/src/models/view/cipherView.ts
Some users reported that every item prompts for reprompt. I managed to replicate it by disabling sync, and setting each cipher to have `reprompt = null`. As a fix I've added a null check to `CipherView` which seems to solve it for me.
(A sync also solved it for me)
> Set reprompt to None if null

- CONTRIBUTING.md
jslib is a common pain point for community contributions. I've updated CONTRIBUTING.md to include:
* brief explanation and resources for understanding git submodules
* common git workflows when working on jslib changes
This way, we can just provide a link to this document, rather than having to re-explain it for each new contributor.
> Expand CONTRIBUTING.md to include submodule info and workflows

- angular/src/pipes/user-name.pipe.ts
Helper to avoid using `user.name || user.email` since we used a few different approaches in the applications. This ensures the names are displayed consistently.
> Add UserNamePipe

- angular/src/components/send/add-edit.component.ts
- angular/src/components/send/efflux-dates.component.ts
> Address a regression bug detailed in [Asana](https://app.asana.com/0/1183359552741420/1200508847900795/f) in a way that keeps the feature from regressing in the future and makes the code somewhat easier to live with.
* Split the `deletionDate` and `expirationDate` inputs for Sends into a separate component - `efflux-dates.component`
* Refactored the backing logic for the `efflux-dates` component to use Reactive Forms and to consolidate a lot of code that was poorly written (It was mine I can say that). These changes address the bug in the attached ticket, cut down on lines of code, improve type safety and readability, and consolidate logic that previously was split based on which browser is being used whenever possible.
https://github.com/bitwarden/web/pull/1084 …
> Resolved Safari Date/Time Issues In Send

- angular/src/directives/api-action.directive.ts
`api-action.directive` does not display error messages on `captchaProtected` api endpoints requesting captcha verification. In the [browser](https://gitbhub.com/bitwarden/browser) project, the type of captcha-required responses was not being identified correctly. Adding a test to the constructor name as a fallback method.
> Use both instanceof and constructor name as type identification

- common/src/services/notifications.service.ts
- common/src/services/sync.service.ts
Sometimes the `sync` response can be out of date with the identity token and contain organizations or providers which the user can't access yet. To resolve this I added a call to `refreshToken` while doing a full sync.
Note: I'm not certain if this will have side effects but from what I've managed to understand we usually refresh it every 5 min, so I don't see any harm in doing it more often sometimes.
We should do some regression testing to verify the identity token can successfully be retrieved in all of our clients.
https://app.asana.com/0/1198901840263430/1200639990863109
> [Provider] Refresh identity token on full sync

- angular/package.json
While setting up my dev-environment I encountered an issue with 'duo_web_sdk' not resolving when running 'npm i' on for example the desktop or browser repo. This occurs spefically on the following component: `angular/src/components/two-factor.component.ts`
This happens because the `jslib/angular`-package does not include a dependency for `duo_web_sdk`.
The error should've been caught earlier through our Github Build Action, but as nothing in `jslib` (common, spec, etc.) depends on `jslib/angular` it doesn't get built (no output in `/dist`)
The behaviour has also been reported in #440.
For our other repo this is usually not an issue as `duo_web_sdk` is included as a dependency on the web, browser and desktop projects, but actually not necessary to include it on a higher level project. …
> Add missing dependency 'duo_web_sdk' in jslib/angular/package.json

- common/src/abstractions/api.service.ts
- common/src/services/api.service.ts
The return type of the api call to create a provider organization is incorrect (https://github.com/bitwarden/server/blob/master/src/Api/Controllers/ProviderOrganizationsController.cs#L65).
This fix is part of the fix for https://app.asana.com/0/0/1200645727236036/f. Web PR is bitwarden/web#1101
* **api.service**: Change return type
> Correct ProviderOrgCreate return type

- angular/package-lock.json
Hi Bitwarden team!
I think recently @djsmith85 updated the `package.json` for jslib angular package (for #440), however it seems like `package-lock.json` wasn't updated.
I think it's best to save the integrity checks in the package-lock for such a crucial dependency. Please see diff.
(I double checked the checksum with `sha512sum duo_web_sdk-2.7.1.tgz | cut -f1 -d' ' | xxd -r -p | base64`)
> Update package lock for duo_web_sdk in angular

- angular/src/components/set-password.component.ts
- angular/src/components/update-temp-password.component.ts
- common/src/abstractions/api.service.ts
- common/src/abstractions/user.service.ts
- common/src/enums/eventType.ts
- common/src/models/request/updateTempPasswordRequest.ts
- common/src/models/response/profileResponse.ts
- common/src/services/api.service.ts
- common/src/services/sync.service.ts
- common/src/services/user.service.ts
> Allow angular clients to force a password update after an admin resets a user's master password.
- **update-temp-password.component.ts**: Created shared component for angular clients that will be able to update a user's temporary password set by an admin. Extends `ChangePasswordComponent` and overrides necessary methods.
- **abstractions/api.service.ts**: Added `putUpdateTempPassword` method signature
- **abstractions/user.service.ts**: Added `getter` and `setter` for `forcePasswordReset` boolean
- **eventType**: Added `User_UpdatedTempPassword` to handle events on the `web` client
- **updateTempPasswordRequest.ts**: Created request object that models the server model
- **profileResponse.ts**: Added `forcePasswordReset` boolean
- **api.service.ts**: Added `putUpdateTempPassword` method …
> [Reset Password v1] Update Temp Password

- common/src/misc/utils.ts
- common/src/models/request/tokenRequest.ts
Client implementation of https://github.com/bitwarden/server/pull/1503.
All Angular clients will need `jslib` bumped after merging.
> Use UrlB64 encoding for auth-email header

- angular/src/components/ciphers.component.ts
Bugfix from this refactor: https://github.com/bitwarden/jslib/pull/436
I had moved some existing code to a new method, `doSearch`. The original code was awaited, but I didn't await the calls to the new method. This means that `this.loaded` is set to `true` before loading is actually finished, and the user gets a "vault empty" sad face for a few seconds, even when they have items.
> Fix cipher loading (missing await)

- angular/src/components/ciphers.component.ts
I refactored the base `ciphers.component.ts` in #436, but was too aggressive in taking stuff out.
The `refresh` method is used by all clients, so I've added it back into `jslib`.
> Fix missing refresh method in ciphers.component

- angular/src/components/login.component.ts
Fixes https://app.asana.com/0/0/1200768603643030/f.
This delay is necessary to make sure the location we're submitting the form to is the same as the webvault captcha iframe location.
This will be cherry picked to `rc` and all jslib clients will be updated to include these changes
> Set up captcha iframe only on submit of login

- angular/src/components/two-factor.component.ts
- common/src/misc/webauthn_iframe.ts
Fixes: https://app.asana.com/0/0/1200719554428331/f
Chrome has begun refusing to load our webauthn iframe in browser. This appears to be due to either a race condition or an intentional block to adding an `allow` attribute to the iframe in javascript.
This PR provides a getter to provide the necessary allow directive to the `html` template.
* **two-factor.ts**: Provide the necessary allow statement for webauthn
* **webauthn_iframe.ts**: only set allow if it's not already present.
I believe this requires no upgrade considerations. The `webauthn_iframe` component should be run on the client making the iframe and appending the `allow` attribute. This flow is complicated, though, so a second brain to validate, would be good.
> Provide information to set webauthn allow in html template

- common/src/abstractions/token.service.ts
- common/src/services/api.service.ts
- common/src/services/auth.service.ts
- common/src/services/token.service.ts
- node/src/services/nodeApi.service.ts
API Key-based authentication does not return a refresh token. Because of this, even after unlocking, it is not possible to work with your vault as syncing requires a refresh. Even if it didn't, auth tokens have a limited lifetime and should be valid until `bw logout` is called.
The fix is to generalize refresh to mean either refreshing via refresh token (the current method) OR refreshing via stored api key credentials (this PR).
* **TokenService**: Add `clientId` and `clientSecret` to tokens being handled by the service. Treat them in the same way as `accessToken` and `refreshToken`.
* **api.service**: update referesh endpoint to `doAuthRefresh`, which determines the refresh method based on tokens stored in `tokenService`. Prefers refresh flow, but falls back to api-key based …
> Generalize token refreshing to include reauth by api key

- node/src/cli/commands/login.command.ts
@fschillingeriv has put together a help article specifically for CLI logins that require extra authentication due to captcha (bitwarden/help#706). Update the error returned on failed captcha challenge to direct users to that site.
> Note: I'd like to cherry pick this into `rc` for the upcoming release. I believe the impact to be quite small. It would require a push to CLI `rc` as well to incorporate the changes.
> Update help url

- common/src/services/i18n.service.ts
For the AZ language that was added I while back by Trey, we where missing a translation for the language selection dropdown in the web client.
So I added it.
> Add missing locale entry for AZ language

- angular/src/components/send/efflux-dates.component.ts
Resolves https://app.asana.com/0/1183359552741420/1200821052763382/f
> New Safari Sends that select a custom expiration date are not being required to provide input for the date and time
Despite being a required field under these conditions, it does not look like Expiration Date is being required in the safari extension when creating a Send with a custom expiration date. I am unsure if the required attribute not functioning is a Safari thing or an issue with the polyfill we use, but here is some proof that the dang thing is required. This is not happening in web, and the field is being flagged as required. 
That said, I figured the best way to address this would be to force an error if either field is null on submit and wasn't caught before that by normal means. I achieved this by simply …
> Send Expiration Date Fix For Browser

- common/src/misc/webauthn_iframe.ts
Self-hosted users have trouble using WebAuthN with the latest clients, due to the clients expecting a newer connector protocol. Until we are confident self-hosted users have updated their servers we should revert the changes.
Note: This will be cherry picked to `rc`.
> Revert WebAuthn iFrame handler

- common/src/models/response/profileResponse.ts
- electron/src/services/electronStorage.service.ts
Fix https://github.com/bitwarden/desktop/issues/1033. The latest desktop release cannot sync with older self-hosted servers. 
This is because the client is expecting a `ForcePasswordReset` property on the http sync response. Because that property doesn't exist and no other default value is provided, the client passes an `undefined` value to `electronStorageService`, which then throws an error when it tries to save.
In my brief testing, other Angular clients do not appear to be affected by this bug, so I assume they tolerate saving `null` or `undefined` values. Therefore, I've added a null check to `electronStorageService` to bring it into line with other storage services.
I've also added a default value, because we really should be doing that either way.
**Note:** this will need to be …
> Add null check to electronStorageService.Save

- angular/src/components/icon.component.ts
Virtual-scroll reuses components, which causes the icon component to have a weird state, where `image` is set for non login items. To avoid this, I reset the state variables on change detection.
Note: This will be cherry picked to `rc` and into `desktop`.
> Ensure icon component state is reset

- angular/src/components/callout.component.html
- angular/src/components/callout.component.ts
- angular/src/components/change-password.component.ts
> Update the `App Callout` object to handle the `Master Password Policy` policy option. This will allow us to reduce repeated code for getting the display text.
- **callout.component.html**: Added UI elements for the `enforcedPolicyOptions`. 
- **callout.component.ts**: Added input options for the policy options and message. Set default message and added `getPasswordScoreAlertDisplay` method to reduce copy+pasta code.
- **change-password.component.ts**: Removed `getPasswordScoreAlertDisplay` method.
> [Callout] Added Enforced Policy Options UI

- electron/src/services/electronStorage.service.ts
In the latest hotfix version (1.28.1), users are unable to set the vault timeout to "Never". It always reverts to the last saved option.
#461 solved a syncing error by:
1. providing a default value for a potentially `undefined` property
2. adding a `null` check so that we don't try to save `undefined` values in the future.
However, there are cases where we do want to save `null` to storage - in particular, the "Never" vault timeout option has a value of `null`. The original syncing error was actually thrown by saving an `undefined` value, not `null`, so the check should've been `obj === undefined`.
However, with the benefit of hindsight, I think:
* in hotfixes, we should only make the minimum changes required to solve the issue. The syncing error was solved by change 1. Change 2 was aimed …
> Remove null check in ElectronStorageService.Save

- angular/src/components/add-edit.component.ts
- angular/src/components/send/add-edit.component.ts
- angular/src/components/send/send.component.ts
- common/src/abstractions/policy.service.ts
- common/src/models/domain/organization.ts
- common/src/services/policy.service.ts
We have lots of duplicate logic when we check whether a policy applies to a user. Here's a typical example:
```typescript
const disableSendPolicies = await this.policyService.getAll(PolicyType.DisableSend);
const organizations = await this.userService.getAllOrganizations();
this.disableSend = organizations.some(o => {
return o.enabled &&
o.status === OrganizationUserStatusType.Confirmed &&
o.usePolicies &&
!o.canManagePolicies &&
disableSendPolicies.some(p => p.organizationId === o.id && p.enabled);
});
```
This is repeated throughout various components. It's a good candidate to standardize and lift up into `policyService`.
* policyService - 
* add `PolicyAppliesToUser` method. This finds whether a given `policyType` (from any organization) applies to a user.
* note: `PolicyAppliesToUser` …
> Move policy checks within policyService

- angular/src/components/modal/dynamic-modal.component.ts
- angular/src/services/modal.service.ts
Lazy loaded modules are not available in the `ComponentFactoryResolver` initialized by `DynamicModalComponent`. Therefore we need a way to register component factory resolvers for the `ModalService`.
> Add support for setting up component factory resolvers in modal service

- angular/src/directives/api-action.directive.ts
`api-action.directive` is generally used to wrap all of our api calls and handle element loading indicators / errors. Adding logging here will improve debugging efforts by providing a more permanent history of api errors and potentially recording more information than the user-friendly message.
> Log full error for better debugging support

- angular/src/components/two-factor.component.ts
Fix the following error, which occurs whenever you load the 2FA screen on Desktop:
This is because we call `queryParamsSub.unsubscribe()` from within the `subscribe()` callback. I'm not sure why this doesn't work - we use this pattern elsewhere and it works fine, it just throws this error in this specific component. 
* `two-factor.component.ts` - use the rxjs `first` operator to get the first emitted value. This makes unsubscribing unnecessary and (in my opinion) is the better pattern to use here.
The original pattern appears in other components but they're not causing any trouble, so I haven't changed them at this stage.
> Fix 'Cannot access variable before initialization' error in Desktop

- angular/src/components/set-password.component.ts
- common/src/abstractions/user.service.ts
- common/src/models/request/setPasswordRequest.ts
- common/src/services/user.service.ts
> Fix the following issue: Non-invited users who are created JIT are not being auto-enrolled into the organization's reset password functionality.
- **set-password.component.ts**: Added new conditional that checks whether or not the user needs to be auto-enrolled in reset password.
- **user.service.ts**: Added new method that will retrieve an organization via `identifier`
> [SSO] Set password auto enroll update

- common/src/models/domain/organization.ts
- common/src/services/policy.service.ts
Tweak some of the changes I made in https://github.com/bitwarden/jslib/pull/466.
This PR has 2 minor follow-up fixes:
1. Include providerUsers as "owners" of an org (this reflects the server-side logic discussed [here](https://github.com/bitwarden/server/pull/1536#issuecomment-910471316))
2. In `policyService.policyAppliesToUser`:
* Remove the redundant `policyType` filter - this is already done in the call to `this.GetAll`
* Refactor so that we're not using a passthrough function for `policyFilter` - that would still involve checking that `true == true` for every policy, when we could just skip it altogether.
> Fixes and cleanup for policyAppliesToUser

- angular/src/components/set-pin.component.ts
Fix https://github.com/bitwarden/browser/issues/887:
> The PIN input screen is insecure in the sense that you can read what you input into it.
* Create a new component for the "set pin" modal
The other changes are in the clients themselves.
* desktop: https://github.com/bitwarden/desktop/pull/1064
* browser: https://github.com/bitwarden/browser/pull/2060
> Use a modal to set the unlock pin

- angular/src/components/set-password.component.ts
- common/src/abstractions/api.service.ts
- common/src/models/response/organizationAutoEnrollStatusResponse.ts
- common/src/services/api.service.ts
> Add the latest `Auto Enroll` status `API` and updated the flow for information retrieval in regards to the `Organization ID` and `AutoEnrollEnabled` boolean.
- **set-password.component**: Update the flow to use the newly available `API`
- **api.service**: Added new `GetOrganizationAutoEnrollStatus` method
- **organizationAutoEnrollStatusResponse**: Added response object for newly created `API`
- [Server - Add Auto Enroll status API](https://github.com/bitwarden/server/pull/1583)
- Will be merged into `master` and `rc`
> [SSO Auto Enroll] Auto Enroll status retrieval

- angular/src/components/login.component.ts
- angular/src/components/sso.component.ts
- angular/src/components/two-factor.component.ts
- common/src/models/domain/authResult.ts
- common/src/models/response/identityTokenResponse.ts
- common/src/services/auth.service.ts
> Refactor the Force Password Reset flow to lift dependency on full sync in downstream clients
- **login.component**: Added conditional/options for navigation when forcing a password reset is necessary
- **sso.component**:  Added conditional/options for navigation when forcing a password reset is necessary
- **two-factor.component**: Added conditional for when forcing a password reset is necessary
- **authResult**: Added `forcePasswordReset` boolean
- **identityTokenResponse**: Added `forcePasswordReset` boolean
- **auth.service**: Added `forcePasswordReset` to the `AuthResult` response object
> [Reset Password v1] Refactor ForcePasswordReset into AuthResult

- angular/src/components/add-edit-custom-fields.component.ts
- angular/src/components/add-edit.component.ts
- angular/src/components/view-custom-fields.component.ts
- angular/src/components/view.component.ts
@MGibson1 suggested in https://github.com/bitwarden/browser/pull/1963 that we move custom fields out of the `add-edit.component.ts` and into their own component. This tidies up `add-edit.component`, which already has a lot going on, and will also make the linked custom fields implementation cleaner. I'll rebase bitwarden/browser#1963 on top of this once merged.
There's less logic in `view.component.ts`, but I've split that out as well for consistency.
Note: this is a pure refactor, there are no changes to logic or behaviour in this PR.
* move relevant code and html from `add-edit.component` to new `add-edit-custom-field.component`
* move relevant code and html from `view.component` to new `view-custom-field.component`
Client changes:
* browser: …
> Move custom fields to separate components

- electron/package-lock.json
- electron/package.json
- electron/src/window.main.ts
Upgrade Electron to use 14.0.1.
I also removed `webviewtag` since it doesn't seem that we are using it for anything.
We'll need to do a regression sweep to verify nothing broke.
> Bump Electron to v14

- angular/src/components/lock.component.ts
In the browser extension, primarily on Safari the error message for biometrics sometimes disappears before it can be read. To resolve this, I needed to only close the dialog if the action was successful, which requires to know the status of the unlock operation.
> Resolve biometric error dissapearing before being read

- angular/src/components/add-edit-custom-fields.component.ts
When creating a new cipher, if you add a linked field and then change the cipher type, it will update the dropdown options but not the `Field.linkedId` value. This can leave you with a `linkedId` that belongs to a different cipher type.
* **angular/src/components/add-edit-custom-fields.component.ts**: if we're adding a new cipher, and the cipher type changes, reset all `linkedId` values to make sure they align with the new cipher type. (This will also fire once on page load, but if we're adding a new cipher then there won't be any existing fields to overwrite.)
NA, will be tested as part of linked custom fields.
> [Linked fields] Reset linkedIds if cipher type changes

- angular/src/components/add-edit-custom-fields.component.ts
Bug fix for #431. When editing a cipher in the web vault, any linked field values would be reset to whatever the first dropdown option is.
We do want to reset these values if the user is adding a new cipher and they change the cipher type. However, the test for "adding a new cipher" was `(!editMode)`, which is passed in from the parent component. `editMode` is briefly `undefined` before the real value is received, which meant it always met this condition. I also realised that `editMode` defaults to `false` in the parent before it correctly sets the value, which could also be a problem.
* **angular/src/components/add-edit-custom-fields.component.ts**:
* separate out (1) resetting the `linkedFieldOptions` dropdown list and (2) resetting the cipher's linked field values.
* only reset the …
> [Linked fields] Fix change detection on cipherType

- common/src/misc/utils.ts
The WebExtensions password storage logic is fully relying on the top URL currently loaded. To ensure that the domain is correctly parsed, as it is used to retrieve the stored credentials, certain checks are deployed. It was discovered that currently a block list approach is implemented for protocols, which only contains the data: protocol handler. This could introduce security issues eg. via the about:blank page or similar pseudo protocols added to browsers.
As an example, the Safari web browsers allows to add arbitrary characters to the about:blank URL. In the end this behavior was not exploitable as this page origin can not be accessed by another page and therefore no iframe can be injected, which would have allowed to leak the credentials of any stored domain.
Added logic to prevent …
> don't allow @ character in uriString prefixing

- common/src/services/api.service.ts
It was discovered that user controlled path variables are not validated before they are utilized to construct a HTTP URL. By traversing the path up, it is possible to reach arbitrary API endpoints.
The impact of this issue was reduced as most paths immediately display the vault's lock page and it was not possible to abuse this behavior further.
Updated the `send()` function in the API service to clean the request path from any directory traversal strings (`../`) before constructing the final url to call.
General regression to ensure no API calls are broken.
> clean api url paths from directory traversal

- common/src/services/api.service.ts
It was discovered that user controlled path variables are not validated before they are utilized to construct a HTTP URL. By traversing the path up, it is possible to reach arbitrary API endpoints.
The impact of this issue was reduced as most paths immediately display the vault's lock page and it was not possible to abuse this behavior further.
Added a check in the generically used `send()` function to ensure paths have not been manipulated. We can do this by constructing a `new URL()` and comparing the `href` property to what was originally expected.
General regression to ensure no API calls are broken.
> validate path for directory traversal

- common/src/services/import.service.ts
macOS Monterey added an export option from System Preferences > Passwords, which uses the same format as exporting from Safari (which we already support). I've updated the name of the importer from "Safari" to "Safari and macOS", so that users know it supports both.
* **common/src/services/import.service.ts** - 
* update name as described above
* put the featured importers (at the top of the dropdown) in alphabetical order. The exception to this is 1Password, that should be at the top (numbers come before letters), but I assume we want Bitwarden as the first option, so I've left it at the bottom. I still think it looks more orderly than before.
Web will need to update jslib after this is merged.
QA can test to confirm that the importer also works for macOS exports. Otherwise this is just …
> Update Safari importer to be Safari and macOS importer

- angular/src/components/verify-master-password.component.ts
- common/src/abstractions/userVerification.service.ts
- common/src/models/response/identityTokenResponse.ts
- common/src/services/auth.service.ts
- common/src/services/keyConnector.service.ts
- common/src/services/userVerification.service.ts
Fix QA feedback on Key Connector:
* Fix no error in desktop when OTP/MP is blank: https://app.asana.com/0/0/1201361837847153/f
* Support CLI changes: https://github.com/bitwarden/cli/pull/410
* **common/src/services/userVerification.service.ts** - 
* add wrapper for requesting OTP code, it just made sense to have it in this service as the main interface
* provide CLI support, which I forgot the first time round:
* break out error handling into its own `protected` method. This lets us override it in CLI, which doesn't use toasts.
* remove `@Injectable` Angular decorator, which doesn't belong in `jslib-common`. Angular clients will need their `services.module.ts` updated.
* add proper error handling if the secret is null or an empty string (tell the user, don't just throw an error)
* remove …
> [Key Connector] QA fixes for CLI and Desktop

- angular/src/components/export.component.ts
- angular/src/components/verify-master-password.component.ts
- common/src/enums/eventType.ts
Follow up to https://github.com/bitwarden/jslib/pull/544, where we decided to throw errors from `UserVerificationService` and catch them in the components if required. We need to update the base `export.component.ts` to use this new pattern.
In the course of testing, I also noticed the following error, which this PR fixes:
* use Key Connector
* submit a form that contains `VerifyMasterPasswordComponent` but leave the OTP blank
* expected: "Verification code required" error message
* actual: "Master Password required" error message
* **angular/src/components/export.component.ts** - add try/catch block
* **angular/src/components/verify-master-password.component.ts** - call `onChanges` with an initial value when the component loads. This is so that `verification.type` is correctly set and …
> Update base export component for userVerificationService changes

- angular/src/components/set-pin.component.ts
If the user is using Key Connector and sets an unlock pin, do not ask them whether they want to "require unlocking with master password when the application is restarted". Instead, hide this checkbox and default it to false because they do not have a master password.
> [Key Connector] Hide "Master Pass On Restart" prompt when setting pin

- common/src/services/sync.service.ts
Resolves an issue where the desktop application didn't correctly prompt to remove password after first unlock with key connector.
The issue was caused by the check running before the organizations were replaced which meant the `requiredByOrganization` check in `userNeedsMigration` always returned false until the next sync. On other clients this operation is a race condition that to my knowledge always runs correctly.
> [Key Connector] Resolve desktop not prompting to remove password

- angular/src/components/add-edit.component.ts
While editing or having a vault item open, if you clicked on a filter item in the navigation pane on the left the ownership options of your open item would duplicate.
This was happening because `ngOnChanges` was called when you selected a filter item, which made a call to `super.init()`.
This change resets the `ownershipOptions` array on every init in jslib.
* **angular/src/components/add-edit.component.ts:** Reset `ownershipOptions` on init
- Test add/edit item while clicking on filter items
- Light testing around add/edit item functionality, specifically ownership options
> Desktop displays duplicate ownership attributes 

- common/src/importers/fsecureFskImporter.ts
- spec/common/importers/fsecureFskImporter.spec.ts
Originally created this PR https://github.com/bitwarden/jslib/pull/303 but the structure of jslib has changed since then. Seemed easier to just create a new PR for it.
Closes bitwarden/web#756
Checks the style-property of a fsk-file and now supports 'website' and 'globe'
Asana task: https://app.asana.com/0/1169444489336079/1199370041222794/f
* **common\src\importers\fsecureFskImporter.ts:** Added support for parsing entries with the style set to global.
* **spec\common\importers\fsecureFskImporter.spec.ts:** Unit tests for parsing entries with style set to `website` and `global`
Should be able to import a FSecure file with the styles (website and global)
> FSescure-Importer: Add support for style = global

- electron/package-lock.json
- electron/package.json
- package-lock.json
To stay up-to-date with electron release schedule, bumping electron dependencies
Asana-task: https://app.asana.com/0/1200804338582616/1201506018477649/f
* **electron/package.json:** Updated `electron` to `16.0.2` and `electron-updater` to `4.6.1`
* **electron/package-lock.json:** Changes after running `npm i` in /electron/
* **package-lock.json:** Changes after running `npm i` in /
No testing necessary, testing will be done in the desktop client and directory-connector
> Bump electron to 16

- common/src/services/state.service.ts
Organizations are being stored in memory but we need that information to persist in session
* Changed the storage location of organizations
> [bug] Correct storage location of organizations

- angular/src/components/change-password.component.ts
- angular/src/components/set-password.component.ts
- common/src/abstractions/api.service.ts
- common/src/abstractions/policy.service.ts
- common/src/services/api.service.ts
- common/src/services/policy.service.ts
Asana Task: https://app.asana.com/0/1169444489336079/1201499725597872/f
Dependency: https://github.com/bitwarden/server/pull/1779
Users currently don't have their master password checked against the organization policy while registering via SSO. This fix checks if the user is registering a new account, and if so pulls org policies from the endpoint created in the server dependency.
**Will be cherry picked to rc**
- **angular/src/components/change-password.component.ts:** Fill policies if user is not registering for first time
- **angular/src/components/set-password.component.ts:** If identifier is set (registering), fill policies using userId and orgId
- **common/src/services/policy.service.ts:** Add method for finding policies if userId is an invited user to organization
- …
> Use MP policies when registering a new user through SSO

- common/src/enums/stateVersion.ts
- common/src/models/domain/account.ts
- common/src/models/domain/globalState.ts
- common/src/services/state.service.ts
- common/src/services/stateMigration.service.ts
- [Asana Task](https://app.asana.com/0/inbox/1183359552741416/1201592404236978/1201607436480545)
- https://github.com/bitwarden/web/pull/1365
The storage engine refactor created a bug where dropdown setting values are not defaulting appropriately, most noticeable on web where a vault timeout of "never" should only be allowed for dev, but instead was being applied as a default for all environments. This is addressed in two parts: a jslib PR that sets defaults for locale, theme, and timeout action (as those are the same on each client) and a web PR that extends the account model and sets an appropriate default for vault timeout duration based on environment. 
I fixed one other thing while in the area: simply removing a call to set InMemory state while loading state from disk. This simply …
> [bug] Add several state value defaults

- angular/src/components/export.component.ts
- angular/src/components/settings/vault-timeout-input.component.ts
Rename all occurrences of fb to formBuilder as it can be confusing.
There were a lot less files to fix than I thought. The only two were:
- **angular/src/components/export.component.ts**
- **angular/src/components/settings/vault-timeout-input.component.ts**
No functionality changes, just make sure the Export Vault form and Custom Vault Timeout forms behave as expected.
> Rename all occurrences of fb to formBuilder

- common/src/abstractions/state.service.ts
- common/src/models/domain/environmentUrls.ts
- common/src/services/state.service.ts
https://app.asana.com/0/inbox/1183359552741416/1201638560333663/1201628380941783
To allow for setting environmentUrls before an account is created we save that value as a global setting and then apply it to any newly authed accounts.
There is a bug that will instead save the urls used by the previous logged in account, making account switching with multiple servers cause errors. This PR addresses this.
See commits and descriptions
> [Bug] [Account Switching] Ensure EnvironmentUrls Pull From The Correction Location On Account Add

- common/src/services/state.service.ts
Fix for some dropdowns defaulting to empty.
Fixes: https://app.asana.com/0/1153292148278596/1201632897395074/f
The reason this is an issue is because the values are coming back as undefined in state service. Angular is doing a strict check to determine the selected option, so the value of null isn't mapping as expected. 
We could also approach this by changing the the default options in the components to be selected when they are null or undefined, but I observed this as an issue in Browser as well and doing it this way fixes it there too without having to manually update the select options in the components there as well. I waffled on which was the better approach, so I went with this way as it fixes it from the deepest level and will fix it for Browser when jslib is updated :) 
- …
> [Account Switching] Fix options dropdowns being empty

- common/src/services/vaultTimeout.service.ts
The client side storage restructuring work incorrectly checks if a vault has ever been unlocked to determine neverLock scenarios, but production does the opposite.
This creates an inability to never manually lock neverLock vaults.
This commit sets that condition back to the way it was.
> [bug] Ensure neverLock vaults can be manually locked

- node/src/services/lowdbStorage.service.ts
Clients that use `lowdbStorageService` (CLI and bwdc CLI) need that service initialized before it can be used.
#600 added a subscription to the `environmentService` constructor, which indirectly calls `storageService` before it's initialized, resulting in the following error:
```
/snapshot/directory-connector/build-cli/bwdc.js:1513
this.db.read();
^
TypeError: Cannot read properties of undefined (reading 'read')
```
I encountered this when trying to bump jslib in https://github.com/bitwarden/directory-connector/pull/204.
No other clients need to initialize their storage services, so this is unique to `lowdbStorageService`.
One solution would be to move the subscription out of the `environmentService` constructor and into its own `init` method. However, that would require every client to …
> Make lowdbStorageService wait until initialised

- angular/tsconfig.json
- common/tsconfig.json
- electron/tsconfig.json
- node/tsconfig.json
- shared/tsconfig.json
Our `tsconfig` files are pretty much identical across our projects. If we ever change any setting it's going to require a fair bit of work to
> Add a shared tsconfig file

- electron/package-lock.json
- electron/package.json
- package-lock.json
Bumping electron from 16.0.2 to 16.0.7
- **electron/package.json:** Updated electron to 16.0.7
- **electron/package-lock.json:** Changes after executing `npm i`
- **package-lock.json:** Changes after executing `npm i`
Regression testing on clients
> Bump electron from 16.0.2 to 16.0.7

- common/src/services/stateMigration.service.ts
Fix the following defect in CLI: 
1. run a pre-account switching version of CLI
2. set your environment urls using `bw config server`
3. log out
4. upgrade CLI and try to log in
Expected result: saved urls are migrated
Actual result: saved urls are lost and it defaults to production servers
* `stateMigrationService.ts` - always migrate the environment urls to `global` settings, regardless of whether the user is logged in (which I believe is what the `userId` storage key indicates). This seems like a reasonable course of action for all clients.
Incidentally, it appears that the environment urls are copied to the user's settings when the migration runs, but after that point they're only read from and written to the global settings. This seems like it could cause problems down the line …
> Always migrate envUrls to new storage format

- angular/src/services/jslib-services.module.ts
- common/src/models/domain/account.ts
- common/src/models/domain/globalState.ts
- common/src/models/domain/state.ts
- common/src/services/state.service.ts
- common/src/services/stateMigration.service.ts
Large vaults see a clear degrade in performance using the state service, especially when multiple vaults are authed and unlocked at the same time.
Some changes made to address this:
1. Clearing in memory decrypted data for non active accounts. This really should have been something we were doing anyway, but letting go of that memory burden has a noticeable performance boost.
2. Not loading a bunch of unnecessary data from disk accounts into memory on application startup. This was being done to initialize in memory accounts, but brought a lot of extra baggage with it like storing encrypted data in memory, even though it is never referenced that way.
3. Breaking the on disk state object up into separate keys for accounts instead of storing everything together under a "state" key. This …
> [Bug] [Account Switching] Improve State Management Performance

- common/src/services/keyConnector.service.ts
- common/src/services/sync.service.ts
- node/src/cli/commands/login.command.ts
See https://github.com/bitwarden/cli/pull/452.
- **common/src/services/sync.service.ts** - set the KC conversion flag in sync service. This is done by all clients anyway, but needs to be done here for cli because it doesn't have a messaging service. I'll go through and remove the duplicate logic in each client after merging.
- **node/src/cli/commands/login.command.ts** - remove KC conversion check and syncing.
Other minor fixes:
- **common/src/services/keyConnector.service.ts**
- add missing await (whoops!)
- move the request model constructor call out of the try/catch block, it was giving me misleading error messages otherwise
**directory-connector will need a jslib update after this is merged.**
See linked cli ticket.
> Fix migration to Key Connector in cli commands

- common/src/models/domain/globalState.ts
- common/src/services/state.service.ts
- common/src/services/stateMigration.service.ts
Currently the StateMigrationService depends on a userId key for running migrations, but if there is not an authenticated user saved to storage that userId is not present and settings are not migrated.
These changes allow for migrating state data even without an active user. For account specific settings like clearClipboard we now temporarily store those values together in disk state until an account is authed that they can be added to. Temp account state is then cleared.
Some notes:
* In order for this to work we need GlobalState.stateVersion to have a default value of StateVersion.One instead of StateVersion.Latest. Defaulting it to latest was causing migrations to not run on some clients (like desktop) that try to access storage before migrations have been run but save a version as if …
> [bug] Migrate state even if there is not a user logged in

- common/src/services/stateMigration.service.ts
A couple of helper methods were recently added to the StateMigrationService, but they were set to private and can't be used in children.
Some clients, like the Directory Connector, extend the StateMigrationService and need access to these methods.
> [Bug] Change method scope for internal StateMigrationService methods

- common/src/services/cipher.service.ts
https://app.asana.com/0/1201648796371593/1201630489910986
Search indexing is not working across clients, resulting in slower search speeds and bugs like not being able to search deleted items.
This commit calls the method responsible for setting decrypted ciphers and indexing when decrypting, instead of setting decrypted ciphers directly. This is what we are doing in production right now, and we erroneously changed this behavior with the move to a central service for handling application state.
> [bug] Index search service when setting decrypted ciphers

- common/src/services/state.service.ts
There is a use case that overrides locally set environmentUrls: an initial boot of a logged out application.
We override environmentUrls with whatever the temporary settings store has, even if different urls are added before authenticating.
This commit ensures we always use input environmentUrls.
> [bug] Always set environementUrls from client when scaffolding an account

- common/src/services/state.service.ts
- common/src/services/stateMigration.service.ts
Some processes, like biometrics, will have already begun modifying state before migrations are run.
We currently don't account for this when migrating, leaving first time startups in a state where some expected values, like biometrics, will be null.
Additionally some clients set default values for specific account settings, like vaultTimeout, that are being lost when migrating temp storage. This results in unexpected behavior like vaultTimeout being set to "never" for fresh installs and even clients that don't allow this setting.
* Check for existing globals during migration and merge it with the migration globals if found
* Assign copied temp storage to a client's Account class to ensure defaults are being honored.
> [bug] Address existing data & defaults when migrating from an unauthenticated state

- common/src/services/state.service.ts
Set environmentUrls after assigning defaults for scaffolding to prevent clearing
> [bug] Set envUrls after assigning defaults during scaffolding

- common/src/services/environment.service.ts
Previously when only one account could be authenticated at a time if a baseUrl was found we didn't need to worry about setting other urls in the environmentService, and simply returned after setting base.
With account switching it is possible to have multiple url configurations, some with a baseUrl and some without, and this early return was causing accounts configured this way to clash. It became possible to have something like:
urls.baseUrl = 'https://testdo.bitwarden.com' set as the base url for an account that was intended to target the cloud, causing deauthenticated sessions.
This commit ensures that all urls are set each time getUrlsFromStorage is called.
> [bug] Set all urls when setting urls from storage

- common/src/services/stateMigration.service.ts
Some fields, like biometrics, are set before we can run the state migration
For some use cases, like initial install, this can lead to migration clearing those fields when it doesn't find them in storage.
Another issue found with this is that StateVersion will remain 1 and never upgrade to 2, resulting in accounts being deauthenticated on each run of the app.
This commit sets up an order of checks for migrating globals that considers fields that may already have been set.
> [bug] Ensure globals set before migration is run are not lost

- common/src/models/domain/account.ts
- common/src/models/domain/globalState.ts
- common/src/services/state.service.ts
- common/src/services/stateMigration.service.ts
Enable Browser Integration should be a global setting, but currently we have it set at the account level.
* Remove enableBrowserIntegration from the AccountSettings model
* Add enableBrowserIntegration to the GlobalState model
* Update get/set functions in stateService to expect enableBrowserIntegration to be global
* Update state migrations to treat enableBrowserIntegration as a global setting
> [bug] Move enableBrowserIntegration to global state

- common/src/services/state.service.ts
While testing on browser the `stateService.init()` is called every time when opening the extension window. Which causes issues with access to dead objects when initAccountState is called. To ensure migrations and initialization only happen once, I've added a boolean to check the state.
- **common/src/services/state.service.ts:** Add boolean to only call init once
Tested this change locally on browser and desktop and did not experience any issues.
Regression testing on account switching needed
> [Account switching] Ensure that initialization and migration only run once

- common/src/abstractions/crypto.service.ts
- electron/src/services/electronCrypto.service.ts
Exposes the `userId` argument of `getKeyFromStorage` which is needed to support native messaging with multiple accounts.
> Expose getKeyFromStorage with userId

- angular/src/components/login.component.ts
With Account Switching we tweaked the way logic determined if an email should be remembered or not. Instead of storing a specific boolean key to know whether or not we had a remembered email on init, we just check to see if a remembered email already exists. This works well for apps like web, where remember email is also controllable with an input, but not so much for apps that always remember email like browser and desktop.
Instead of going back to the way things were and having client specific logic in the base login component, we should ensure that we always remember emails for clients that behave that way in the clients that need to special case.
This commit exposes a component variable that can be set by clients to determine if email should always be remembered.
> [bug] Ensure clients that always remember emails have an avenue to do so

- common/src/importers/keeperImporters/keeperCsvImporter.ts
- common/src/importers/keeperImporters/keeperJsonImporter.ts
- common/src/importers/keeperImporters/types/keeperJsonTypes.ts
- common/src/services/import.service.ts
- spec/common/importers/keeperJsonImporter.spec.ts
- spec/common/importers/testData/keeperJson/testData.ts
To aid new users in migrating to Bitwarden we offer a wide variety of importers. This PR adds importing `.json` exports from Keeper, providing our new users a really smooth transition into Bitwarden.
The importer supports creating Login types with the following fields:
- Title
- Username
- Password
- URIs
- TOTP
- Notes
- Folders/Collections (Only creates collections when an import is done from within an organization)
- and creates custom fields for any fields in the custom_fields that could not be mapped
**The permissions present in the shared_folders are not imported. These will have to be set once the data has been imported.**
For more information on exporting from Keeper: https://docs.keeper.io/user-guides/export-and-reports/vault-export
and for information on the json export: …
> BEEEP: Add importer for Keeper in json format

- common/src/abstractions/state.service.ts
- common/src/models/domain/globalState.ts
- common/src/services/state.service.ts
- common/src/services/stateMigration.service.ts
A good refactor point was made that we can use the ThemeType enum instead of strings when managing theme in state. 
Convert type used for theme in the state model, service, and migration
> [refactor] Use ThemeType enum instead of string

- common/src/abstractions/environment.service.ts
- common/src/services/environment.service.ts
With the change to our state model to have a concept of an "account" we started saving global environmentUrls to a temporary location in storage to be fetched and added to any newly authed accounts
This isn't compatible with the option to not save envUrls passed to setUrls to storage, since we need that storage value to handle urls for authed accounts. This is only applicable to web.
There was some discussion around maybe extending the environmentService in web to skip the temporary storage route, since web isn't planned to ever offer account switching, but that would also require a distinction in web specifically that environmentUrls aren't an account level data point, which isn't really true. Ultimately I think just removing this option is the clearest way to make this work.
* Remove …
> [bug] Always save environmentUrls passed to setUrls

- angular/src/services/jslib-services.module.ts
- common/src/factories/accountFactory.ts
- common/src/factories/globalStateFactory.ts
- common/src/factories/stateFactory.ts
- common/src/models/domain/account.ts
- common/src/models/domain/globalState.ts
- common/src/models/domain/state.ts
- common/src/services/state.service.ts
- common/src/services/stateMigration.service.ts
Some clients have unique global setting defaults (and unique global settings)
For example: the web vault defaults to light theme, but most clients with theme support default to system theme.
The current way we handle `GlobalState` is buried in jslib and not easily extendible in clients.
To fix this, we need to treat `GlobalState` as a generic in the `StateService` and `StateMigration` service and allow for its extension in those methods and anywhere `GlobalState` is inited. We already use this pattern for extending the `Account` object into clients.
* Set the default `ThemeType` to `System`, since that is the standard among clients.
* Move `AccountFactory` into a folder dedicated to factories
* Add a `GlobalStateFactory`, and a `StateFactory` that combines the combines the two for one …
> [bug] Allow for GlobalState to be extended and modified in clients

- angular/src/components/update-password.component.ts
Asana: https://app.asana.com/0/1169444489336079/1200003629652775/f
We currently don't check master passwords against the org policy when accepting an invite from an existing account. We can't perform this server side as the password is encrypted, so this PR introduces the validation in the web client.
When a user logs in to accept an invite, we will check the password against the organization policy. If it fails, we ask the user to change their password to accept the invitation. Once the user changes it, we log out and require the user to log in once more with the changed password to accept the invitation. If the user cancels, we clear the org invite from storage and navigate them to the vault. 
- **angular/src/components/update-password.component.ts:** Create a new update-password …
> Master password policy is not checked when accepting invite from an existing account

- angular/src/components/avatar.component.ts
The avatar components generates an error message before the `src` component has had time to load. To resolve this I added a `*ngIf` check which triggers when `src` is null.
> Fix avatar error when src is undefined

- common/src/services/import.service.ts
I recently added an importer for the Keeper json format https://github.com/bitwarden/jslib/pull/608. During testing we found some issues and room for improvement to support additional item types. 
This PR is gonna hide the option from the WebVault import dropdown/cli import
Asana task: https://app.asana.com/0/1200804338582616/1201763333842566/f
This will need cherry picking 🍒 ⛏️  to `rc`
- **common/src/services/import.service.ts:** Comment out the keeperJson import / Hide it from the dropdown
> Temporarily remove keeper json import for the Feb release

- common/src/services/api.service.ts
We've moved `prelogin` and `register` endpoints to the Indentity project
Reflecting that change here
Related to https://github.com/bitwarden/server/pull/1837. https://github.com/bitwarden/server/pull/1807 moved endpoints into identity, but we did not update this project at the time to point to the new location, but the obsolete API location. This PR updates to the newer path.
* **api.service**: override api url with identity url for calls moved to that project.
Validate registration and login still work as expected
> Use Identity server routes

- common/src/enums/authenticationType.ts
- common/src/models/domain/logInCredentials.ts
- common/src/services/auth.service.ts
The authService refactor was broken on browser. `authService.logIn` identifies the `credentials` subclass by using `instanceof`. However, browser has different webpack bundles for the background page and the popup, so a `credentials` object constructed in the popup and passed to the background page is not an `instanceof` the same class as it exists in the background.
Now, we just switch based on an enum identifying the authentication type which the credentials are used for.
Note: client PRs are on hold until this is merged.
Covered under the authService refactor ticket.
> [authService refactor] Fix browser by not using instanceof

- common/src/models/domain/account.ts
- common/src/models/domain/state.ts
- common/src/services/state.service.ts
- common/src/services/stateMigration.service.ts
https://app.asana.com/0/1201648796371593/1201771028067731
This will need to be cherry-picked to all clients.
During the storage data model refactor we have frequently seen issues where the frequency at which we record activity sometimes creates a race condition with other operations that create unexpected behavior. 
This happens because activity tracking runs outside of normal client processes, and runs a lot (on every click, for example), but access the same Account storage key as other operations (like saving vault timeout settings). This creates a race condition where:
1. The vaultTimeout.valueChange methods starts modifying state to save the updated setting
2. At the same time (from the same click) activity tracking starts its process to record activity
3. Both operations, running at …
> [bug] Make activity a top level storage key

- angular/src/services/jslib-services.module.ts
- common/src/services/state.service.ts
- common/src/services/vaultTimeout.service.ts
https://app.asana.com/0/inbox/1183359552741416/1201787020823690/1201782081866250
This will need to be cherry picked to rc
When an account has the Vault Timeout Action set to Logout, the other authenticated accounts incorrectly get logged out
* Pass userId in to the logout callback parameter to the vaultTimeoutService. The message handle in desktop already expects this.
* Set lastActive on account login, and null it on account deauthentication. This prevents an issue where newly logged in accounts immediately time out due to inactivity.
> [bug] Fix logout timeout action for inactive accounts

- common/src/abstractions/token.service.ts
- common/src/services/state.service.ts
- common/src/services/token.service.ts
- common/src/services/vaultTimeout.service.ts
https://app.asana.com/0/inbox/1183359552741416/1201787020823699/1201795621278997
This will need to be cherry picked to rc
In production we store tokens in different locations based on timeout action. If the timeout action is set to "lock", we save tokens to memory for normal use and to disk in order to maintain authenticated sessions on startup. If the timeout action is set to "log out" we only store tokens in memory, so when the app is closed it takes authenticated sessions with it. In production most of this switch happens in [`toggleTokens()`](https://github.com/bitwarden/jslib/blob/f4c66b2c8c243935bf25f689b16afaa5d6345f1b/common/src/services/token.service.ts#L92-L113).
With the state refactor I misunderstood this and broke it, only ever saving tokens to disk. As far as I know this …
> [bug] Toggle tokens appropriatly based on timeout action

- common/src/models/domain/account.ts
- common/src/services/state.service.ts
Fix providers portal links being removed on vault refresh and unlock.
[Ticket](https://app.asana.com/0/1169444489336079/1201797137809540)
- **common/src/services/state.service.ts:** Save providers to 'disk' so that they are persisted after page refresh and vault unlock. They only get set from the syncAll() api call, so we can't rely on them being reset in memory on page refresh.
Ensure that Providers links are present after vault is refreshed and locked.
> Move providers to profile and save to disk

- common/src/services/sync.service.ts
Now that organizations and providers are saved to the same state object, we need to save them individually instead of at the same time because they were causing shenanigans and overwriting each other. 
- **common/src/services/sync.service.ts:** Await saving of organizations and providers individually
Ensure both organizations and providers show up as expected on the vault page.
> Individually await saving of orgs and providers

- common/src/services/state.service.ts
`everBeenUnlocked` is not meant to be stored long term. [Previously](https://github.com/bitwarden/jslib/blob/b4f475251aa6817403117b71fb5a8836cdae9c75/common/src/services/vaultTimeout.service.ts#L23), it was tracked using a service variable. The storage refactor incorrectly began saving this value to disk, creating issues with never lock situations. If a user:
1. Previously installed Bitwarden (is migrating)
2. Updates (migrates, everBeenUnlocked set to null)
3. Logs in (everBeenUnlocked is set to true)
4. Changes to Never Lock
5. Closes the browser
6. Reopens it
You can observe that the vault is locked, because everBeenUnlocked returns true [here](https://github.com/bitwarden/jslib/blob/5fad7c666f0fa301a180ec1a72794b1fd6088a5e/common/src/services/vaultTimeout.service.ts#L56), causing us …
> [bug] Store everBeenUnlocked in memory

- common/src/services/state.service.ts
Prevent so much disk i/o with the new large account object being read so much.
Adds an account cache in memory to buffer the disk reads.
Regression
> Cache state service account blob from disk reads

- angular/src/components/lock.component.ts
Fixes a minor regression bug where the autoprompt for biometric is never shown on desktop. This is due to not awaiting the first `load` call prior to watching the observable.
Biometric is shown immediately upon opening the desktop app to unlock
> Load component on init, then watch

- common/src/services/crypto.service.ts
It seems `hasKeyStored` returned true when checking for biometric keys since `hasCryptoMasterKeyBiometric` returns a boolean which should never be null.
Should resolve https://github.com/bitwarden/browser/issues/2334
I've tested this in browser, but we probably need to investigate if this has sideeffects in the other clients.
> Resolve hasKeyStored returning true when no biometric key is stored

- common/src/services/state.service.ts
With https://github.com/bitwarden/jslib/pull/668 we introduced an account cache which results in good performance but had some issues when logging out and back in again.
- **common/src/services/state.service.ts:** Make sure the account cache is cleared when logging out
Testing will be done on the clients with logging out of accounts and back in again. Also with timeoutAction == logout
> Clean up the cached account

- common/src/services/state.service.ts
We aren't running the account scaffolding methods that happen during login through saveAccount, and so they aren't being cached. This is creating a confusing state for applications and authenticating them inappropriately. 
* Call saveAccount from the scaffolding methods. Only one of these is relevant, since the other two are web specific and don't cache, but we should still be pushing all account saving logic through saveAccount.
https://user-images.githubusercontent.com/15897251/153625545-c1347382-3ad8-4523-8c13-4dfa2eed5b07.mov
> Run addAccount storage scaffolding calls through saveAccount

- common/src/services/state.service.ts
Logging out in some clients is crashing because the active user is being set back to the user that was just logged out.
I'm not entirely sure when/how this started, but a simple length check on state and setting the active user to null if we don't have any options does the job of logging out successfully. 
* Set active userId to null if state doesn't have any users
* Use getAccount/saveAccount for account teardown functions. I don't think this has any effect on the bug, but we should be using those methods for all account access, especially with the cache addition.
> Clear active user if state has no users

- common/src/enums/stateVersion.ts
- common/src/services/stateMigration.service.ts
- spec/common/services/stateMigration.service.ts
Fix bitwarden/browser#2337, for real this time.
The previous fix (https://github.com/bitwarden/jslib/pull/667) moved the `everBeenUnlocked` key from onDisk to inMemory storage.
However, `stateService.init()` loads the onDisk values into memory on startup. If the old onDisk value is left behind, it'll be loaded into memory, and that will continue to be used as the `everBeenUnlocked` value. The defect persists until users clear local storage.
Add another `StateVersion` migration, following a similar pattern as #666.
> Clear stale everBeenUnlocked value from onDisk storage

- common/src/services/state.service.ts
When a user has multiple logins for the same site, the list is sorted by the lastUsedDate on the localData state object.
This was formerly saved to local storage, so it was persisted across browser restarts. With the state service refactor, this was moved to memory storage, which is wiped when the browser is restarted.
I checked to see what other items are save to the localData object so I don't break anything with this change, and it appears that lastUsedDate and lastLaunched are the only data items saved to it so I think we are fine here.
- **common/src/services/state.service.ts:** Get and save localData to local storage instead of in memory
Use autofill for a site that the account has multiple logins for, then quit the browser. Open the browser again and verify that the last item …
> Save localData to local storage instead of in memory

- common/src/services/crypto.service.ts
Allow new `bw serve` command to work without getting stuck in an infinite recursion loop.
It's still not clear to be with this only happens when running the new `bw serve` CLI command. Perhaps because all other clients are preceded by an unlock function of some sort.
Moved `getEncKey()` functionality out to a private helper so that the `sequentialize()` decorator does not try to parallelize the call when coming from other internal functions such as `validateKey()`.
No behavior to test here other than ensure we do not lose the performance boost of  `getEncKey()` being sequentialized in other areas of the code, such as vault decryption.
> fix infinite recursion on getEncKey

- angular/src/scss/bwicons/styles/style.scss
Cleanup the new `bwicons -> styles.scss` file that has deprecation warnings revolving around the use of `/` for division.  Use the `calc()` function since the `math.div` function is not available in our current version of `sass`
- **styles.scss:** Surrounded all division math with the `calc()` function. Removed unused `export` call
- Make sure icons using either `bwi-fw, bwi-lg, bwi-ul, bwi-li, or bwi-li & bwi-lg` still appear the same throughout the client applications (once the updated `jslib` has been applied)
> [Icons] Fix sass deprecation warnings

- angular/src/components/export-scope-callout.component.html
- angular/src/components/export-scope-callout.component.ts
- common/src/abstractions/organization.service.ts
- common/src/services/organization.service.ts
https://app.asana.com/0/1183359552741420/1200074829339233
Exports are often confusing to users in organizations because there is no indication on screen that a personal export won't include organization items and vice versa. We should add an information panel to this screen noting what exactly is being exported.
- **organization.service:** Added a `hasOrganizations()` method.
- **export-scope-callout.component:** Created this component to be used in client `export.component` templates.
> [feature] Implement scope warning for exports

- common/src/models/domain/account.ts
- common/src/services/state.service.ts
https://app.asana.com/0/1169444489336079/1201880324649413
Move collapsedGroupings to accountSettings, which is not cleared on logout or during login scaffolding. 
* Move collapsedGroupings to accountSettings in the Account model and reference it correctly in StateService get/set functions.
> [bug] Store collapsedGroupings in accountSettings

- common/src/models/domain/account.ts
- common/src/services/state.service.ts
Fix https://github.com/bitwarden/browser/issues/2400.
`autoFillOnPageLoadDefault` should default to true if it's not explicitly set. Note that this is the default per-item autofill setting - it still won't do anything unless `enableAutoFillOnPageLoad` is true (to enable the feature in general).
The intention was always to replicate the previous behaviour, where once Autofill On Page Load was enabled, all items would autofill by default unless configured otherwise.
Luckily this does not appear to be a migration issue as such, any saved value should still have been migrated, we just need to handle the `null` case.
Change default value if null.
* use browser client on a fresh install (no saved data)
* log in
* confirm that Settings > Options are:
* Enable Auto-Fill On Page Load: `false`
* …
> Fix autoFillOnPageLoadDefault default value

- common/src/services/stateMigration.service.ts
Fix https://github.com/bitwarden/cli/issues/490.
`encOrgKeys` are never migrated properly because `stateMigrationService` does not reference the correct storage key - it incorrectly appends the `userId` to the storage key. This means that org items cannot be decrypted in CLI after an upgrade. I assume that other clients hid this issue by syncing to get account keys, whereas CLI is less automatic in this respect.
For reference, here's the `setOrgKeys` method immediately before account switching was merged. Note the lack of userId suffix: https://github.com/bitwarden/jslib/blob/8fc3cf50d2967212ffbbf0d57cac71d0774aa2a8/common/src/services/crypto.service.ts#L97
The migration of provider enc keys also follow this pattern, and I also note that the pre-account switching logic doesn't have this …
> Fix v1 migration of providerKeys and orgKeys

- common/src/services/cipher.service.ts
While working on [this](https://github.com/bitwarden/server/pull/1890), I noticed that if a bulk share action fails, the items in the cipher view are updated to show that they transferred to the organization even though they were not. 
The items in the vault that were attempted to be shared are then in this state until a sync is performed or the vault is refreshed.
- **common/src/services/cipher.service.ts:** Add try catch that reverts setting of items `organizationId` and `collectionIds` properties if the api call fails.
Make sure that if an item fails to share to an organization (e.g. has attachments and is sent to a free org)
> Roll back organizationId and collectionId's if ciphers fail to be moved

- angular/src/components/two-factor.component.ts
- common/src/abstractions/auth.service.ts
- common/src/misc/logInStrategies/logIn.strategy.ts
- common/src/misc/logInStrategies/passwordLogin.strategy.ts
- common/src/services/auth.service.ts
- node/src/cli/commands/login.command.ts
- spec/common/misc/logInStrategies/logIn.strategy.spec.ts
> Fix issue with captcha bypass token received on the `login` component being persisted during the 2fa flow
> Expand the current implementation to allow for captcha to be collected on the `two-factor` component and passed along to through the auth flow
> Update `cli - login.command` to handle captcha bypass and collection during the `2fa` flow
- **two-factor.component:** Extended `CaptchaProtectedComponent` and applied the setup, response handling, and passing of the `captchaResponse` into the the `logInTwoFactor` call
- **(abstraction/service)auth.service:** Updated `logInTwoFactor` method to take a passed in `captchaResponse`. Updated the state clearing to allow for captcha responses triggered from failed `2fa` attempts.
- **logInStrategy.ts**: Base class - extended the `logInTwoFactor` …
> [Captcha] Failed login attempts

- common/src/services/state.service.ts
We aren't completely removing keytar keys right now, and instead are just nulling out values. We should be completely cleaning up those keys if they are set to null, like on logout..
To achieve this I checked for a null value on any secure storage set operations and used the `remove` method instead of `save` if the passed in value is null.
https://user-images.githubusercontent.com/15897251/156616575-2409e877-056a-497f-bc77-930cb9e24026.mov
> [bug] Delete stored keys if passed in value is null

- common/src/enums/importOptions.ts
With https://github.com/bitwarden/jslib/pull/708 we added the new Dashlane csv importer. As Dashlane has removed support for the JSON format, the CSV importer should be on the featureList instead
- **common/src/enums/importOptions.ts:** Removed the Dashlane json importer from the featured importer list
> Remove Dashlane json importer from the featured importer list

- common/src/importers/mykiCsvImporter.ts
- spec/common/importers/mykiCsvImporter.spec.ts
- spec/common/importers/testData/mykiCsv/UserAccount.csv.ts
- spec/common/importers/testData/mykiCsv/UserCreditCard.csv.ts
- spec/common/importers/testData/mykiCsv/UserIdCard.csv.ts
- spec/common/importers/testData/mykiCsv/UserIdentity.csv.ts
- spec/common/importers/testData/mykiCsv/UserNote.csv.ts
- spec/common/importers/testData/mykiCsv/UserTwofa.csv.ts
With the announcement of Myki discontinuing their existing products on April 10th, 2022, after being aquired by JumpCloud, it was time to revisit our Myki importer.
This PR fixes some minor issues and adds support for previously not imported exports types (`UserIdCard.csv` and `UserTwoFA.csv`).
Asana task: https://app.asana.com/0/1200578627114106/1201930330138516/f
**Rough overview of imported ciphers/fields:**
- Empty fields are skipped
- All unmapped columns are imported as custom fields (for example: status and tags)
- **Login items - `UserAccount.csv`**
- Username
- Password
- TOTP
- Notes
- **TwoFA - `UserTwoFa.csv`**
- nickname -> CipherTitle
- TOTP
- Notes
- **CreditCard items - `UserCreditCard.csv`**
- Cardholder
- CC Number
- CVV
- Expiry date
- Card brand is set using CC Number …
> Fixes and improvements to MykiCsvImporter

- common/src/importers/onepasswordImporters/onepassword1PuxImporter.ts
- common/src/importers/onepasswordImporters/types/onepassword1PuxImporterTypes.ts
- spec/common/importers/testData/onePassword1Pux/APICredentials.ts
- spec/common/importers/testData/onePassword1Pux/BankAccount.ts
- spec/common/importers/testData/onePassword1Pux/CreditCard.ts
- spec/common/importers/testData/onePassword1Pux/Database.ts
- spec/common/importers/testData/onePassword1Pux/DriversLicense.ts
- spec/common/importers/testData/onePassword1Pux/EmailAccount.ts
- spec/common/importers/testData/onePassword1Pux/IdentityData.ts
- spec/common/importers/testData/onePassword1Pux/LoginData.ts
- spec/common/importers/testData/onePassword1Pux/MedicalRecord.ts
- spec/common/importers/testData/onePassword1Pux/Membership.ts
- spec/common/importers/testData/onePassword1Pux/Onepux_example.ts
- spec/common/importers/testData/onePassword1Pux/OutdoorLicense.ts
- spec/common/importers/testData/onePassword1Pux/Passport.ts
- spec/common/importers/testData/onePassword1Pux/Password.ts
- spec/common/importers/testData/onePassword1Pux/RewardsProgram.ts
- spec/common/importers/testData/onePassword1Pux/SSN.ts
- spec/common/importers/testData/onePassword1Pux/SanitizedExport.ts
- spec/common/importers/testData/onePassword1Pux/SecureNote.ts
- spec/common/importers/testData/onePassword1Pux/Server.ts
- spec/common/importers/testData/onePassword1Pux/SoftwareLicense.ts
- spec/common/importers/testData/onePassword1Pux/WirelessRouter.ts
It seems that 1password has changed the structure of their 1pux file format, since I wrote the importer with the file I received.
```
//Before:
items: [
{
item: {
}
}
]
```
```
//Current
items: [
{
}
]
```
This will need to be 🍒 ⛏️ to `rc`
Asana task: https://app.asana.com/0/1200578627114106/1201633451894388/f
- **common/src/importers/onepasswordImporters/types/onepassword1PuxImporterTypes.ts:** 
- Removed the `ItemCollection` type and use `Item[]` instead
- Made `item.trashed` and optional property
- **common/src/importers/onepasswordImporters/onepassword1PuxImporter.ts:** 
- Removed the import of the no longer needed `ItemCollection`
- Fixed the type used in the `vaults.items.forEach`
- **spec/common/importers/testData/onePassword1Pux/\*.ts:** Removed the unneeded named object `item` …
> Fixes for format change of 1pux files

- angular/src/components/groupings.component.ts
https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-94
Allow for types, collections, and folders to be collapsed, and establish a pattern for collapsing other top level groupings (like the forthcoming All Vaults grouping).
This PR allows for collapsing top level groupings by creating a couple of static groupings to use in the preexisting collapse logic. These can be applied to templates in clients.
* Create a new node type: TopLevelGrouping
* Change collapse logic to use any ITreeNodeObject
> [End User Vault Refresh] Allow for top level groupings to be collapsed

- common/src/abstractions/sync.service.ts
- common/src/services/sync.service.ts
Fix https://github.com/bitwarden/web/issues/1324.
I came across this code in the web navbar component which is likely causing duplicate fullSyncs: https://github.com/bitwarden/web/blob/master/src/app/layouts/navbar.component.ts#L38
That code is not unreasonable though, sometimes we need to ensure a full sync has been done. Better to handle duplicate calls in syncService so that callers don't need to worry about it.
Add sequentialize decorator to `syncService.fullSync`.
> Avoid duplicate fullSync api calls

- angular/src/directives/api-action.directive.ts
- common/src/services/cipher.service.ts
- node/src/cli/commands/login.command.ts
After minification was added to browser last release, we started mangling constructor names. This breaks our runtime type checking.
This PR fixes the issue by determining the appropriate constructor name at runtime as well.
Fixes https://app.asana.com/0/1169444489336079/1201956221046192/f
This will be cherry picked to `rc`
Validate that linked issue is resolved.
> Check runtime name vs mangled name

- angular/src/directives/api-action.directive.ts
Minimization is impacting type checking in a non-consistent way. The previous type check works locally, but not from build artifacts :shrug:. We only set `captchaRequired` on our errors when we want a resubmit with captcha included, so we're safe keying off that
Remove ErrorResponse type requirement from api-action.directive checking
Will be tested in clients. related to https://app.asana.com/0/1169444489336079/1201956221046192/f
> Remove error Response type check

- angular/src/pipes/ellipsis.pipe.ts
I noticed that we don't have a nice way to truncate large text (such as organization names) while working on the end user vault refresh work for browser, so I added this ellipsis pipe to do just that 🙂  
The default limit is 25 characters, but you can pass the amount you want to add the ellipsis on. You can also pass a flag to break on complete words and to also change what the ellipsis is.
- **angular/src/pipes/ellipsis.pipe.ts:** Add ellipsis pipe
None, until it is used in one of our clients.
> Add ellipsis pipe

- electron/src/utils.ts
`isMacAppStore()` was returning undefined if on mac and not a MAS build. This fix forces the function to return true/false
- **file.ext:** Description of what was changed and why
`isMacAppStore` is called during the update function (to make sure the build is not a MAS build), while building the toolbar menus (some options like "Check for Update" is not available on MAS build) and while closing the window (to keep application alive in background until user quits it with Cmd-Q). These will need to be checked.
> PS-91 make isMacAppStore return true/false

- common/src/importers/safariCsvImporter.ts
- spec/common/importers/safariCsvImporter.spec.ts
- spec/common/importers/testData/safariCsv/oldSimplePasswordData.csv.ts
- spec/common/importers/testData/safariCsv/simplePasswordData.csv.ts
Currently, the Safari CSV importer does not handle the modern Safari/macOS export format where the header includes an upper case `URL` field. Also, notes within the Passwords.csv file were ignored.
See the format used below as of macOS 12.3 and Safari 15.4.
- **safariCsvImporter.ts:** Updated login `URL` and `Notes` field parsing
- Unit tests for both formats were also added
- Importing password exports from Safari/macOS works for different CSV header formats
- Notes and URLs from Safari/macOS password exports are included in Bitwarden items
> [bug] Fix Safari CSV importer for URL and Notes

- spec/common/importers/safariCsvImporter.spec.ts
Happily merged https://github.com/bitwarden/jslib/pull/730 and realized the import path for the safariCsvImporter was wrong and thus the build failed.
- **spec/common/importers/safariCsvImporter.spec.ts:** Fix the import path of the SafarCsvImporter
> Fix import path for safari importer

- angular/src/components/password-generator.component.ts
- angular/src/services/jslib-services.module.ts
Add ability to pass username website to base component so that it can be property set inside the scope of 
`route.queryParams.pipe` subscription. This is used for passing in the context of the item website being edited so that it can be used in the generator.
Also added username generator service to angular DI service module in jslib.
password-generator.component.ts - Added websiteUsername property to override username options.
jslib-services.module.ts - resolve username gen service
n/a
> support for username gen website setting

- angular/src/jslib.module.ts
We override the verify master password component in the client projects, which does not seem possible when the module is already defined.
> Remove the VerifyMasterPasswordComponent from jslib module

- angular/src/components/generator.component.ts
- angular/src/components/password-generator.component.ts
Following the addition of the username generator, the password generator component had a few outstanding cleanup items to attend to. This PR addresses them. Client repo PRs reacting to these changes will follow.
- Rename `PasswordGenerator` component to `Generator`.
- Rename `showSelect` property to `comingFromAddEdit` per feedback from @eliykat 
- Remove `showWebsiteOption` property since the same logic can be derived from `usernameWebsite`.
- Default `type` to null so that it can be properly set based on logic from `onInit` or passed in from child component.
Standard generator testing as defined in previous PRs for this feature.
> Generator cleanup

- components/src/button/button.component.spec.ts
- components/src/button/button.component.ts
- components/src/callout/callout.component.spec.ts
- components/src/callout/callout.component.ts
> Callout `headerClass` color was being overridden via Bootstrap styling on the client level. Force the color to be `important!`
> Button `display` was not defaulting to `inline-block`
- **button.component.spec.ts**: Added tests for handling `block` vs `inline-block` display styling
- **button.component.ts**: Defaulted display styling to `inline-block` to match existing button pattern
- **callout.component.spec.ts**: Added additional context to existing tests regarding the `headerClass` color
- **callout.component.ts**: Forced `headerClass` to be `important!` in order to override bootstrap styling on the client
- Make sure Callout's `headerClass` matches the desired color scheme
- Make sure Button's default `display` styling is `inline-block`
> [bug] CL - fix default button display and callout header class

- common/spec/importers/onepassword1PuxImporter.spec.ts
- common/spec/importers/testData/onePassword1Pux/Emailfield.ts
- common/spec/importers/testData/onePassword1Pux/EmailfieldOnIdentity.ts
- common/spec/importers/testData/onePassword1Pux/EmailfieldOnIdentity_Prefilled.ts
- common/spec/importers/testData/onePassword1Pux/SanitizedExport.ts
- common/spec/importers/testData/onePassword1Pux/SoftwareLicense.ts
- common/src/importers/onepasswordImporters/onepassword1PuxImporter.ts
- common/src/importers/onepasswordImporters/types/onepassword1PuxImporterTypes.ts
Some user where experiencing issues while importing a 1pux export into Bitwarden. The reason being, that a new email field type was introduced which got parsed incorrectly. This caused corruption while encrypting into a Bitwarden identity type and failed the import.
I also discovered that these email fields got falsely skipped and should have been imported as custom fields.
Old format
```
"value": {
"string": "someuser@someprovider.com"
},
```
New format
```
"value": {
"email": {
"email_address": "someuser@someprovider.com",
"provider": null
}
},
```
Original report: https://github.com/bitwarden/web/issues/1548
- **common/src/importers/onepasswordImporters/types/onepassword1PuxImporterTypes.ts:** Change type of email field typefrom string to object
- …
> [EC-142] Fix error during import of 1pux containing new email field format

- common/src/services/passwordGeneration.service.ts
- common/src/services/usernameGeneration.service.ts
Generation services have a DefaultOptions object that was getting set by reference. This caused any changes made to the options later on to alter DefaultOptions itself. Future assignments of DefaultOptions would then have those values.
Resolve https://app.asana.com/0/1153292148278596/1202089012747649
Changed DefaultOptions assignment to copy by value in username and password generation services.
Re-test steps in https://app.asana.com/0/1153292148278596/1202089012747649
> copy generator default options by value

- angular/src/modules/vault-filter/vault-filter.component.ts
https://bitwarden.atlassian.net/browse/SG-203?atlOrigin=eyJpIjoiYjAyM2NhODc2YWEyNDdhMjlmZTJjN2ExM2ZhNzE0ZGIiLCJwIjoiaiJ9
Sometimes changing an organization filter involves resetting the filter modifier because the current one is not relevant to the new organization filter. One example of this is if a collection is selected, as changing an organization filter will always invalidate a selected collection. We are missing a null check when we check this to prune the filter, resulting in filter changes sometimes not being applied and console errors.
This commit adds a null check when correcting a requested filter change.
> [end user vault refresh] [bug] Add missing null check in vault filters

- common/spec/services/export.service.spec.ts
- common/src/importers/bitwardenJsonImporter.ts
- common/src/models/export/cardExport.ts
- common/src/models/export/cipherExport.ts
- common/src/models/export/cipherWithIdsExport.ts
- common/src/models/export/collectionExport.ts
- common/src/models/export/collectionWithIdExport.ts
- common/src/models/export/eventExport.ts
- common/src/models/export/fieldExport.ts
- common/src/models/export/folderExport.ts
- common/src/models/export/folderWithIdExport.ts
- common/src/models/export/identityExport.ts
- common/src/models/export/loginExport.ts
- common/src/models/export/loginUriExport.ts
- common/src/models/export/secureNoteExport.ts
- common/src/services/export.service.ts
We currently have two sets of DTOs named identical, `domain` and `export`. To avoid confusion this PR adds a `Export` suffix to the export DTOs.
EC-147
Verify the export and the bitwarden json importer still works.
> Rename Export DTOs

- common/src/services/usernameGeneration.service.ts
Fix default username generation options so that simplelogin is the default selection when not having used the feature before.
- **username generation service:** Change property name to what is actually used in implementation.
Make sure simplelogin is default selection for forwarded email service.
> fix default forwardedService property name

- angular/jest.config.js
- common/jest.config.js
- electron/jest.config.js
- jest.config.js
- node/jest.config.js
Removes some deprecation warnings for jest. (`ts-jest/utils` is gone in the next version of `ts-jest`)
> [EC-192] Use ts-jest instead of deprecated ts-jest/utils

- angular/src/modules/vault-filter/components/status-filter.component.ts
Fix condition to only hide status filters if both favorites and trash are hidden. 
- **angular/src/modules/vault-filter/components/status-filter.component.ts:** Fix show() condition
> [SG-245] “All Items” and “Trash” missing from Organization Vault

- components/src/stories/colors.stories.mdx
- components/src/tw-theme.css
- components/tailwind.config.base.js
Add the text color alt2 as contrast option to background alt2.
Note: Will be cherry picked to `rc`.
> [SG-234] Add alt2 text color

- angular/src/modules/vault-filter/vault-filter.component.ts
https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-239
This will need to be cherry picked to rc
When loading the organization vault page initially all collections are displayed as filters instead of just the collections for the selected organization. This only happens on init, and toggling orgs creates the correct filters.
This is happening because the collection init logic is in jslib's `VaultFiltersComponent.ngOnInit()`, and the concept of an organization vault screen only exists in web. The collection init call needs to be exposed to web's `VaultFiltersComponent` to override it and pass in the organization for that condition. 
Extract the collection init logic into a function that can be overwritten in the web vault's organization vault
> [fix] Expose collection filter init function for client override

- angular/src/modules/vault-filter/vault-filter.component.ts
https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-333
This will be cherry-picked to rc
An issue that has been encountered in the web vault for the new organization filters in the filters bar is that they are sometimes hidden on initial login, because a sync didn't complete in time to create the filter component. 
This bug has also been found in desktop, and so the method that handles this in web's `VaultFiltersComponent` is being pulled back to jslib.
The ideal way to do this would be to be able to subscribe to organizations and have the object update on sync, but for now this is a manual process following a pattern set by collections.
The function has been moved to jslib as-is from web.
> [fix] Move web's VaultFiltersComponent.reloadOrganizations() method to jslib

- angular/src/components/ciphers.component.ts
- common/src/services/search.service.ts
- Replicate same functionality of being able to search for texts with accented characters using normal texts. 
- **angular/src/components/ciphers.component.ts:** Added `normalize("NFD").replace(/[\u0300-\u036f]/g, "")` to the `searchText` variable to strip off accent from a character. 
- This PR is related to https://github.com/bitwarden/web/pull/1690 and https://github.com/bitwarden/jslib/pull/804
> [PS-136] stripped off accented characters from search field for browser client

- angular/src/components/sso.component.ts
- angular/src/services/jslib-services.module.ts
- common/src/services/keyConnector.service.ts
Related to https://github.com/bitwarden/key-connector/pull/16.
If there is any error with Key Connector (including contacting Key Connector or an unhandled server error), the user remains logged in. This presents them with a lock screen or their vault, depending on the flow. Because they have a token and a locally generated user key, they can even create new ciphers etc.
I propose that if there is any error with Key Connector onboarding or fetching user keys, this is most likely unrecoverable and we should just log the user out.
- **common/src/services/keyConnector.service.ts** - add common error handling code - log the actual error to console, then log the user out and throw a custom error message for the toast.
- **angular/src/services/jslib-services.module.ts** - update dependencies
- …
> [EC-178] Logout on Key Connector error

- common/src/abstractions/state.service.ts
- common/src/services/state.service.ts
- common/src/services/sync.service.ts
Grant access to premium features immediately after upgrade without having to log out.
- **common/src/abstractions/state.service.ts:** abstract method `setCanAccessPremium` added.
- **common/src/services/state.service.ts:** implementation of the abstract method `setCanAccessPremium` with sets the current state of `hasPremiumPersonally` property when premium has been activated.
- **common/src/services/sync.service.ts:** calls the `setCanAccessPremium` method which syncs and sets the current state of `hasPremiumPersonally` property.
https://user-images.githubusercontent.com/13024008/169881648-b03aa6c3-baab-4f58-a036-0973668e1fe0.mov
> [PS-153] upgrade premium on refresh

- angular/src/components/sso.component.ts
- common/src/abstractions/api.service.ts
- common/src/models/response/ssoPreValidateResponse.ts
- common/src/services/api.service.ts
- [ X] New feature development
Handles token returned during `PreValidate()` call to pass back to `Login()` method on server - used to ensure the SSO redirect request was initiated by the user. Also handles adding user's hashed master password for validation during password reset enrollment (CSA-1 and CSA-2).
- **sso.component.ts:** Extract token from `PreValidate()` response and add to `Login()` request
- **organizationUserResetPasswordEnrollmentRequest.ts:** Extending password enrollment model to add hashed user master password.
- **api.service.ts:** Adding handling of returned token from `PreValidate()` call.
> CSA-2 SSO user interaction token

- common/src/services/state.service.ts
https://bitwarden.atlassian.net/browse/SG-358
Username and password generator settings don't use local storage for web, so they don't persist across sessions.
This is needed for a hotfix for web, and thus will need to be merged here and recreated in `clients`
Use the correct storage options for generator settings so they are persistent across web sessions
> [fix] Generator settings not persisting across web sessions
