bitwarden/jslib

src/abstractions/audit.service.ts
src/abstractions/crypto.service.ts
src/services/audit.service.ts
src/services/crypto.service.ts
src/services/utils.service.ts

Companion PR to https://github.com/bitwarden/browser/pull/526.

AuditService

---

src/services/api.service.ts

make src/services/api.service.ts work with https servers requiring client certificates

---

src/angular/components/view.component.ts
src/models/view/cardView.ts

Required for [bitwarden/desktop issue #78](/bitwarden/desktop/issues/78)

Adding mask and toggle for Card Security Code

---

src/angular/pipes/color-password.pipe.ts

I think the code (and its comment :D) explains it all. This is in preparation for the following PR to the desktop repo.

Added password coloring pipe (which also sanitizes HTML)

---

spec/common/misc/throttle.spec.ts
src/misc/throttle.ts
src/services/audit.service.ts

Randomly failing to check by passwords, I'm pretty sure its because ~2000 connections are made at the same time.

 Throttle calls to HIBP api

---

src/models/view/loginUriView.ts
src/models/view/loginView.ts

Closes https://github.com/bitwarden/browser/issues/850 and closes https://github.com/bitwarden/browser/issues/656

Ignore regex URI when launching

---

src/services/passwordGeneration.service.ts

See https://community.bitwarden.com/t/add-capital-letter-i-to-ambiguous-characters/5810

Add capital letter "I" to ambiguous characters

---

src/angular/components/lock.component.ts

This a requisite for https://github.com/bitwarden/desktop/pull/258 that aims to implement this: https://community.bitwarden.com/t/show-the-server-to-which-you-are-logged-in/5472

Allow the lock component to access the environmentService

---

src/electron/window.main.ts

fixes [https://github.com/bitwarden/desktop/issues/186](https://github.com/bitwarden/desktop/issues/186)

fix bitwarden/desktop#186 App not responding when NOT opening from tray

---

src/angular/components/view.component.ts

This function enables the two incoming pull request to set data when being draged.

Add function to copy data to drag transfer event

---

src/angular/components/add-edit.component.ts
src/angular/components/view.component.ts

- **Add-Edit component**: added support for "clone mode" 
- **View component**: added output property for the clone operation

[jslib] Updated shared components for cipher cloning

---

src/models/view/identityView.ts

we should not always append state as some countries do not have states in the addresses.

fix `fullAddressPart2` state if empty should not show in address line

---

src/importers/onepassword1PifImporter.ts

resolves #451 at https://github.com/bitwarden/web/issues/451

dont import trashed items into 1password.

---

spec/common/importers/lastpassCsvImporter.spec.ts
src/importers/lastpassCsvImporter.ts

throwing my hat in the ring to fix https://github.com/bitwarden/web/issues/443
builds off #57 
first time using typescript. suggestions welcome

fix lastpass import credit card expiration

---

src/angular/components/add-edit.component.ts

- **add-edit.component**: Check all collections associated with the given cipher during clone mode.

Show cipher collection ids during clone mode

---

src/importers/zohoVaultCsvImporter.ts

Zoho export header changed
attaching new Zoho CSV export file
[zoho_export.zip](https://github.com/bitwarden/jslib/files/4174847/zoho_export.zip)

zoho import password header chnges

---

src/importers/onepassword1PifImporter.ts

- **onepassword1PifImporter**: fixed missing whitespace that was triggering a lint warning

Fix lint warning with recent merge

---

src/angular/components/add-edit.component.ts

- **AddEditComponent.ts**: Include `this.cloneMode` in the conditional regarding the `login` type and setting a null URI if possible

Added missing clone mode condition

---

src/importers/encryptrCsvImporter.ts
src/importers/zohoVaultCsvImporter.ts
src/services/import.service.ts

Also fixed a few lint warnings on the zoho importer from someone that merged a PR last week.

support for encryptr csv importer

---

src/angular/components/password-generator.component.ts

> While an organizational password generator policy is enabled, alert the user that all/some settings are being adjusted.
- **password-generator.component.ts**: Add helper method used by the UI as to whether or not to show the policy in effect banner

Show policy in effect banner for password generator

---

src/angular/components/callout.component.html
src/angular/components/callout.component.ts
src/angular/components/password-generator.component.ts

- Made `policyInEffect` a property rather than a function.
- Brought over new callout component from web so that we can re-use it on other Angular clients

Moved callout to jslib, made policyInEffect a prop

---

src/abstractions/api.service.ts
src/services/api.service.ts

API service implementation for https://github.com/bitwarden/server/pull/661

API for getting policies by token

---

src/services/api.service.ts

A few fixes to this function after testing. Path was wrong and parameters needs URL encoding to be correct.

fixes to getPoliciesByToken

---

src/abstractions/policy.service.ts
src/services/policy.service.ts

- **abstractions/policy.service.ts**: Added missing semi-colons and added missing parameter for `getMasterPasswordPolicyOptions` function
- **policy.service.ts**: Added missing semi-colon and adjusted the import order

Fixed lint warnings

---

appveyor.yml
package.json

Add the lint to CI script

---

src/abstractions/passwordGeneration.service.ts
src/angular/components/password-generator.component.ts
src/services/passwordGeneration.service.ts

> Rearrange the current password generation code in order to update the UI if password length varies based on the selected options.  Fixes [Web Bug #497](https://github.com/bitwarden/web/issues/497)
- **abstractions/passwordGeneration.service.ts**: Added `normalizeOptions` function
- **password-generator.component.ts**: Removed all non-application dependent logic from the `normalizeOptions` function.  Added call to the `passwordGenerationService.normalizeOptions`
- **passwordGeneration.service.ts**: Added 'normalizeOptions` function. Fully replicates existing logic except has added call to new `sanitizePasswordLength` function. Created `sanitizePasswordLength` function that can be called with UI changes or for password generation only.  Maintains existing workflows but will now properly …

Password Generator Sanitize Length

---

src/abstractions/vaultTimeout.service.ts
src/services/vaultTimeout.service.ts

> Implement TODOs in `VaultTimeoutService` in regards to new `logout` action
- **vaultTimeout.service.ts**
- Updated constructor to include new `loggedOutCallback` for bubbling up when the platform in use should logout due to interval checks
- `checkVaultTimeout` now has updated variable names and includes logic to pivot based on the saved action. 
- `logout` uses the newly created callback to alert the application
-  `setVaultTimeoutOptions` now saves the action as well

[Auto-Logout] Implement logout functionality in VaultTimeoutService

---

package-lock.json
package.json
src/services/search.service.ts

cf. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43044

Update lunr type

---

src/importers/enpassJsonImporter.ts

Resolves https://github.com/bitwarden/web/issues/519

Add support for enpass sensitive fields

---

src/misc/utils.ts

brings jslib inline with recent changes in mobile. ref https://github.com/bitwarden/mobile/pull/860

fixes to url parsing

---

src/importers/enpassJsonImporter.ts

I broke enpass importer with https://github.com/bitwarden/jslib/commit/5e24e396ab9c1089dcb08f8e0e401ab610d3acc6#diff-26ab5a449ddd924e343bfe0ecde5725e
This fixed it

default to text field type

---

src/abstractions/api.service.ts
src/services/api.service.ts

Client API implementation for getting an enterprise portal auth token.

getEnterprisePortalSignInToken api

---

src/models/view/loginUriView.ts

Resolves https://github.com/bitwarden/browser/issues/1296

Do not process hostname for regex matching URIs

---

src/angular/components/register.component.ts
src/models/request/registerRequest.ts

Add the referenceId to the registration component.

Add referenceId to register component

---

src/angular/components/add-edit.component.ts

This is in relation to [PR #1272](https://github.com/bitwarden/browser/pull/1272) in bitwarden/browser

Added current date variable to add-edit component

---

src/abstractions/api.service.ts
src/abstractions/auth.service.ts
src/angular/components/lock.component.ts
src/angular/components/two-factor.component.ts
src/misc/utils.ts
src/models/domain/authResult.ts
src/models/request/tokenRequest.ts
src/models/response/identityTokenResponse.ts
src/services/api.service.ts
src/services/auth.service.ts
src/services/constants.service.ts

support for sso implementation on server and web
- update auth service to support sso flow with `logInSso`
- lock component to support sso cases in which there is no existing master password hash. call to api for verification
- pull kdf info and new reset master password properties from token response
- add sso state and code verified keys to constants

sso support

---

CONTRIBUTING.md

Got some questions via Gitter regarding jslib and figured this is likely a common barrier to contributions in understanding how to use and perform core development against jslib when addressing issues or changes across JavaScript client repos.

Updated contribution guidance for developers

---

src/importers/keepass2XmlImporter.ts

resolves https://github.com/bitwarden/web/issues/579

parse otp for keepass import

---

src/angular/components/register.component.ts
src/models/domain/referenceEventData.ts
src/models/request/referenceEventRequest.ts
src/models/request/registerRequest.ts

Companion to the server change for reference id to be a data field (json blob) with a structured model for API submission through jslib. Need to capture 3 data points to send back through for flow and layout in addition to id.

Reference id to data conversion

---

src/services/search.service.ts

Add custom fields to consideration when returning a filtered list of ciphers
Added some custom fields fun to the basic search method
Fixes bitwarden/web#568

Bug.568.organization search ignores custom fields

---

src/angular/components/sso.component.ts
src/electron/window.main.ts

Allows for protocols access/deeplink callbacks to the main process for sso processing. Also fixes a bug in saving state when kicking off SSO.

callbacks for argv from window main

---

src/models/request/organizationUpdateRequest.ts
src/models/response/organizationResponse.ts

Need this to support updating the org id from the web vault settings pages (coming soon)

add support for org identifier to api models

---

src/angular/components/set-password.component.ts
src/angular/components/sso.component.ts

This PR moved the set password component to jslib so that we can re-use it in multiple clients.

abstract set password component to jslib

---

src/importers/yotiCsvImporter.ts
src/services/import.service.ts

A customer emailed us asking to support this simple importer for yoti

adds support for yoti csv importer

---

src/abstractions/api.service.ts
src/angular/components/sso.component.ts
src/models/data/organizationData.ts
src/models/domain/organization.ts
src/models/response/profileOrganizationResponse.ts
src/services/api.service.ts

Objective
Create a jslib environment that will allow for linking/unlinking existing users to organization SSO
Code changes
Created API passthroughs for the nearly created DeleteSsoUser API method
Added Identifier, UseSso, and SsoBound properties to some response models for use in bitwarden/web
Added a returnUri property to the sso component for better control over where we put users post SSO authentication
Alphabetized the 'S' section of the Api methods in api.service
**NOTE** this PR was resubmitted because the old one was showing unchanged files as changed, not sure why, but a fresh PR removed the bad diffs.

Link existing user to sso

---

src/angular/components/sso.component.ts

Split the length of the sso.component generated password in an attempt to bring URL size down

updated sso password string to be 32 characters

---

src/angular/components/sso.component.ts

Set codeVerifier length back to 64, it was determined this was not helping shrink URL size

reverted codeVerifier length back to 64

---

src/services/i18n.service.ts

I have no clue if what I did was correct. If it is not, please try to display the locale name. Thanks

Added locale name(ml)

---

src/enums/policyType.ts

> Allow organizations to specify whether or not SSO authentication is required to log in
- **policyType**: Added `SsoAuthentication` enumeration

[Require SSO] Add policy type enumeration

---

src/services/api.service.ts

Quick fix for lint errors (w/o muddying up what I'm currently working on with unrelated changes).

Fix lint errors/warnings

---

src/angular/components/register.component.ts

> In order to complete GDPR compliance, moving forward with new user creation, we need to have explicit user interaction for Terms of Service and Privacy Policy acknowledgement.
- **register.component.ts**: Added tracking boolean for showing terms/privacy message. Added tracking boolean for new checkbox. Adjusted `submit` logic to include a check for policies acceptance.

[GDPR] Added TOS/Privacy variables and logic

---

src/cli/commands/login.command.ts

Sibling to https://github.com/bitwarden/jslib/pull/210. Resolves the CLI portion of https://community.bitwarden.com/t/sso-issues-with-desktop-app-and-cli/15604.

Add normalized state compare for CLI

---

src/abstractions/export.service.ts
src/angular/components/export.component.ts
src/models/export/card.ts
src/models/export/cipher.ts
src/models/export/cipherWithIds.ts
src/models/export/collection.ts
src/models/export/collectionWithId.ts
src/models/export/field.ts
src/models/export/folder.ts
src/models/export/folderWithId.ts
src/models/export/identity.ts
src/models/export/login.ts
src/models/export/loginUri.ts
src/models/export/secureNote.ts
src/services/export.service.ts

This PR adds support to the export service and components for "encrypted_json" export format.
- Extend all export models to support view and domain models
- Update export service to process encrypted vs decrypted formats

support for encrypted json export

---

src/electron/electronConstants.ts
src/electron/tray.main.ts
src/electron/window.main.ts

Improves fit & finish for the desktop application.
https://app.asana.com/0/1195018406457675/1198936531478093

Desktop fit & finish

---

src/models/view/loginView.ts

This helper method is for views to toggle quick totp copy buttons based on existence and the ability to viewPassword.
This PR is paired with PRs to bitwarden/browser#1493 and bitwarden/web#737
* **loginView.ts**: Uses utils to determine whether a totp authenticator key is saved to the cipher.

Has Totp method will be used to enable quick copy

---

src/cli/services/cliPlatformUtils.service.ts

Added comments to empty function block for CLI (doesn't have a "system theme" like other clients) to make linter happy.

Linter build fix

---

src/electron/electronConstants.ts

Missed this when reviewing changes from https://github.com/bitwarden/jslib/pull/234/files#diff-cb61939a40755604321a8ac627185b4f0d7e41306f77da89dbe8c439e09b71a7R10

fix lint error, missing semicolon;

---

src/abstractions/send.service.ts
src/models/view/sendView.ts
src/services/send.service.ts

Created a service method for the remove password function for a Send.
Added some helpful getters to SendView.

send removePasswordWithServer and model updates

---

src/services/constants.service.ts
src/services/system.service.ts

Improves the biometrics condition in the system.services.ts. Now checks that we have fingerprint for biometrics before skipping reload, which prevents clearing the fingerprint from memory.

Improve system.service biometrics condition

---

src/angular/components/send/send.component.ts

It looks like fuzzy searching sends isn't working, even in web. This PR wires that up.

Send search

---

src/angular/components/send/add-edit.component.ts

Add toggle password visibility to send add-edit.component
* **add-edit.component.ts**: Standard password visibility toggle.
testing will be described in web client PR.

Add password toggle to add-edit

---

spec/common/importers/onepasswordMacCsvImporter.spec.ts
spec/common/importers/onepasswordWinCsvImporter.spec.ts
spec/common/services/consoleLog.service.spec.ts
spec/common/services/export.service.spec.ts
src/angular/components/sso.component.ts
tslint.json

Match trailing comma linter rules

Match tslint rules

---

src/models/response/emergencyAccessResponse.ts

This PR is required to support the changes described in https://github.com/bitwarden/server/pull/1132. Refer to that PR for explanation.

Improved handling of grantor access to organizations after takeover

---

src/angular/components/send/add-edit.component.ts
src/services/send.service.ts

Adds some functions to the base jslib components for adding "copy send link on save" option when creating/editing a Send.

support for copying send link to clipboard on save

---

src/angular/components/send/send.component.ts

> The browser extension child class needs a bit more flexibility in terms of the following functions: `ngOnInit, load, and search`
- **send/send.component**: Added `hasSearched` tracking boolean that is used for showing search results in the same component, smoothly. Added anonymous function for `onSuccessfulLoad` in order to run some client-side calculations before considering the data `loaded`. Removed call to `load` in `ngOnInit` because additional client-side operations need to take place before calling `load` in the browser extension.
- The call to remove `load` from `onInit` will need to be updated and re-implemented for the child classes in the `web` and `desktop` repositories immediately following the merge of this PR

[Send] Add more flexibility to base component

---

src/abstractions/api.service.ts
src/models/response/emergencyAccessResponse.ts
src/services/api.service.ts

This PR is required to support the changes described in https://github.com/bitwarden/server/pull/1132. Refer to that PR for explanation, particularly my latest comment [here](https://github.com/bitwarden/web/pull/820#issuecomment-775632609).

Improved handling of grantor access to organizations after takeover (refactored)

---

src/angular/components/send/add-edit.component.ts

Refactored two simple Send properties (`title` and `editMode`) into getters for better reuse & change detection. This update shouldn't impact any clients unless they want it to.

refactored a few properties into getters

---

src/angular/components/send/add-edit.component.ts

Added a property & method for handling hiding optional fields for Sends

added toggle options logic

---

src/angular/components/callout.component.html
src/angular/components/callout.component.ts

> The latest additions to the Browser extension for Send enable the `app-callout` banner to be clicked and perform an action. Update the share component to allow each platform to add hover/active/focus states to improve UX.
- **callout.component.html**: Applies a `clickable` styling based on the Input `clickable`
- **callout.component.ts**: Added `clickable` Input parameter

[Send] App Callout input

---

src/models/domain/sendAccess.ts
src/models/response/sendAccessResponse.ts
src/models/view/sendAccessView.ts

Added properties from https://github.com/bitwarden/server/pull/1166 to relevant jslib models

added props to send access models

---

src/angular/components/send/add-edit.component.ts

Resolves https://app.asana.com/0/1199659118818122/1199987076477970/f
Sibling to https://github.com/bitwarden/mobile/pull/1292

clear Send password if whitespace

---

src/angular/components/send/add-edit.component.ts

Added date/time fallbacks on Send add/edit using separate props for browsers that don't support `<input type=datetime-local>`

Date time fallbacks

---

src/models/request/sendRequest.ts
src/services/send.service.ts

Client-side changes coupled to bitwarden/server#1175
* **sendRequest.ts/send.service.ts**: include optional file length. This will be required for File type sends

Include File size in SendRequest

---

src/abstractions/platformUtils.service.ts
src/angular/components/export.component.ts

Required to support https://github.com/bitwarden/web/pull/866.

Expand encrypted export warning

---

src/angular/components/send/add-edit.component.ts

use send.bitwarden.com redirect as base URL for send links in prod

use send.bitwarden.com

---

src/angular/components/send/send.component.ts

missed adding this to send listing copy function as ewll

update share link on send list copy

---

spec/common/importers/testData/safeInCloud/testData.xml.ts

Just a semicolon missing at the end of spec/common/importers/testData/safeInCloud/testData.xml.ts

Fixes linting error introduced with PR #307

---

src/services/cipher.service.ts
src/services/fileUpload.service.ts
src/services/send.service.ts

I forgot to await fileUploadService methods. This PR fixes that error.
* **cipher.service.ts**: await `uploadCipherAttachment`
* **send.service.ts**: await `uploadSendFile`

Await file upload service

---

src/models/api/permissionsApi.ts

> Allow users with the `custom` type to be able to manage reset password functionality.
- **permissionsApi**: Added `manageResetPassword` boolean.  Updated constructor to set variable based on the response property from the server

[Reset Password] Custom user permission

---

src/services/search.service.ts

In Chinese, one character is also  meaning.
Such as A char `长` to `long`, `短` to `short`.
So we need to input one character to trigger searching.

Optimize isSearchable for Chinese.

---

src/angular/components/send/add-edit.component.ts

jslib logic for https://github.com/bitwarden/web/pull/915

Require user to verify email to use file Send

---

src/services/api.service.ts

Related to bitwarden/server#1266. Fixes overlapping api endpoint

Move renew endpoint to fix overlapping endpoint issue

---

src/angular/services/lock-guard.service.ts
src/angular/services/unauth-guard.service.ts

Supporting jslib code for https://github.com/bitwarden/desktop/pull/847
Note that `unauthGuard` is lifted up from the web repo, unchanged other than to update the import paths. `lockGuard` is new, but based on the same logic.

Add unauthGuard and lockGuard to prevent unintended navigation

---

src/angular/components/send/add-edit.component.ts

Required to support https://github.com/bitwarden/web/pull/949

Fix "copy link to clipboard" for large file Sends

---

spec/common/importers/lastpassCsvImporter.spec.ts
src/importers/lastpassCsvImporter.ts

Fixes bitwarden/desktop#795
The lastpassCsvImporter wasn't copying the totp value into the cipher.
Added test to verify

Add import of totp from Lastpass

---

src/abstractions/passwordReprompt.service.ts
src/abstractions/platformUtils.service.ts
src/angular/components/add-edit.component.ts
src/angular/components/view.component.ts
src/cli/services/cliPlatformUtils.service.ts
src/electron/services/electronPlatformUtils.service.ts
src/enums/cipherRepromptType.ts
src/enums/eventType.ts
src/models/data/cipherData.ts
src/models/domain/cipher.ts
src/models/request/cipherRequest.ts
src/models/response/cipherResponse.ts
src/models/view/cardView.ts
src/models/view/cipherView.ts
src/services/cipher.service.ts
src/services/passwordReprompt.service.ts

Revert of https://github.com/bitwarden/jslib/commit/3c872e56f27ae78fb922b765d7601886b5c39f78 now that `rc` branch has been cut.

Password reprompt

---

src/abstractions/totp.service.ts
src/services/constants.service.ts
src/services/totp.service.ts

Enable [Extension PR #1626](https://github.com/bitwarden/browser/pull/1626) by extending the jslib with proper constant and `TotpService` method.

feat: Help enable copying of TOTP code when auto filling credentials

---

src/abstractions/totp.service.ts
src/services/constants.service.ts
src/services/totp.service.ts

See https://github.com/bitwarden/browser/pull/1843

Copy TOTP after autofill on page load by default

---

src/models/request/importDirectoryRequest.ts

Include largeImport in import request. Related to bitwarden/directory-connector#118 & bitwarden/server#1311

Add largImport to request model

---

src/enums/eventType.ts

> Sync with server `EventType` enumeration. Add new `AdminResetPassword` value
- **eventType.ts**: Added `OrganizationUser_AdminResetPassword` enum value

[Reset Password] Add AdminResetPassword event type

---

src/electron/services/electronMainMessaging.service.ts

See https://github.com/bitwarden/desktop/pull/929

Respond to OS theme changes

---

angular/src/services/lock-guard.service.ts
angular/src/services/unauth-guard.service.ts

See https://github.com/bitwarden/browser/pull/1883

Refactor canactivate guards

---

common/src/misc/tldjs.noop.ts
common/src/misc/utils.ts
spec/common/misc/utils.spec.ts

See more info here: https://app.asana.com/0/1169444489336079/1200474469788269/f.
* strip dollar signs from URI before calling `getDomain()`.
`browser/jslib` will need to be bumped after this is merged.

Improve URL parsing

---

angular/src/components/login.component.ts
electron/src/window.main.ts

See https://github.com/bitwarden/desktop/pull/970

[macOS] Don't enable secure input when app is not in focus

---

common/src/models/response/organizationUserBulkPublicKeyResponse.ts

See https://github.com/bitwarden/web/pull/1071
I expect this will be cherry-picked into `rc`

Fix fingerprint phrases

---

common/src/models/request/sendWithIdRequest.ts
common/src/models/request/updateKeyRequest.ts

See https://github.com/bitwarden/server/pull/1417

[send.key] Add models to update send.key with account key

---

common/src/enums/eventType.ts
common/src/models/response/eventResponse.ts

Add support for the provider events added in https://github.com/bitwarden/server/pull/1475

[Provider] ProviderOrganization events

---

common/src/models/response/identityTwoFactorResponse.ts

Update response property name to match late change in bitwarden/server#1469

Rename captcha bypass token

---

common/src/abstractions/api.service.ts
common/src/models/request/provider/providerOrganizationCreateRequest.ts
common/src/services/api.service.ts

Changes in accordance with bitwarden/server#1488

Provide owner with Provider client org create requst

---

common/src/misc/utils.ts

Helper function that returns an array of enum values to iterate over. Needed for bitwarden/web#1107

Iterate over enum values

---

common/src/enums/eventType.ts

Related to bitwarden/server#1496. Adds the new event types to jslib.

Add event type for provider accessing client vault

---

common/src/enums/eventType.ts

Add new event type for https://github.com/bitwarden/server/pull/1560

Add event type for ResetSsoLink

---

common/src/abstractions/environment.service.ts

I'm looking to move the [WebConstants.ts](https://github.com/bitwarden/web/blob/master/src/services/webConstants.ts) values to the config files following the pattern set in https://github.com/bitwarden/web/pull/1151. This change requires the Type addition of PayPalConfig to the Environment Service.

Adding a PayPalConfig environment type

---

angular/src/components/export.component.ts
common/src/enums/policyType.ts

Adds support for the new policy which disables personal vault export.
Asana: https://app.asana.com/0/1198901840263430/1200900473757545

Disable Private Vault Export Policy

---

common/src/services/constants.service.ts
electron/src/electronConstants.ts

https://community.bitwarden.com/t/automatic-biometrics-prompt-on-open-popup/17383
This adds constants required by the parent PR: https://github.com/bitwarden/browser/pull/2065

Add constants for biometrics auto-prompt option

---

common/src/abstractions/api.service.ts
common/src/models/request/organizationCreateRequest.ts
common/src/models/request/organizationSubscriptionUpdateRequest.ts
common/src/models/request/seatAutoscaleRequest.ts
common/src/models/response/organizationResponse.ts
common/src/services/api.service.ts

Asana Ticket: https://app.asana.com/0/0/1200970162914676/f
Service updates for organization autoscaling. See bitwarden/server#1585

Organization autoscaling

---

angular/src/components/add-edit-custom-fields.component.ts

Fix non-explicit import paths, which are now broken due to #490.

Fix import paths in add-edit-custom-fields.component

---

angular/src/components/add-edit-custom-fields.component.ts

Fix incorrect capitalisation in https://github.com/bitwarden/jslib/pull/493, which was enough for it to build locally but fail tests.

Fix typo in import paths

---

electron/src/biometric.darwin.main.ts

Fixes a missing import path I forgot in #490

Fix forgotten imports

---

node/src/cli/models/response/fileResponse.ts

Added a new response type/object for the CLI to response file file data. This is needed for the CLI `serve` work, which will be opened in a separate PR with the CLI repo.

file response for CLI

---

angular/package-lock.json
common/package-lock.json
common/package.json
electron/package-lock.json
node/package-lock.json

Bump the SignalR package to 5.0.10.

Bump signalr to 5.0.10

---

package-lock.json

#498 we bumped the dependencies of several pacakges, to minimize the conflicts this PR also bumps the packages in the root project.

Bump packages in root jslib

---

angular/src/components/environment.component.ts
common/src/abstractions/api.service.ts
common/src/abstractions/environment.service.ts
common/src/enums/permissions.ts
common/src/models/api/permissionsApi.ts
common/src/models/api/ssoConfigApi.ts
common/src/models/data/organizationData.ts
common/src/models/domain/organization.ts
common/src/models/request/organization/organizationSsoRequest.ts
common/src/models/response/organization/organizationSsoResponse.ts
common/src/models/response/profileOrganizationResponse.ts
common/src/models/response/profileProviderOrganizationResponse.ts
common/src/services/api.service.ts
common/src/services/environment.service.ts

Adds the necessary model changes to support setting up and configuring sso using the web vault.
- **angular/src/components/environment.component.ts**: Remove `enterpriseUrl`, since the service is now gone.
- **common/src/services/environment.service.ts**: Remove enterprise related methods.
- **common/src/abstractions/api.service.ts**: Remove `getEnterprisePortalSignInToken`, add `getOrganizationSso` and `postOrganizationSso`.
- **common/src/enums/permissions.ts**: Remove `Permissions.AccessBusinessPortal`.
- **common/src/models/response/organization/organizationSsoResponse.ts**: Added response model for SSO configuration.
- **common/src/models/request/organization/organizationSsoRequest.ts**: Added request modal for SSO configuration.

Remove Business Portal, add SSO configuration models

---

common/src/abstractions/user.service.ts
common/src/models/response/subscriptionResponse.ts
common/src/services/user.service.ts

Families for enterprise/redeem card

---

common/src/abstractions/api.service.ts
common/src/services/api.service.ts

Add resend email to api service

---

angular/src/components/add-edit-custom-fields.component.ts
common/src/models/export/field.ts

Fix QA feedback on linked fields:
* CLI did not show the new `Field.LinkedId` property, because it was missing from the export models (which are used by CLI for json string representations)
* Angular clients were making all field types "linked" when the cipher type changed
* **common/src/models/export/field.ts** - add `linkedId` to the export model. I haven't added it to the template, because it's an optional field and I think it's unlikely to be set via CLI (it takes an enum, it's for use in browser, it's only used for 1 field type).
* **angular/src/components/add-edit-custom-fields.component.ts** - change `=` to `===` in the filter
jslib will need to be updated on all Angular clients.
No additional testing other than making sure the bugs are fixed.

[Linked Fields] Fix QA feedback

---

common/src/models/api/ssoConfigApi.ts
common/src/models/data/organizationData.ts
common/src/models/domain/organization.ts
common/src/models/response/profileOrganizationResponse.ts
common/src/models/response/profileProviderOrganizationResponse.ts
common/src/services/keyConnector.service.ts

Adds the new `useKeyConnector` to domain objects.
Resolves https://app.asana.com/0/1201363553288890/1201363553288934

Add useKeyConnector flag

---

common/src/abstractions/api.service.ts
common/src/services/api.service.ts

Before saving Key Connector config, ping the Key Connector URL to make sure it's alive.
* **common/src/services/api.service.ts** - add the API call to the api service. This uses the existing `/alive` endpoint on Key Connector, which should just return a JSON containing the current date and time.
Try saving the Key Connector config with valid and invalid Key Connector URLs. If the URL is invalid (i.e. Key Connector cannot be reached), you should get an error toast.

[Key Connector] Add getKeyConnectorAlive to ApiService

---

angular/src/components/verify-master-password.component.html

I forgot to include the confirm help text in #553

Add confirm identity helper text to password in verify component

---

common/src/enums/eventType.ts

* **file.ext:** Description of what was changed and why

[Key Connector] Add FirstSsoLogin event

---

common/src/models/response/organizationUserResponse.ts

Adds `usesKeyConnector` to the `organizationUserUserDetailsResponse, which is needed for the changed delete warning.
https://app.asana.com/0/1201363553288890/1201385116854988

Add usesKeyConnector to OrganizationUserUserDetailsResponse

---

angular/src/components/lock.component.ts

Adds support for hiding the password input on the lock screen if using key connector.
https://app.asana.com/0/1201363553288890/1201390561003506

Add support for hiding input on lock screen if using key connector

---

node/src/cli/services/cliPlatformUtils.service.ts

Provide a synchronous application version for node CLI Platform Utils Service. The CLI needs a sync version in order to create the api service in the `Main` constructor.
None, test implementation PR

Fix cli user agent

---

common/src/abstractions/api.service.ts
common/src/services/api.service.ts

Add sponsorship pre-validate endpoint which returns whether the provided token is valid or not.
None, test via web PR

Add sponsorship pre validate endpoint

---

angular/src/components/toastr.component.ts
angular/src/services/jslib-services.module.ts
common/src/abstractions/platformUtils.service.ts

As a part of upgrading Angular, I noticed that the toaster library we use still depends on Angular 11. This PR adds the nessesary modules to switch over to ngx-toastr.
* **angular/src/components/toastr.component.ts:** Add a new component for the toast, this lets us correctly handle the multiple themes with different icons without having to add inline svg.
* **common/src/abstractions/platformUtils.service.ts:** Make toast options strictly typed.
We'll need to do a regression sweep to verify toasts still looks the same as before.

Add toastr component

---

package-lock.json
package.json

After bumping Angular today, I was about to continue work on a different task and realized an updated `package-lock.json`  after running `npm i`
* **package-lock.json:** Update after running `npm i`

Sync package-lock.json after Angular bump

---

.prettierignore
package.json

The pre-commit hook which was added recently, did not run on all files (html was missing for example).
- **.prettierignore:** Add `.github/workflows` to ignore
- **package.json:** Add all filetypes to prettier and ignore via `.prettierignore`

Fix prettier

---

angular/src/services/lock-guard.service.ts
common/src/models/domain/account.ts
common/src/models/domain/environmentUrls.ts
common/src/models/domain/globalState.ts
common/src/services/environment.service.ts
common/src/services/state.service.ts
common/src/services/stateMigration.service.ts

https://app.asana.com/0/1200804338582616/1201630086148170
This PR addresses a couple of small issues and may be best read by going through each commit. The main things being addressed here are:
1. EnvironmentUrls need to be account specific, and currently they are global
2. Performance concerns with the state service
3. A bug in the logout flow that could leave applications in a semi-authenticated state
* See commits and descriptions

Misc Account Switching Fixes & Refactors

---

electron/src/window.main.ts

Disables the built in spellchecker in electron. Should remove a startup request to fetch the dictation from googles CDN.

Disable spell checking

---

common/src/services/token.service.ts

Logging in with the bwdc cli was throwing an error: "No amr found".
* **common/src/services/token.service.ts**: `getIsExternal` checks whether the token has the `external` amr claim. It appears that when logging in with org api credentials, there is no amr claim, so we should do an early return in that case without throwing the error.
* confirm user can log in and perform basic sync with bwdc cli.
* basic regression testing on an existing user being required to convert to key connector (in one of the other Angular clients, e.g. web or desktop)

Fix "no amr found" error in bwdc cli

---

common/src/services/state.service.ts

Save `usesKeyConnector` using `defaultOnDiskOptions` instead of `defaultInMemoryOptions` so that it persists between CLI commands. 
**cli will need a jslib update after merging.**
Basic regression testing to make sure clients correctly detect that the user is using Key Connector.

Save usesKeyConnector using defaultOnDiskOptions

---

package-lock.json
package.json
spec/support/jasmine.json

Directly run jasmine tests without needed to repeat transpilation
* **package.json**: Add jasmine-ts and ts-node
* **jasmine.json**: change test files to `.ts` files
None

Use node-ts and jasmine-ts to run tests

---

package.json

I didn't update `test:node:watch` properly when converting to jasmine-ts in #621 
None

watch `ts` files and source directly

---

angular/src/components/icon.component.ts

Updates the fallback icon image from `fa-globe` to `bwi-globe`.

Update the fallback icon name

---

angular/src/components/callout.component.html
angular/src/components/verify-master-password.component.html

Icon fixes for callouts and verify mp

Icon fixes for callouts and verify mp

---

common/src/services/passwordGeneration.service.ts

Fix bug where no passwords were being recorded in the history.
**Note:** this will be cherry-picked to `rc`.
- **common/src/services/passwordGeneration.service.ts** - fix null check. If the history has not been decrypted, then you need to decrypt it. Previously this block was being skipped, so history was never being decrypted, it assumed there was no history, and it was recreating it from scratch every time.

Fix password generator history

---

common/src/abstractions/platformUtils.service.ts
common/src/enums/clientType.ts
common/src/models/request/identityToken/passwordTokenRequest.ts
common/src/services/api.service.ts
electron/src/services/electronPlatformUtils.service.ts
node/src/cli/services/cliPlatformUtils.service.ts

Adds two new headers included in each request. I decided to not re-use the `DeviceType`, since it's more granular and we throw away the client type in `getDeviceString`.
`Bitwarden-Client-Name`: `[web, browser, desktop, cli, connector, mobile]`
`Bitwarden-Client-Version`: `1.41.0`
This will allow us to get an insight into which versions are currently in use.
- **common/src/abstractions/platformUtils.service.ts:** Added new method, `getClientType`.
- **common/src/enums/clientType.ts:** New enum with the client types.
Should be covered in general regression testing.

Add headers for client type and client version

---

angular/src/components/attachments.component.ts
angular/src/components/two-factor-options.component.ts
node/src/cli/commands/login.command.ts

> Update all `help.bitwarden.com` and `bitwarden.com/help/article/*` to the new `bitwarden.com/help/*` URL pattern
- **attachments.component.ts**: Updated help URL pattern
- **two-factor-options.component.ts**: Updated help URL pattern
- **login.command.ts**: Updated help URL pattern
- Make sure URL links don't 404 and take you to the correct page

[Help] Update links to new pattern

---

common/src/services/appId.service.ts

`appId` is currently being stored in `sessionStorage` and therefore users get a "New Device Logged in from ..." for each tab even though it's the same device. 
- **appId.service.ts:** Get and save `appId` from local storage.
- Ensure that logging in from a new tab in web does not send a "New Device Logged in from ..."
- Ensure that logging in from all other clients properly results in a new device email the first time and does not send one just for new sessions.

Fix new device login

---

common/src/enums/stateVersion.ts
common/src/services/stateMigration.service.ts
common/src/services/token.service.ts

Fix bug where user will not have premium after upgrading, until they log out and log back in.
Note: will be cherry-picked to `rc`
- `common/src/services/stateMigration.service.ts` - add a new state migration to read the premium status from the accessToken and then save it to that account
- `common/src/services/token.service.ts` - extract token decoding logic into a static method to avoid circular dependencies (ty @MGibson1)

Add StateVersion.Three to fix premium migration

---

common/src/services/state.service.ts

https://github.com/bitwarden/jslib/pull/661 resolved a bug causing "On Restart - Logout" timeouts to not work, but introduced a bug where "Never - Logout" timeouts do not work. This is because we never store the access token to disk for logout actions, but we should for never logout.
* Created a helper for timeout based options
* Added a check for `timeout != null` to the timeout based options conditional, and to the conditional that manages this behavior during login scaffolding. 
* Applied the updated timeout based options to any getters/setters that were using it before.
I tested never lock, never logout, on restart lock, and on restart logout - all were behaving as expected.

[bug] Also check for a never lock timeout when determining where to put tokens

---

common/src/services/state.service.ts

https://github.com/bitwarden/jslib/pull/675 did not
1. Update to use GetAccount instead of directly calling storage
2. Pass in a userId, causing us to depend on an active user Id, except on login none exists.
* Use GetAccount
* Pass in userId to setAccount

Use getAccount when scaffolding + pass in the correct userId

---

common/src/services/vaultTimeout.service.ts

Clears the automatic key after manually locking the vault.
Regression around locking / unlocking. Restart the app sometimes, and verify biomerics work.

Clears the key after locking

---

angular/src/components/export-scope-callout.component.ts
angular/src/pipes/color-password-count.pipe.ts
angular/src/scss/bwicons/styles/style.scss

Fix linting after merging #341, as the CI checks are not run on community PRs.
- **file.ext:** Description of what was changed and why

Fix linting

---

angular/src/components/lock.component.ts

Expose the `logService` in the lock base component.

Expose logger in lock component

---

angular/src/directives/not-premium.directive.ts
angular/src/directives/premium.directive.ts
angular/src/directives/unless-premium.directive.ts

Adds two directives which will allow us to do the following.
```html
<span *appPremium>Premium</span>
<span *appNotPremium>No Premium<span>
```

Add premium and unless-premium directives

---

common/src/models/domain/organization.ts

jslib changes for https://github.com/bitwarden/web/pull/1524.
https://bitwarden.atlassian.net/browse/SG-18
* **common/src/models/domain/organization.ts** - move logic from `organization-layout.component` to here. These getters determine which tabs in the org admin view the user can see, and in turn, whether they can access the org admin view at all. I don't like mixing client-specific view logic into this model, but we need to be able to filter by `canAccessAdminView` in several places and this seemed like the least bad solution.
Under main ticket.

[End User Vault Refresh] Organization changes

---

common/src/models/domain/organization.ts

This enables the latest changes in https://github.com/bitwarden/web/pull/1524.
In https://github.com/bitwarden/jslib/pull/713 I moved access permissions into the jslib organization model. This is because we need to access it from various places in web and I wanted it to live in a single place. But really we should not hard-bake client permissions into a jslib model, and I hit this issue pretty quickly when I needed to change these permissions.
This replaces the previous changes with a more flexible method that will take an array of `Permission`s and evaluate it for the organization. This is moved from web's `organization-type-guard.service.ts` so it can be used more generally.
As above

[End User Vault Refresh] Refactor route permission checking

---

angular/src/jslib.module.ts
angular/tsconfig.json

This creates a `JslibModule` which declares & exports all the injectables (components and pipes) contained in jslib. This allows clients to simply include `JslibModule` in their AppModule imports array, without repeating all the boilerplate for importing & declaring the individual injectables.
This will also facilitate further splitting our apps into modules, because sub-modules need to be able to import these without creating a circular dependency with the top-level `AppModule`.
Client PRs to follow.
Create `JslibModule`.
Most failures here should occur during build, but general regression testing should pick up anything else.

[JslibModule] Add JslibModule

---

angular/src/components/register.component.ts
angular/src/components/set-password.component.ts
angular/src/services/jslib-services.module.ts
common/src/abstractions/platformUtils.service.ts
common/src/enums/kdfType.ts
common/src/services/export.service.ts
common/src/services/send.service.ts
common/src/services/webCryptoFunction.service.ts
electron/src/services/electronPlatformUtils.service.ts
node/src/cli/services/cliPlatformUtils.service.ts
spec/web/services/webCryptoFunction.service.spec.ts

Remove Internet Explorer logic since we no longer supports that browser. While at it, I also extracted default KDF settings to constants.
EC-109
Regression test actions related to KDF.
- Register
- Login
- Change KDF
- Create, modify, access send with password

Remove Internet Explorer logic

---

electron/package-lock.json
electron/package.json
electron/src/updater.main.ts

Bumping a couple of dependencies to resolve some upgrading issues.
Regression testing around the electron update.

Bump electron and related dependencies

---

electron/src/updater.main.ts

Force the updater to be silent on Windows.
PS-100

Force updates to be silent

---

angular/src/jslib.module.ts

Resolves form bindings not working for components in `JslibModule`.

Fix jslibModule forms

---

angular/src/jslib.module.ts

Add Ellipsis pipe to jslib module so that it can be imported easily like the other pipes.
- **angular/src/jslib.module.ts:** Add ellipsis pipe

Add ellipsis pipe to jslib module

---

angular/src/jslib.module.ts

We're missing `ColorPasswordCountPipe` from `JslibModule`, which is breaking this feature in browser.
Add to JslibModule declarations and exports arrays.

[EC-137] Add ColorPasswordCountPipe to JslibModule

---

components/.storybook/main.js
components/package-lock.json
components/package.json
components/src/badge/badge.stories.ts
components/src/button/button.stories.ts
components/src/callout/callout.stories.ts
components/src/stories/Introduction.stories.mdx

Update introduction section for the Component Library.
Resolves CL-21 and CL-22.

Update introduction for CL

---

angular/jest.config.js
common/jest.config.js
electron/jest.config.js
node/jest.config.js

Removes the `roots` section of the jest config. This allows jest to watch src files and run tests accurately in watch.
PS-20
N/A

Update jest configs to remove roots

---

common/spec/domain/attachment.spec.ts
common/spec/domain/card.spec.ts
common/spec/domain/cipher.spec.ts
common/spec/domain/collection.spec.ts
common/spec/domain/encString.spec.ts
common/spec/domain/field.spec.ts
common/spec/domain/folder.spec.ts
common/spec/domain/identity.spec.ts
common/spec/domain/login.spec.ts
common/spec/domain/loginUri.spec.ts
common/spec/domain/password.spec.ts
common/spec/domain/secureNote.spec.ts
common/spec/domain/send.spec.ts
common/spec/domain/sendAccess.spec.ts
common/spec/domain/sendFile.spec.ts
common/spec/domain/sendText.spec.ts
common/spec/domain/symmetricCryptoKey.spec.ts
common/spec/utils.ts
common/src/models/api/sendFileApi.ts
common/src/models/data/cipherData.ts
common/src/models/data/sendFileData.ts
common/src/models/domain/attachment.ts
common/src/models/domain/loginUri.ts

Adds tests for our domain models.
- **common/src/models/domain/loginUri.ts:** It seems we had a bug where `match` wouldn't persist along when moving between data -> domain -> data.
- **common/src/models/data/cipherData.ts**: Remove unused `sizeName`.

Add tests for domain models

---

common/src/models/domain/globalState.ts

It seems we default the language to English for some reason which causes our applications to not detect whichever system language the user is using.
Since the field is nullable, I've changed it to default to undefined, which seems to work in web. We need to verify it behaves correctly in the other clients as well.
https://github.com/bitwarden/web/issues/1587
PS-179
Verify language detection works in all our clients.

Fix language always defaulting to english

---

angular/src/validators/notAllowedValueAsync.validator.ts

- **angular/src/validators/notAllowedValueAsync.validator.ts:** A validator that will get a value from an async method and compare it to the control value and return an error if they are equal.

Add in notAllowedValueAsync.validator.ts

---

common/src/abstractions/api.service.ts
common/src/enums/organizationConnectionType.ts
common/src/models/api/billingSyncConfigApi.ts
common/src/models/request/billingSyncConfigRequest.ts
common/src/models/request/organizationConnectionRequest.ts
common/src/models/response/organizationConnectionResponse.ts
common/src/services/api.service.ts

Adds api response/request for Organization connections
* **api.service**: CRUD for organization connections. I had to use a abstract method pattern vs our typical (and weird) property pattern to allow for generic arguments on the methods. These generics are used to correctly parse the config.
* **organizationConnectionType**: enum for the connection type.
* **billingSyncConfigApi**: the api response for billingSyncConfigs
* **billingSyncConfigRequest**: The api request model for billing sync config
* **OrganizationConnecitonRequest**: The api request model for general organization connections. Config types are limited by the `OrganizationConnectionRequestConfigs` type
* **organizationConnectionResponse**: The api response model for general organization connections. Config types are …

[PS-248] Feature/manage billing sync connection

---

common/src/services/api.service.ts

Uses correct endpoints for self-hosted families for enterprise create/revoke

Use self hosted endpoints for f4e

---

angular/src/modules/vault-filter/vault-filter.service.ts

https://github.com/bitwarden/desktop/pull/1487#discussion_r857248484

[bug] Add @Injectable to VaultFilterService

---

angular/src/components/two-factor.component.ts
common/src/models/request/twoFactorEmailRequest.ts

Add `DeviceId` to the 2FA email request and set it when calling the endpoint of resending the 2FA email to see if the 2FA email is because of a new device login.
Relates to: [Server change](https://github.com/bitwarden/server/pull/1977)
Clients updates:
- [Web](https://github.com/bitwarden/web/pull/1624)
- [Desktop](https://github.com/bitwarden/desktop/pull/1508)
- [Browser](https://github.com/bitwarden/browser/pull/2523)
- **common/src/models/request/twoFactorEmailRequest.ts:** Added `deviceIdentifier`
- **angular/src/components/two-factor.component.ts:** Set `deviceIdentifier` to the `TwoFactorEmailRequest` to check then if it's a 2FA email of a new device login.
On the clients' verification code screen, test that resending code works as expected on new devices login as well as on …

[PS-302] Added DeviceId to the Send 2FA email request

---

common/src/models/domain/organization.ts

Additional jslib changes for https://github.com/bitwarden/web/pull/1614.
These changes were originally in the client, but this code was moved to jslib during End User Vault Refresh.
* add the `ManageBilling` permission to permission checks

[EC-151] Hide Subscription/Billing information for Provider-managed organizations

---

.github/PULL_REQUEST_TEMPLATE.md

Testing requirements / QA notes are now in the Jira ticket templates, and can be removed from the Github PR templates.
The reviewer of any community PR is responsible for completing the testing notes in Jira.
- **file.ext:** Description of what was changed and why

Remove testing requirements from PR template

---

common/src/services/sync.service.ts

Resolve a defect from #771 where `syncSends` omitted the response.

[PS-568] Fix send sync not working as expected

---

common/src/enums/eventType.ts
common/src/models/export/eventExport.ts
common/src/models/response/eventResponse.ts
common/src/models/view/eventView.ts

Adds `Organization_SponsorshipSync` as a known event and InstallationId to event data.
> Note: Will be cherry picked into `rc`

[PS-655] Add `Organization_SponsorshipsSynced` event type

---

common/src/models/request/organizationUserResetPasswordEnrollmentRequest.ts

Require user verification for enrollment in password reset

[PS-616] Require auth for enrollment

---

angular/src/scss/icons.scss

Allows for overriding the icons path.

Add !default to icons path

---

angular/src/guards/lock.guard.ts

`LockGuard` wasn't redirecting properly because it had accidentally nested an array in an array for the `redirectUrl`.
**will be picked to rc**
Remove array nesting

[EC-237] Fix lockGuard redirect
